export * from './visualObjects';
export * from './textControls';
export * from './listControls';
export * from './drawingControls';
export * from './dataControls';
export * from './ribbonControls';
export * from './oleVisualControls';

import { PbSystemSymbolEntry } from '../../types';
import {
	PB_MANUAL_CORE_DATA_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_DATA_CONTROLS,
} from './dataControls';
import {
	PB_MANUAL_CORE_DRAWING_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_DRAWING_CONTROLS,
} from './drawingControls';
import {
	PB_MANUAL_CORE_LIST_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_LIST_CONTROLS,
} from './listControls';
import {
	PB_MANUAL_CORE_OLE_VISUAL_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_OLE_VISUAL_CONTROLS,
} from './oleVisualControls';
import {
	PB_MANUAL_CORE_RIBBON_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_RIBBON_CONTROLS,
} from './ribbonControls';
import {
	PB_MANUAL_CORE_TEXT_CONTROL_CATEGORIES,
	PB_MANUAL_CORE_TEXT_CONTROLS,
} from './textControls';
import {
	PB_MANUAL_CORE_VISUAL_OBJECT_CATEGORIES,
	PB_MANUAL_CORE_VISUAL_OBJECTS,
} from './visualObjects';

export const PB_MANUAL_CORE_VISUAL_SYSTEM_OBJECT_DATATYPE_CATEGORIES: readonly string[] = [
	...PB_MANUAL_CORE_VISUAL_OBJECT_CATEGORIES,
	...PB_MANUAL_CORE_TEXT_CONTROL_CATEGORIES,
	...PB_MANUAL_CORE_LIST_CONTROL_CATEGORIES,
	...PB_MANUAL_CORE_DRAWING_CONTROL_CATEGORIES,
	...PB_MANUAL_CORE_DATA_CONTROL_CATEGORIES,
	...PB_MANUAL_CORE_RIBBON_CONTROL_CATEGORIES,
	...PB_MANUAL_CORE_OLE_VISUAL_CONTROL_CATEGORIES,
];

export const PB_MANUAL_CORE_VISUAL_SYSTEM_OBJECT_DATATYPES: readonly PbSystemSymbolEntry[] = [
	...PB_MANUAL_CORE_VISUAL_OBJECTS,
	...PB_MANUAL_CORE_TEXT_CONTROLS,
	...PB_MANUAL_CORE_LIST_CONTROLS,
	...PB_MANUAL_CORE_DRAWING_CONTROLS,
	...PB_MANUAL_CORE_DATA_CONTROLS,
	...PB_MANUAL_CORE_RIBBON_CONTROLS,
	...PB_MANUAL_CORE_OLE_VISUAL_CONTROLS,
];