import type { PbSystemSymbolLocalizationOverlay } from '../../types';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_TOOLING } from './toolingLocalization';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_VISUAL } from './visualLocalization';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME } from './runtimeLocalization';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_CORE } from './core';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_DATAWINDOW } from './datawindow';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_INTEGRATION } from './integration';

export const PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL = [
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_CORE,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_TOOLING,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_VISUAL,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_DATAWINDOW,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_INTEGRATION,
] as const satisfies readonly PbSystemSymbolLocalizationOverlay[];
