import type { PbSystemSymbolLocalizationOverlay } from '../../types';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_TOOLING } from './tooling';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_VISUAL } from './visual';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME } from './runtime';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_CORE } from './core';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_DATAWINDOW } from './datawindow';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_INTEGRATION } from './integration';
import { PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_LANGUAGE } from './language';

export const PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL = [
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_CORE,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_TOOLING,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_VISUAL,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_DATAWINDOW,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_INTEGRATION,
  ...PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_LANGUAGE,
] as const satisfies readonly PbSystemSymbolLocalizationOverlay[];
