import type { PbSystemSymbolLocalizationOverlay } from '../../types';

/**
 * Spanish localization overlays for manual runtime domain entries.
 */
export const PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME = [
	// — Non-visual objects —
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ADOResultSet' }, text: { summary: 'Result set no visual de ADO.', documentation: 'The ADOResultSet object provides the ability to use ActiveX Data Object (ADO) record sets to return a result set to a client and to manipulate ADO Recordsets in PowerBuilder.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'BatchDataObjects' }, text: { summary: 'Colección no visual para procesar múltiples objetos de datos en batch.', documentation: 'The BatchDataObjects object specifies more than one DataWindow controls, DataStores, and child DataWindows to be used with the .NET DataStore Web API to perform data retrievals or updates. It is used with the RESTClient object to perform retrieve/update operations for multiple DataWindows at one time. BatchDataObjects has no events.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'NonVisualObject' }, text: { summary: 'Base de objetos no visuales personalizados.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ResultSet' }, text: { summary: 'Result set no visual interoperable con DataStore y ADO.', documentation: 'The ResultSet object provides the ability to use ActiveX Data Object (ADO) record sets to return a result set to a client. Use ResultSet objects with the CreateFrom and GenerateResultSet DataStore functions.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Connection' }, text: { summary: 'Conexión no visual a servicios o fuentes externas.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ContextInformation' }, text: { summary: 'Contexto no visual para metadata de sesión.', documentation: 'The ContextInformation object provides information about an application\'s execution context, including current version information. Using this information, you can modify display characteristics and application behavior.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ContextKeyword' }, text: { summary: 'Keyword de contexto no visual para metadatos runtime.', documentation: 'The ContextKeyword object provides environment information for the current context. In the default environment, the ContextKeyword object provides host workstation environment variables.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ErrorLogging' }, text: { summary: 'Objeto no visual para logging de errores.', documentation: 'The ErrorLogging object provides the ability to write messages to the log file used by the object\'s container, such as the NT system application log for Microsoft Transaction Server.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MLSync' }, text: { summary: 'Objeto no visual para sincronización móvil.', documentation: 'An MLSync object is derived from the MLSynchronization object base class. Its primary function is to launch dbmlsync.exe, a separate process that synchronizes a SQL Anywhere remote database with a consolidated database. The MLSync properties control the options used for the synchronization. MLSync events represent callbacks that are automatically triggered by dbmlsync.exe at specific times during the synchronization process.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MLSynchronization' }, text: { summary: 'Objeto no visual para sincronización móvil avanzada.', documentation: 'The MLSynchronization object is an abstract class from which MLSync objects are derived.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Pipeline' }, text: { summary: 'Pipeline no visual para procesos ETL y data movement.', documentation: 'A Pipeline system object is used to manage a data pipeline during execution. You use a Pipeline object by defining a standard class user object inherited from the built-in Pipeline object in the User Object painter. You can then access the Pipeline events by writing scripts that contain code for the events. For more information about piping data, see the section called “Piping Data Between Data Sources” in Application Techniques .' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PowerServerResult' }, text: { summary: 'Resultado no visual devuelto por operaciones PowerServer.', documentation: 'A PowerServerResult system object is used to store the result of merged operations. As suggested by the object name, this object and its functions only take effect when the application is deployed via the PowerServer project. This object and its functions will not be executed or modify how the application works in the traditional client/server environment (they will be ignored when the application is deployed via the PowerClient project or the Application project). Note PowerServerResult (as well as HTTPClient, CrypterObject, CoderObject, CompressorObject, DotNetAssembly, JSONGenerator, JSONParser, JSONPackage, OAuthClient, PDF Builder objects, RESTClient, SMTPClient, PowerServerLabel) does not support multi-threading.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SyncParm' }, text: { summary: 'Parámetro no visual para sincronización móvil.', documentation: 'A SyncParm object is a system structure that you can use to obtain runtime properties from a synchronization option window, and then pass these property values to an MLSync object. The SyncParm object has no events or functions.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Timing' }, text: { summary: 'Utilidad no visual para medición temporal.', documentation: 'Timing is a nonvisual system object that can be used when a Timer event cannot be associated with a window. To use a timing object, create a standard class user object that inherits from the Timing system class, and then create an instance of the inherited timing object.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TransactionServer' }, text: { summary: 'Servidor transaccional no visual.', documentation: 'The TransactionServer object provides information about the current transaction context and enables a component running in a transaction server to control the transaction and its own life cycle.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ULSync' }, text: { summary: 'Objeto no visual para sincronización UltraLite.', documentation: 'The ULSync object is derived from the MLSynchronization base class but is not supported in the current release.' } },

	// — System objects —
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Application' }, text: { summary: 'Objeto raíz de la aplicación PowerBuilder.', documentation: 'An application is a collection of PowerBuilder windows and objects that provide functionality for user activities, such as order entry or accounting activities. The Application object is the entry point into the applications. When a user runs an application, the Open event of the Application object is fired. The Open event triggers the script that initiates all the activity in the application.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PowerObject' }, text: { summary: 'Raíz de la jerarquía de tipos PowerBuilder.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'GraphicObject' }, text: { summary: 'Base de objetos gráficos.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DrawObject' }, text: { summary: 'Base de objetos de dibujo (línea, rectángulo, etc.).' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Structure' }, text: { summary: 'Tipo estructura (agrupación de campos).' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ArrayBounds' }, text: { summary: 'Describe los límites declarados de un array PowerBuilder.', documentation: 'A structure that specifies the upper and lower bounds of a single dimension of an array. It is used in the VariableCardinalityDefinition object. ArrayBounds has no events.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DataWindowChild' }, text: { summary: 'Referencia a un DataWindow hijo (DropDownDataWindow).', documentation: 'A DataWindowChild object is a nested report or a DropDownDataWindow within a DataWindow object. For example, a DataWindow object that populates a column having the DropDownDataWindow edit style is a DataWindowChild object. The DataWindowChild object is used for accessing DataWindow objects independently from DataWindow functionality, and it inherits from the system Structure object because it needs storage and autoinstantiation. A DataWindowChild object has no events. Obsolete functions Several DataWindowChild functions are described as obsolete, which means that although the functions operate as usual in this release, they will be removed in a future release. You should replace all use of these functions as soon as possible.' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DynamicDescriptionArea' }, text: { summary: 'Área de descripción para SQL dinámico.', documentation: 'DynamicDescriptionArea is a PowerBuilder system object that stores information about the input and output parameters used in Format 4 of dynamic SQL. PowerBuilder provides a global DynamicDescriptionArea named SQLDA that you can use when you need a DynamicDescriptionArea variable. If necessary, you can declare and create additional variables of this type using this system object as the datatype. For more information about using dynamic SQL, see the section called “Using dynamic SQL” in PowerScript Reference .' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DynamicStagingArea' }, text: { summary: 'Área de staging para SQL dinámico.', documentation: 'DynamicStagingArea is a PowerBuilder system object that stores information for use in dynamic SQL statements. The DynamicStagingArea object is the only connection between the execution of a statement and a Transaction object and is used internally by PowerBuilder. You cannot access information in DynamicStagingArea, and there are no properties associated with DynamicStagingArea. PowerBuilder provides a global DynamicStagingArea variable named SQLSA that you can use when you need a DynamicStagingArea variable. If necessary, you can declare and create additional variables of this type using this system object as the datatype. For more information about using dynamic SQL, see the section called “Using dynamic SQL” in PowerScript Reference .' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Environment' }, text: { summary: 'Información del entorno de ejecución.', documentation: 'The Environment object is a system structure used to hold information about the computing platform the PowerBuilder application is running on. You populate the Environment object using the GetEnvironment function. The Environment object has no events. For more information about the GetEnvironment function, see the section called “GetEnvironment” in PowerScript Reference .' } },
	{ locale: 'es', reviewed: false, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Message' }, text: { summary: 'Objeto global para paso de mensajes entre objetos.', documentation: 'The Message object is used to process events that are not defined by PowerBuilder, to communicate parameters between windows when you open and close them, and to specify whether optional parameters are used in TriggerEvent or PostEvent. You can also customize your own version of the Message object by defining a class user object inherited from the built-in Message object. For more information about creating a custom Message object, see the section called “Working with User Objects” in Users Guide .' } },
] as const satisfies readonly PbSystemSymbolLocalizationOverlay[];
