import { PbSystemSymbolEntry } from '../types';
import {
    dataWindowFunction,
    PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    PB_MANUAL_CORE_DATAWINDOW_SCROLL_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_SCROLL_OWNER_TYPES,
    PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
} from './common';

export const PB_MANUAL_CORE_DATAWINDOW_FUNCTION_CATEGORIES = [
    'Datos',
    'Metadatos',
    'Navegación',
    'Transacciones',
    'Visual',
    'Layout',
    'Contexto',
    'Texto',
] as const;

type DataWindowFunctionCategory = (typeof PB_MANUAL_CORE_DATAWINDOW_FUNCTION_CATEGORIES)[number];

type DataWindowFunctionDescriptor = {
    name: string;
    category: DataWindowFunctionCategory;
    summary: string;
    signature: string;
    appliesTo: readonly string[];
    ownerTypes: readonly string[];
};

const PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES = [
    'datawindow',
    'datastore',
] as const;

const PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO = [
    'DataWindow control',
    'DataStore object',
] as const;

const PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES = [
    'datawindow',
    'datastore',
] as const;

const PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO = [
    'DataWindow control',
    'DataStore object',
] as const;

const PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_OWNER_TYPES = ['datawindow'] as const;
const PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_APPLIES_TO = ['DataWindow control'] as const;

function defineDataWindowFunctionEntries(
    descriptors: readonly DataWindowFunctionDescriptor[],
): readonly PbSystemSymbolEntry[] {
    return descriptors.map(descriptor => dataWindowFunction({
        name: descriptor.name,
        category: descriptor.category,
        summary: descriptor.summary,
        signatures: [{ label: descriptor.signature }],
        appliesTo: descriptor.appliesTo,
        ownerTypes: descriptor.ownerTypes,
        sourceUrl: `https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_${descriptor.name}.html`,
    }));
}

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07A = defineDataWindowFunctionEntries([
    {
        name: 'Collapse',
        category: 'Navegación',
        summary: 'Contrae un grupo TreeView concreto dentro del DataWindow.',
        signature: 'Collapse(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'CollapseAll',
        category: 'Navegación',
        summary: 'Contrae todos los grupos TreeView del DataWindow.',
        signature: 'CollapseAll()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'CollapseAllChildren',
        category: 'Navegación',
        summary: 'Contrae todos los descendientes del grupo TreeView indicado.',
        signature: 'CollapseAllChildren(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'CollapseLevel',
        category: 'Navegación',
        summary: 'Contrae todos los grupos TreeView del nivel indicado.',
        signature: 'CollapseLevel(level)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'Create',
        category: 'Metadatos',
        summary: 'Crea en runtime un DataWindow a partir de una definición dinámica.',
        signature: 'Create(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'CreateFrom',
        category: 'Metadatos',
        summary: 'Crea un DataWindow dinámico a partir de otro origen compatible.',
        signature: 'CreateFrom(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'CrosstabDialog',
        category: 'Visual',
        summary: 'Abre el diálogo interactivo de Crosstab para el control DataWindow.',
        signature: 'CrosstabDialog()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'Drag',
        category: 'Visual',
        summary: 'Inicia o termina el arrastre del control DataWindow.',
        signature: 'Drag(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'ExpandAllChildren',
        category: 'Navegación',
        summary: 'Expande todos los descendientes del grupo TreeView indicado.',
        signature: 'ExpandAllChildren(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'ExpandLevel',
        category: 'Navegación',
        summary: 'Expande todos los grupos TreeView del nivel indicado.',
        signature: 'ExpandLevel(level)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07B = defineDataWindowFunctionEntries([
    {
        name: 'FindGroupChange',
        category: 'Datos',
        summary: 'Busca el siguiente cambio de grupo dentro del DataWindow.',
        signature: 'FindGroupChange(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'FindRequired',
        category: 'Datos',
        summary: 'Busca la siguiente fila con datos obligatorios pendientes.',
        signature: 'FindRequired(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'GetItemFormattedString',
        category: 'Datos',
        summary: 'Recupera el valor formateado de una columna como cadena.',
        signature: 'GetItemFormattedString(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'GetItemStatus',
        category: 'Datos',
        summary: 'Devuelve el estado de una fila o de una columna dentro de una fila.',
        signature: 'GetItemStatus(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'GetItemUnformattedString',
        category: 'Datos',
        summary: 'Recupera el valor sin formato de una columna como cadena.',
        signature: 'GetItemUnformattedString(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'IsExpanded',
        category: 'Navegación',
        summary: 'Indica si el grupo TreeView indicado está expandido.',
        signature: 'IsExpanded(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'IsSelected',
        category: 'Navegación',
        summary: 'Indica si la fila indicada está seleccionada en el DataWindow.',
        signature: 'IsSelected(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
    },
    {
        name: 'PostEvent',
        category: 'Contexto',
        summary: 'Publica un evento asíncrono sobre el DataWindow o DataStore.',
        signature: 'PostEvent(eventname, wordparm?, longparm?)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SetCultureFormat',
        category: 'Metadatos',
        summary: 'Ajusta el formato cultural usado para presentar y parsear datos.',
        signature: 'SetCultureFormat(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'TriggerEvent',
        category: 'Contexto',
        summary: 'Dispara inmediatamente un evento sobre el DataWindow o DataStore.',
        signature: 'TriggerEvent(eventname, wordparm?, longparm?)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07C = defineDataWindowFunctionEntries([
    {
        name: 'CopyRTF',
        category: 'Texto',
        summary: 'Copia contenido RichText del control DataWindow al portapapeles.',
        signature: 'CopyRTF()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'GetRichTextAlign',
        category: 'Texto',
        summary: 'Devuelve la alineación activa en el control RichText del DataWindow.',
        signature: 'GetRichTextAlign()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'GetRichTextColor',
        category: 'Texto',
        summary: 'Devuelve el color activo del texto en el control RichText.',
        signature: 'GetRichTextColor()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'GetRichTextFaceName',
        category: 'Texto',
        summary: 'Devuelve la fuente activa del texto en el control RichText.',
        signature: 'GetRichTextFaceName()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'GetRichTextSize',
        category: 'Texto',
        summary: 'Devuelve el tamaño activo del texto en el control RichText.',
        signature: 'GetRichTextSize()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'GetRichTextStyle',
        category: 'Texto',
        summary: 'Devuelve el estilo activo del texto en el control RichText.',
        signature: 'GetRichTextStyle()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'InsertDocument',
        category: 'Texto',
        summary: 'Inserta un documento RichText dentro del control DataWindow.',
        signature: 'InsertDocument(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'LineCount',
        category: 'Texto',
        summary: 'Devuelve el número de líneas del contenido RichText actual.',
        signature: 'LineCount()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'OLEActivate',
        category: 'Visual',
        summary: 'Activa el objeto OLE incrustado en el control DataWindow.',
        signature: 'OLEActivate(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'PasteRTF',
        category: 'Texto',
        summary: 'Pega contenido RichText en el control DataWindow.',
        signature: 'PasteRTF()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07D = defineDataWindowFunctionEntries([
    {
        name: 'ResetInk',
        category: 'Visual',
        summary: 'Limpia la capa de tinta digital asociada al control DataWindow.',
        signature: 'ResetInk()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SaveAsAscii',
        category: 'Datos',
        summary: 'Guarda el contenido del DataWindow como texto ASCII.',
        signature: 'SaveAsAscii(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SaveAsFormattedText',
        category: 'Datos',
        summary: 'Guarda el contenido formateado del DataWindow como texto.',
        signature: 'SaveAsFormattedText(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SaveDisplayedDataAs',
        category: 'Datos',
        summary: 'Guarda exactamente los datos mostrados por el DataWindow.',
        signature: 'SaveDisplayedDataAs(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SaveInk',
        category: 'Visual',
        summary: 'Guarda la capa de tinta digital del control DataWindow.',
        signature: 'SaveInk(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SaveInkPic',
        category: 'Visual',
        summary: 'Guarda la capa de tinta como imagen.',
        signature: 'SaveInkPic(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SetFullState',
        category: 'Transacciones',
        summary: 'Aplica un blob con el estado completo del DataWindow o DataStore.',
        signature: 'SetFullState(data)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SetRichTextAlign',
        category: 'Texto',
        summary: 'Cambia la alineación del texto en el control RichText.',
        signature: 'SetRichTextAlign(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SetRichTextColor',
        category: 'Texto',
        summary: 'Cambia el color del texto en el control RichText.',
        signature: 'SetRichTextColor(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SetRichTextFaceName',
        category: 'Texto',
        summary: 'Cambia la fuente activa en el control RichText.',
        signature: 'SetRichTextFaceName(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07E = defineDataWindowFunctionEntries([
    {
        name: 'SetRichTextSize',
        category: 'Texto',
        summary: 'Cambia el tamaño del texto en el control RichText.',
        signature: 'SetRichTextSize(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SetRichTextStyle',
        category: 'Texto',
        summary: 'Cambia el estilo del texto en el control RichText.',
        signature: 'SetRichTextStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'SetSQLPreview',
        category: 'Metadatos',
        summary: 'Activa o configura el modo de vista previa SQL del DataWindow.',
        signature: 'SetSQLPreview(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
    },
    {
        name: 'SetText',
        category: 'Texto',
        summary: 'Sustituye el texto del edit control activo del DataWindow.',
        signature: 'SetText(text)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'ShowHeadFoot',
        category: 'Visual',
        summary: 'Muestra u oculta cabeceras y pies en el control DataWindow.',
        signature: 'ShowHeadFoot(show)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
    },
    {
        name: 'CategoryCount',
        category: 'Metadatos',
        summary: 'Devuelve cuántas categorías tiene la gráfica del DataWindow.',
        signature: 'CategoryCount()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'CategoryName',
        category: 'Metadatos',
        summary: 'Devuelve el nombre de una categoría de la gráfica.',
        signature: 'CategoryName(index)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'Clipboard',
        category: 'Visual',
        summary: 'Copia la gráfica actual al portapapeles.',
        signature: 'Clipboard()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'DataCount',
        category: 'Metadatos',
        summary: 'Devuelve cuántos puntos de datos expone la gráfica.',
        signature: 'DataCount()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07F = defineDataWindowFunctionEntries([
    {
        name: 'FindCategory',
        category: 'Contexto',
        summary: 'Busca una categoría concreta dentro de la gráfica.',
        signature: 'FindCategory(name)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'FindSeries',
        category: 'Contexto',
        summary: 'Busca una serie concreta dentro de la gráfica.',
        signature: 'FindSeries(name)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetData',
        category: 'Datos',
        summary: 'Recupera el valor de un punto de datos de la gráfica.',
        signature: 'GetData(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataDateVariable',
        category: 'Datos',
        summary: 'Recupera la variable de fecha asociada a un punto de datos.',
        signature: 'GetDataDateVariable(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataLabelling',
        category: 'Visual',
        summary: 'Devuelve la configuración de etiquetado de un punto de datos.',
        signature: 'GetDataLabelling(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataNumberVariable',
        category: 'Datos',
        summary: 'Recupera la variable numérica asociada a un punto de datos.',
        signature: 'GetDataNumberVariable(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataPieExplode',
        category: 'Visual',
        summary: 'Devuelve el valor explode configurado para un punto de un gráfico circular.',
        signature: 'GetDataPieExplode(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataPieExplodePercentage',
        category: 'Visual',
        summary: 'Devuelve el porcentaje explode configurado para un punto circular.',
        signature: 'GetDataPieExplodePercentage(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStringVariable',
        category: 'Datos',
        summary: 'Recupera la variable string asociada a un punto de datos.',
        signature: 'GetDataStringVariable(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStyle',
        category: 'Visual',
        summary: 'Devuelve la configuración de estilo de un punto de datos.',
        signature: 'GetDataStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07G = defineDataWindowFunctionEntries([
    {
        name: 'GetDataStyleColorValue',
        category: 'Visual',
        summary: 'Devuelve el color configurado para un punto de datos.',
        signature: 'GetDataStyleColorValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStyleFillPattern',
        category: 'Visual',
        summary: 'Devuelve el patrón de relleno configurado para un punto de datos.',
        signature: 'GetDataStyleFillPattern(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStyleLineStyle',
        category: 'Visual',
        summary: 'Devuelve el estilo de línea configurado para un punto de datos.',
        signature: 'GetDataStyleLineStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStyleLineWidth',
        category: 'Visual',
        summary: 'Devuelve el ancho de línea configurado para un punto de datos.',
        signature: 'GetDataStyleLineWidth(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataStyleSymbolValue',
        category: 'Visual',
        summary: 'Devuelve el símbolo configurado para un punto de datos.',
        signature: 'GetDataStyleSymbolValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataTransparency',
        category: 'Visual',
        summary: 'Devuelve la transparencia configurada para un punto de datos.',
        signature: 'GetDataTransparency(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetDataValue',
        category: 'Datos',
        summary: 'Recupera el valor numérico mostrado por un punto de datos.',
        signature: 'GetDataValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesLabelling',
        category: 'Visual',
        summary: 'Devuelve la configuración de etiquetado de una serie.',
        signature: 'GetSeriesLabelling(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyle',
        category: 'Visual',
        summary: 'Devuelve la configuración de estilo de una serie.',
        signature: 'GetSeriesStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyleColorValue',
        category: 'Visual',
        summary: 'Devuelve el color configurado para una serie.',
        signature: 'GetSeriesStyleColorValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07H = defineDataWindowFunctionEntries([
    {
        name: 'GetSeriesStyleFillPattern',
        category: 'Visual',
        summary: 'Devuelve el patrón de relleno configurado para una serie.',
        signature: 'GetSeriesStyleFillPattern(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyleLineStyle',
        category: 'Visual',
        summary: 'Devuelve el estilo de línea configurado para una serie.',
        signature: 'GetSeriesStyleLineStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyleLineWidth',
        category: 'Visual',
        summary: 'Devuelve el ancho de línea configurado para una serie.',
        signature: 'GetSeriesStyleLineWidth(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyleOverlayValue',
        category: 'Visual',
        summary: 'Devuelve el valor overlay configurado para una serie.',
        signature: 'GetSeriesStyleOverlayValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesStyleSymbolValue',
        category: 'Visual',
        summary: 'Devuelve el símbolo configurado para una serie.',
        signature: 'GetSeriesStyleSymbolValue(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'GetSeriesTransparency',
        category: 'Visual',
        summary: 'Devuelve la transparencia configurada para una serie.',
        signature: 'GetSeriesTransparency(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SeriesCount',
        category: 'Metadatos',
        summary: 'Devuelve cuántas series expone la gráfica.',
        signature: 'SeriesCount()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SeriesName',
        category: 'Metadatos',
        summary: 'Devuelve el nombre de una serie de la gráfica.',
        signature: 'SeriesName(index)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetDataLabelling',
        category: 'Visual',
        summary: 'Configura el etiquetado visible de un punto de datos.',
        signature: 'SetDataLabelling(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetDataPieExplode',
        category: 'Visual',
        summary: 'Configura el explode de un punto en un gráfico circular.',
        signature: 'SetDataPieExplode(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
]);

const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07I = defineDataWindowFunctionEntries([
    {
        name: 'SetDataStyle',
        category: 'Visual',
        summary: 'Configura el estilo visible de un punto de datos.',
        signature: 'SetDataStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetDataTransparency',
        category: 'Visual',
        summary: 'Configura la transparencia visible de un punto de datos.',
        signature: 'SetDataTransparency(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetSeriesLabelling',
        category: 'Visual',
        summary: 'Configura el etiquetado visible de una serie.',
        signature: 'SetSeriesLabelling(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetSeriesStyle',
        category: 'Visual',
        summary: 'Configura el estilo visible de una serie.',
        signature: 'SetSeriesStyle(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'SetSeriesTransparency',
        category: 'Visual',
        summary: 'Configura la transparencia visible de una serie.',
        signature: 'SetSeriesTransparency(...)',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
    {
        name: 'ObjectAtPointer',
        category: 'Contexto',
        summary: 'Devuelve el objeto gráfico situado bajo el puntero.',
        signature: 'ObjectAtPointer()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_OWNER_TYPES,
    },
    {
        name: 'ObjectAtPointerDataPoint',
        category: 'Contexto',
        summary: 'Devuelve el punto de datos gráfico situado bajo el puntero.',
        signature: 'ObjectAtPointerDataPoint()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_OWNER_TYPES,
    },
    {
        name: 'ObjectAtPointerSeries',
        category: 'Contexto',
        summary: 'Devuelve la serie gráfica situada bajo el puntero.',
        signature: 'ObjectAtPointerSeries()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_CONTROL_OWNER_TYPES,
    },
    {
        name: 'ResetDataColors',
        category: 'Visual',
        summary: 'Restaura los colores automáticos de la gráfica del DataWindow.',
        signature: 'ResetDataColors()',
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_GRAPH_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_GRAPH_OWNER_TYPES,
    },
]);

export const PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS: readonly PbSystemSymbolEntry[] = [
    dataWindowFunction({
        name: 'AcceptText',
        category: 'Datos',
        summary: 'Acepta el contenido del edit control activo y lo aplica al buffer del DataWindow.',
        signatures: [{ label: 'AcceptText()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_AcceptText.html',
    }),
    dataWindowFunction({
        name: 'Describe',
        category: 'Metadatos',
        summary: 'Lee propiedades del DataWindow y puede evaluar expresiones painter cuando la property list es literal y defendible.',
        signatures: [{
            label: 'Describe(propertylist)',
            documentation: 'Reporta propiedades del DataWindow y de sus controles internos; tambien admite Evaluate(...) dentro de una property list literal.',
            parameters: [{
                label: 'propertylist',
                documentation: 'Lista separada por espacios de propiedades o expresiones Evaluate(...) a consultar.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Describe.html',
        risk: 'dynamic',
    }),
    dataWindowFunction({
        name: 'GetItemString',
        category: 'Datos',
        summary: 'Obtiene datos de tipo string desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemString(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemString.html',
    }),
    dataWindowFunction({
        name: 'GetItemDate',
        category: 'Datos',
        summary: 'Obtiene datos de tipo date desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemDate(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemDate.html',
    }),
    dataWindowFunction({
        name: 'GetItemDateTime',
        category: 'Datos',
        summary: 'Obtiene datos de tipo DateTime desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemDateTime(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemDateTime.html',
    }),
    dataWindowFunction({
        name: 'GetItemDecimal',
        category: 'Datos',
        summary: 'Obtiene datos de tipo decimal desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemDecimal(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemDecimal.html',
    }),
    dataWindowFunction({
        name: 'GetRow',
        category: 'Datos',
        summary: 'Devuelve el número de la fila actual del DataWindow, DataWindowChild o DataStore.',
        signatures: [{ label: 'GetRow()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetRow.html',
    }),
    dataWindowFunction({
        name: 'Modify',
        category: 'Metadatos',
        summary: 'Aplica un modstring para cambiar propiedades, controles o metadata SQL del objeto DataWindow en runtime.',
        signatures: [{
            label: 'Modify(modstring)',
            documentation: 'Modifica apariencia, comportamiento, controles o SQL del DataWindow con instrucciones string; los modstring dinamicos reducen la confianza semantica.',
            parameters: [{
                label: 'modstring',
                documentation: 'Cadena de instrucciones Modify, por ejemplo control.prop=value, create ... o destroy ....'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Modify.html',
        risk: 'dynamic',
    }),
    dataWindowFunction({
        name: 'DeleteRow',
        category: 'Datos',
        summary: 'Elimina la fila indicada del buffer primario o la marca para borrado según el objeto sea actualizable.',
        signatures: [{ label: 'DeleteRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_DeleteRow.html',
    }),
    dataWindowFunction({
        name: 'InsertRow',
        category: 'Datos',
        summary: 'Inserta una fila inicializada antes de la fila indicada o al final si se usa 0.',
        signatures: [{ label: 'InsertRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_InsertRow.html',
    }),
    dataWindowFunction({
        name: 'Find',
        category: 'Datos',
        summary: 'Busca la siguiente fila cuyo contenido cumpla una expresión booleana sobre columnas.',
        signatures: [{ label: 'Find(expression, start, end, buffer?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Find.html',
    }),
    dataWindowFunction({
        name: 'Filter',
        category: 'Datos',
        summary: 'Aplica al DataWindow los criterios de filtrado actualmente definidos.',
        signatures: [{ label: 'Filter()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Filter.html',
    }),
    dataWindowFunction({
        name: 'SetFilter',
        category: 'Datos',
        summary: 'Define la expresión de filtrado que luego se aplicará con Filter.',
        signatures: [{ label: 'SetFilter(format)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetFilter.html',
    }),
    dataWindowFunction({
        name: 'SetRow',
        category: 'Navegación',
        summary: 'Cambia programáticamente la fila actual del DataWindow, DataWindowChild o DataStore.',
        signatures: [{ label: 'SetRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetRow.html',
    }),
    dataWindowFunction({
        name: 'SetSort',
        category: 'Datos',
        summary: 'Define los criterios de ordenación activos para el DataWindow.',
        signatures: [{ label: 'SetSort(format)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetSort.html',
    }),
    dataWindowFunction({
        name: 'Sort',
        category: 'Datos',
        summary: 'Ordena las filas usando los criterios configurados en el DataWindow.',
        signatures: [{ label: 'Sort()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Sort.html',
    }),
    dataWindowFunction({
        name: 'GroupCalc',
        category: 'Datos',
        summary: 'Recalcula los saltos y agrupaciones del DataWindow tras cambios en los datos.',
        signatures: [{ label: 'GroupCalc()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GroupCalc.html',
    }),
    dataWindowFunction({
        name: 'RowsMove',
        category: 'Datos',
        summary: 'Mueve un rango de filas entre buffers o entre DataWindows compatibles.',
        signatures: [{ label: 'RowsMove(startrow, endrow, movebuffer, targetdw, beforerow, targetbuffer)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_RowsMove.html',
    }),
    dataWindowFunction({
        name: 'ScrollToRow',
        category: 'Navegación',
        summary: 'Hace visible una fila concreta y la convierte en la fila actual.',
        signatures: [{ label: 'ScrollToRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_SCROLL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_SCROLL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ScrollToRow.html',
    }),
    dataWindowFunction({
        name: 'Reset',
        category: 'Datos',
        summary: 'Limpia todos los datos actuales del DataWindow sin afectar a la base de datos.',
        signatures: [{ label: 'Reset()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Reset.html',
    }),
    dataWindowFunction({
        name: 'Retrieve',
        category: 'Datos',
        summary: 'Recupera filas desde la fuente de datos usando los retrieve arguments definidos y un transaction binding valido.',
        signatures: [{
            label: 'Retrieve(argument...)',
            documentation: 'Recupera filas del DataWindow, DataStore o DataWindowChild; si faltan argumentos, PowerBuilder puede solicitarlos en runtime.',
            parameters: [{
                label: 'argument...',
                documentation: 'Uno o mas valores para los retrieve arguments declarados por el DataWindow.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Retrieve.html',
        risk: 'dynamic',
    }),
    dataWindowFunction({
        name: 'RowCount',
        category: 'Datos',
        summary: 'Devuelve el número de filas disponibles actualmente en el buffer primario.',
        signatures: [{ label: 'RowCount()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_RowCount.html',
    }),
    dataWindowFunction({
        name: 'SetItem',
        category: 'Datos',
        summary: 'Asigna un valor a una fila y columna concretas del DataWindow.',
        signatures: [{ label: 'SetItem(row, column, value)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetItem.html',
    }),
    dataWindowFunction({
        name: 'SetItemStatus',
        category: 'Datos',
        summary: 'Cambia el estado de modificación de una fila o de una columna dentro de una fila.',
        signatures: [{ label: 'SetItemStatus(row, column, dwbuffer, status)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetItemStatus.html',
    }),
    dataWindowFunction({
        name: 'SetTransObject',
        category: 'Transacciones',
        summary: 'Asocia un transaction object explicito para que el caller controle CONNECT, COMMIT y ROLLBACK.',
        signatures: [{
            label: 'SetTransObject(transaction)',
            documentation: 'Vincula un transaction object programado al DataWindow, DataStore o DataWindowChild y requiere gestion transaccional explicita.',
            parameters: [{
                label: 'transaction',
                documentation: 'Transaction object que se reutilizara para Retrieve y Update.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetTransObject.html',
        risk: 'safe',
    }),
    dataWindowFunction({
        name: 'Update',
        category: 'Transacciones',
        summary: 'Envia a la base de datos los cambios acumulados en el DataWindow y depende del transaction binding activo.',
        signatures: [{
            label: 'Update(accept?, resetflag?)',
            documentation: 'Actualiza la base de datos; accept controla AcceptText y resetflag decide si las marcas de update se conservan o limpian.',
            parameters: [{
                label: 'accept?',
                documentation: 'True (por defecto) ejecuta AcceptText antes del update; False evita ese paso.'
            }, {
                label: 'resetflag?',
                documentation: 'True (por defecto) limpia las marcas de update; False las conserva para commit/rollback manual o updates encadenados.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Update.html',
        risk: 'dynamic',
    }),
    dataWindowFunction({
        name: 'Show',
        category: 'Visual',
        summary: 'Hace visible el control DataWindow.',
        signatures: [{ label: 'Show()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Show.html',
    }),
    dataWindowFunction({
        name: 'Hide',
        category: 'Visual',
        summary: 'Oculta el control DataWindow.',
        signatures: [{ label: 'Hide()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Hide.html',
    }),
    dataWindowFunction({
        name: 'Move',
        category: 'Layout',
        summary: 'Reubica el control DataWindow dentro de su contenedor.',
        signatures: [{ label: 'Move(x, y)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Move.html',
    }),
    dataWindowFunction({
        name: 'Resize',
        category: 'Layout',
        summary: 'Cambia el tamaño del control DataWindow.',
        signatures: [{ label: 'Resize(width, height)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Resize.html',
    }),
    dataWindowFunction({
        name: 'SetRedraw',
        category: 'Visual',
        summary: 'Suspende o reactiva temporalmente el repintado del control DataWindow.',
        signatures: [{ label: 'SetRedraw(redraw)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetRedraw.html',
    }),
    dataWindowFunction({
        name: 'GetItemNumber',
        category: 'Datos',
        summary: 'Obtiene datos numéricos desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemNumber(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemNumber.html',
    }),
    dataWindowFunction({
        name: 'GetItemTime',
        category: 'Datos',
        summary: 'Obtiene datos de tipo time desde uno de los buffers del DataWindow.',
        signatures: [{ label: 'GetItemTime(row, column, dwbuffer?, originalvalue?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetItemTime.html',
    }),
    dataWindowFunction({
        name: 'GetNextModified',
        category: 'Datos',
        summary: 'Devuelve la siguiente fila modificada a partir de una fila inicial en el buffer indicado.',
        signatures: [{ label: 'GetNextModified(dwbuffer, startrow)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetNextModified.html',
    }),
    dataWindowFunction({
        name: 'GetRowFromRowId',
        category: 'Navegación',
        summary: 'Obtiene el número de fila asociado a un row id único.',
        signatures: [{ label: 'GetRowFromRowId(rowid)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetRowFromRowId.html',
    }),
    dataWindowFunction({
        name: 'GetRowIdFromRow',
        category: 'Navegación',
        summary: 'Obtiene el row id único asociado a una fila del DataWindow.',
        signatures: [{ label: 'GetRowIdFromRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetRowIdFromRow.html',
    }),
    dataWindowFunction({
        name: 'GetSelectedRow',
        category: 'Navegación',
        summary: 'Devuelve la primera fila seleccionada a partir de la fila indicada.',
        signatures: [{ label: 'GetSelectedRow(startrow)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetSelectedRow.html',
    }),
    dataWindowFunction({
        name: 'GetSQLSelect',
        category: 'Metadatos',
        summary: 'Devuelve el SELECT actualmente asociado al DataWindow.',
        signatures: [{ label: 'GetSQLSelect()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetSQLSelect.html',
    }),
    dataWindowFunction({
        name: 'GetText',
        category: 'Texto',
        summary: 'Devuelve el texto actual del edit control activo del DataWindow.',
        signatures: [{ label: 'GetText()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetText.html',
    }),
    dataWindowFunction({
        name: 'GetValidate',
        category: 'Metadatos',
        summary: 'Devuelve la regla de validación configurada para una columna.',
        signatures: [{ label: 'GetValidate(column)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetValidate.html',
    }),
    dataWindowFunction({
        name: 'GetValue',
        category: 'Metadatos',
        summary: 'Devuelve un ítem concreto de la value list o code table de una columna.',
        signatures: [{ label: 'GetValue(column, item)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetValue.html',
    }),
    dataWindowFunction({
        name: 'ClearValues',
        category: 'Metadatos',
        summary: 'Elimina todos los ítems de la value list o code table asociada a una columna.',
        signatures: [{ label: 'ClearValues(column)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ClearValues.html',
    }),
    dataWindowFunction({
        name: 'GetChild',
        category: 'Metadatos',
        summary: 'Obtiene una referencia al child DataWindow o a un reporte de un composite DataWindow.',
        signatures: [{
            label: 'GetChild(name, REF DataWindowChild dwchildvariable)',
            documentation: 'Devuelve una referencia utilizable para Retrieve, SetTransObject y otras operaciones sobre el child o reporte indicado.',
            parameters: [{
                label: 'name',
                documentation: 'Nombre de la columna DropDownDataWindow o del reporte dentro de un composite DataWindow.'
            }, {
                label: 'REF DataWindowChild dwchildvariable',
                documentation: 'Variable de salida donde se almacena la referencia al child DataWindow.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_AND_STORE_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetChild.html',
        risk: 'dynamic',
    }),
    dataWindowFunction({
        name: 'GetClickedColumn',
        category: 'Navegación',
        summary: 'Devuelve la columna sobre la que el usuario hizo click o doble click.',
        signatures: [{ label: 'GetClickedColumn()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetClickedColumn.html',
    }),
    dataWindowFunction({
        name: 'GetClickedRow',
        category: 'Navegación',
        summary: 'Devuelve la fila sobre la que el usuario hizo click o doble click.',
        signatures: [{ label: 'GetClickedRow()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetClickedRow.html',
    }),
    dataWindowFunction({
        name: 'GetColumn',
        category: 'Navegación',
        summary: 'Devuelve la columna actual del DataWindow.',
        signatures: [{ label: 'GetColumn()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetColumn.html',
    }),
    dataWindowFunction({
        name: 'GetColumnName',
        category: 'Metadatos',
        summary: 'Devuelve el nombre de la columna actual del DataWindow.',
        signatures: [{ label: 'GetColumnName()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetColumnName.html',
    }),
    dataWindowFunction({
        name: 'GetFormat',
        category: 'Metadatos',
        summary: 'Devuelve el formato de presentación configurado para una columna.',
        signatures: [{ label: 'GetFormat(column)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetFormat.html',
    }),
    dataWindowFunction({
        name: 'SetColumn',
        category: 'Navegación',
        summary: 'Convierte la columna indicada en la columna actual del DataWindow.',
        signatures: [{ label: 'SetColumn(column)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetColumn.html',
    }),
    dataWindowFunction({
        name: 'SetFormat',
        category: 'Metadatos',
        summary: 'Cambia en runtime el formato de presentación de una columna.',
        signatures: [{ label: 'SetFormat(column, format)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetFormat.html',
    }),
    dataWindowFunction({
        name: 'SetValue',
        category: 'Metadatos',
        summary: 'Cambia el valor de un ítem de la value list o code table de una columna.',
        signatures: [{ label: 'SetValue(column, item, value)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetValue.html',
    }),
    dataWindowFunction({
        name: 'DeletedCount',
        category: 'Datos',
        summary: 'Devuelve cuántas filas fueron marcadas como borradas y aún no se han actualizado.',
        signatures: [{ label: 'DeletedCount()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_DeletedCount.html',
    }),
    dataWindowFunction({
        name: 'FilteredCount',
        category: 'Datos',
        summary: 'Devuelve cuántas filas quedan ocultas por el filtro actual.',
        signatures: [{ label: 'FilteredCount()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_FilteredCount.html',
    }),
    dataWindowFunction({
        name: 'ModifiedCount',
        category: 'Datos',
        summary: 'Devuelve cuántas filas fueron modificadas y siguen pendientes de update.',
        signatures: [{ label: 'ModifiedCount()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ModifiedCount.html',
    }),
    dataWindowFunction({
        name: 'GetChanges',
        category: 'Transacciones',
        summary: 'Recupera en un blob los cambios pendientes del DataWindow.',
        signatures: [{ label: 'GetChanges()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetChanges.html',
    }),
    dataWindowFunction({
        name: 'GetFullState',
        category: 'Transacciones',
        summary: 'Recupera el estado completo del DataWindow en un blob serializable.',
        signatures: [{ label: 'GetFullState()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetFullState.html',
    }),
    dataWindowFunction({
        name: 'GetStateStatus',
        category: 'Transacciones',
        summary: 'Obtiene el estado interno de flags del DataWindow en un blob.',
        signatures: [{ label: 'GetStateStatus()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetStateStatus.html',
    }),
    dataWindowFunction({
        name: 'ResetUpdate',
        category: 'Transacciones',
        summary: 'Resetea las marcas de update pendientes en las filas del DataWindow.',
        signatures: [{ label: 'ResetUpdate()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ResetUpdate.html',
    }),
    dataWindowFunction({
        name: 'RowsCopy',
        category: 'Datos',
        summary: 'Copia un rango de filas entre buffers o entre DataWindows compatibles.',
        signatures: [{ label: 'RowsCopy(startrow, endrow, sourcebuffer, targetdw, beforerow, targetbuffer)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_RowsCopy.html',
    }),
    dataWindowFunction({
        name: 'RowsDiscard',
        category: 'Datos',
        summary: 'Descarta definitivamente un rango de filas sin posibilidad de undo.',
        signatures: [{ label: 'RowsDiscard(startrow, endrow, dwbuffer)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_RowsDiscard.html',
    }),
    dataWindowFunction({
        name: 'SetChanges',
        category: 'Transacciones',
        summary: 'Aplica sobre el DataWindow un blob de cambios capturado previamente.',
        signatures: [{ label: 'SetChanges(data)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetChanges.html',
    }),
    dataWindowFunction({
        name: 'DBCancel',
        category: 'Transacciones',
        summary: 'Cancela una recuperación de base de datos que sigue en curso.',
        signatures: [{ label: 'DBCancel()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_DBCancel.html',
    }),
    dataWindowFunction({
        name: 'GetTrans',
        category: 'Transacciones',
        summary: 'Recupera los valores del Transaction object interno del DataWindow.',
        signatures: [{ label: 'GetTrans(transaction)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetTrans.html',
    }),
    dataWindowFunction({
        name: 'ResetTransObject',
        category: 'Transacciones',
        summary: 'Desasocia un Transaction object explícito y vuelve al transaction interno.',
        signatures: [{ label: 'ResetTransObject()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ResetTransObject.html',
    }),
    dataWindowFunction({
        name: 'ReselectRow',
        category: 'Transacciones',
        summary: 'Reconsulta columnas actualizables y refresh de timestamps para una fila.',
        signatures: [{ label: 'ReselectRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ReselectRow.html',
    }),
    dataWindowFunction({
        name: 'SetSQLSelect',
        category: 'Metadatos',
        summary: 'Cambia en runtime el SELECT asociado al DataWindow.',
        signatures: [{ label: 'SetSQLSelect(sqlselect)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetSQLSelect.html',
    }),
    dataWindowFunction({
        name: 'SetTrans',
        category: 'Transacciones',
        summary: 'Copia valores al transaction object interno y deja que PowerBuilder conecte y desconecte automaticamente.',
        signatures: [{
            label: 'SetTrans(transaction)',
            documentation: 'Copia los parametros del transaction object especificado al transaction interno del DataWindow, DataStore o DataWindowChild.',
            parameters: [{
                label: 'transaction',
                documentation: 'Transaction object origen cuyos valores se copian al transaction interno.'
            }]
        }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetTrans.html',
        risk: 'safe',
    }),
    dataWindowFunction({
        name: 'ShareData',
        category: 'Datos',
        summary: 'Comparte el dataset entre un DataWindow primario y otro secundario.',
        signatures: [{ label: 'ShareData(primarydw)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ShareData.html',
    }),
    dataWindowFunction({
        name: 'ShareDataOff',
        category: 'Datos',
        summary: 'Interrumpe un enlace previo de ShareData.',
        signatures: [{ label: 'ShareDataOff()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ShareDataOff.html',
    }),
    dataWindowFunction({
        name: 'SaveAs',
        category: 'Datos',
        summary: 'Guarda el contenido del DataWindow en un fichero con el formato indicado.',
        signatures: [{ label: 'SaveAs(filename, saveastype, colheading?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SaveAs.html',
    }),
    dataWindowFunction({
        name: 'SaveNativePDFToBlob',
        category: 'Datos',
        summary: 'Guarda en un blob el PDF nativo generado desde el DataWindow.',
        signatures: [{ label: 'SaveNativePDFToBlob(blob)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SaveNativePDFToBlob.html',
    }),
    dataWindowFunction({
        name: 'ExportJson',
        category: 'Datos',
        summary: 'Exporta el contenido del DataWindow a una cadena JSON.',
        signatures: [{ label: 'ExportJson()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ExportJson.html',
    }),
    dataWindowFunction({
        name: 'ExportRowAsJson',
        category: 'Datos',
        summary: 'Exporta una fila concreta del DataWindow a una cadena JSON.',
        signatures: [{ label: 'ExportRowAsJson(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ExportRowAsJson.html',
    }),
    dataWindowFunction({
        name: 'ImportClipboard',
        category: 'Datos',
        summary: 'Importa filas o contenido desde el portapapeles al DataWindow.',
        signatures: [{ label: 'ImportClipboard()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportClipboard.html',
    }),
    dataWindowFunction({
        name: 'ImportFile',
        category: 'Datos',
        summary: 'Importa contenido desde un fichero externo al DataWindow.',
        signatures: [{ label: 'ImportFile(filename)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportFile.html',
    }),
    dataWindowFunction({
        name: 'ImportJson',
        category: 'Datos',
        summary: 'Inserta datos desde una cadena JSON en el DataWindow.',
        signatures: [{ label: 'ImportJson(json)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportJson.html',
    }),
    dataWindowFunction({
        name: 'ImportJsonByKey',
        category: 'Datos',
        summary: 'Inserta datos JSON mapeando explícitamente por nombre de clave.',
        signatures: [{ label: 'ImportJsonByKey(json)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportJsonByKey.html',
    }),
    dataWindowFunction({
        name: 'ImportRowFromJson',
        category: 'Datos',
        summary: 'Inserta una fila concreta desde una cadena JSON.',
        signatures: [{ label: 'ImportRowFromJson(json, row?)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportRowFromJson.html',
    }),
    dataWindowFunction({
        name: 'ImportString',
        category: 'Datos',
        summary: 'Importa contenido textual serializado directamente en el DataWindow.',
        signatures: [{ label: 'ImportString(data)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ImportString.html',
    }),
    dataWindowFunction({
        name: 'Print',
        category: 'Visual',
        summary: 'Envía el contenido del DataWindow a la impresora activa.',
        signatures: [{ label: 'Print()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Print.html',
    }),
    dataWindowFunction({
        name: 'PrintCancel',
        category: 'Visual',
        summary: 'Cancela el trabajo de impresión actual del DataWindow.',
        signatures: [{ label: 'PrintCancel()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_PrintCancel.html',
    }),
    dataWindowFunction({
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control u objeto DataWindow.',
        signatures: [{ label: 'ClassName()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ClassName.html',
    }),
    dataWindowFunction({
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una referencia a una instancia de servicio contextual para el DataWindow.',
        signatures: [{ label: 'GetContextService(...)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetContextService.html',
    }),
    dataWindowFunction({
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve una referencia al objeto padre del DataWindow.',
        signatures: [{ label: 'GetParent()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetParent.html',
    }),
    dataWindowFunction({
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del control u objeto DataWindow.',
        signatures: [{ label: 'TypeOf()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_TypeOf.html',
    }),
    dataWindowFunction({
        name: 'GetBorderStyle',
        category: 'Metadatos',
        summary: 'Devuelve el estilo de borde configurado para una columna.',
        signatures: [{ label: 'GetBorderStyle(column)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetBorderStyle.html',
    }),
    dataWindowFunction({
        name: 'SetBorderStyle',
        category: 'Metadatos',
        summary: 'Cambia el estilo de borde configurado para una columna.',
        signatures: [{ label: 'SetBorderStyle(column, borderstyle)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetBorderStyle.html',
    }),
    dataWindowFunction({
        name: 'SetDetailHeight',
        category: 'Layout',
        summary: 'Cambia la altura de las filas dentro de un rango determinado.',
        signatures: [{ label: 'SetDetailHeight(startrow, endrow, height)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetDetailHeight.html',
    }),
    dataWindowFunction({
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Reordena el control u objetos internos del DataWindow en el eje visual.',
        signatures: [{ label: 'SetPosition(...)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetPosition.html',
    }),
    dataWindowFunction({
        name: 'Expand',
        category: 'Navegación',
        summary: 'Expande un grupo TreeView concreto dentro del DataWindow.',
        signatures: [{ label: 'Expand(level, row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Expand.html',
    }),
    dataWindowFunction({
        name: 'ExpandAll',
        category: 'Navegación',
        summary: 'Expande todos los grupos TreeView del DataWindow.',
        signatures: [{ label: 'ExpandAll()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ExpandAll.html',
    }),
    dataWindowFunction({
        name: 'CanUndo',
        category: 'Texto',
        summary: 'Indica si el edit control actual del DataWindow puede deshacer la última edición.',
        signatures: [{ label: 'CanUndo()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_CanUndo.html',
    }),
    dataWindowFunction({
        name: 'Clear',
        category: 'Texto',
        summary: 'Borra el texto seleccionado en el edit control activo del DataWindow.',
        signatures: [{ label: 'Clear()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Clear.html',
    }),
    dataWindowFunction({
        name: 'Copy',
        category: 'Texto',
        summary: 'Copia al portapapeles el texto seleccionado del edit control activo.',
        signatures: [{ label: 'Copy()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Copy.html',
    }),
    dataWindowFunction({
        name: 'Cut',
        category: 'Texto',
        summary: 'Corta el texto seleccionado del edit control activo y lo envía al portapapeles.',
        signatures: [{ label: 'Cut()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Cut.html',
    }),
    dataWindowFunction({
        name: 'Paste',
        category: 'Texto',
        summary: 'Pega en el edit control activo el contenido actual del portapapeles.',
        signatures: [{ label: 'Paste()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Paste.html',
    }),
    dataWindowFunction({
        name: 'ReplaceText',
        category: 'Texto',
        summary: 'Reemplaza el texto seleccionado en el edit control activo.',
        signatures: [{ label: 'ReplaceText(text)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ReplaceText.html',
    }),
    dataWindowFunction({
        name: 'SelectText',
        category: 'Texto',
        summary: 'Selecciona un tramo de texto dentro del edit control activo del DataWindow.',
        signatures: [{ label: 'SelectText(start, length)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectText.html',
    }),
    dataWindowFunction({
        name: 'Undo',
        category: 'Texto',
        summary: 'Deshace la última edición realizada en el edit control activo del DataWindow.',
        signatures: [{ label: 'Undo()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Undo.html',
    }),
    dataWindowFunction({
        name: 'Position',
        category: 'Texto',
        summary: 'Devuelve la posición actual del cursor o de la selección en el edit control activo.',
        signatures: [{ label: 'Position()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Position.html',
    }),
    dataWindowFunction({
        name: 'Scroll',
        category: 'Texto',
        summary: 'Desplaza el edit control activo el número indicado de líneas.',
        signatures: [{ label: 'Scroll(lines)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_Scroll.html',
    }),
    dataWindowFunction({
        name: 'FindNext',
        category: 'Texto',
        summary: 'Busca la siguiente coincidencia de texto usando los criterios previos de Find en RichText.',
        signatures: [{ label: 'FindNext()' }],
        appliesTo: ['DataWindow control con presentación RichText'],
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_FindNext.html',
    }),
    dataWindowFunction({
        name: 'GetBandAtPointer',
        category: 'Contexto',
        summary: 'Devuelve la banda y fila ubicadas bajo el puntero en el DataWindow visual.',
        signatures: [{ label: 'GetBandAtPointer()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetBandAtPointer.html',
    }),
    dataWindowFunction({
        name: 'GetObjectAtPointer',
        category: 'Contexto',
        summary: 'Devuelve el objeto interno y la fila situados bajo el puntero.',
        signatures: [{ label: 'GetObjectAtPointer()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_GetObjectAtPointer.html',
    }),
    dataWindowFunction({
        name: 'PointerX',
        category: 'Contexto',
        summary: 'Devuelve la coordenada X del puntero respecto al control DataWindow.',
        signatures: [{ label: 'PointerX()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_PointerX.html',
    }),
    dataWindowFunction({
        name: 'PointerY',
        category: 'Contexto',
        summary: 'Devuelve la coordenada Y del puntero respecto al control DataWindow.',
        signatures: [{ label: 'PointerY()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_PointerY.html',
    }),
    dataWindowFunction({
        name: 'SelectedLength',
        category: 'Texto',
        summary: 'Devuelve la longitud del texto actualmente seleccionado en el edit control activo.',
        signatures: [{ label: 'SelectedLength()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectedLength.html',
    }),
    dataWindowFunction({
        name: 'SelectedLine',
        category: 'Texto',
        summary: 'Devuelve la línea actual del edit control activo del DataWindow.',
        signatures: [{ label: 'SelectedLine()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectedLine.html',
    }),
    dataWindowFunction({
        name: 'SelectedStart',
        category: 'Texto',
        summary: 'Devuelve la posición inicial del texto seleccionado en el edit control activo.',
        signatures: [{ label: 'SelectedStart()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectedStart.html',
    }),
    dataWindowFunction({
        name: 'SelectedText',
        category: 'Texto',
        summary: 'Devuelve el texto actualmente seleccionado en el edit control activo.',
        signatures: [{ label: 'SelectedText()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectedText.html',
    }),
    dataWindowFunction({
        name: 'TextLine',
        category: 'Texto',
        summary: 'Devuelve el texto completo de la línea actual del edit control activo.',
        signatures: [{ label: 'TextLine()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_TextLine.html',
    }),
    dataWindowFunction({
        name: 'ScrollNextPage',
        category: 'Navegación',
        summary: 'Desplaza el DataWindow visual una página hacia delante.',
        signatures: [{ label: 'ScrollNextPage()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ScrollNextPage.html',
    }),
    dataWindowFunction({
        name: 'ScrollNextRow',
        category: 'Navegación',
        summary: 'Desplaza el DataWindow visual a la fila siguiente.',
        signatures: [{ label: 'ScrollNextRow()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ScrollNextRow.html',
    }),
    dataWindowFunction({
        name: 'ScrollPriorPage',
        category: 'Navegación',
        summary: 'Desplaza el DataWindow visual una página hacia atrás.',
        signatures: [{ label: 'ScrollPriorPage()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ScrollPriorPage.html',
    }),
    dataWindowFunction({
        name: 'ScrollPriorRow',
        category: 'Navegación',
        summary: 'Desplaza el DataWindow visual a la fila anterior.',
        signatures: [{ label: 'ScrollPriorRow()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_ScrollPriorRow.html',
    }),
    dataWindowFunction({
        name: 'SetFocus',
        category: 'Visual',
        summary: 'Transfiere el foco al control DataWindow.',
        signatures: [{ label: 'SetFocus()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetFocus.html',
    }),
    dataWindowFunction({
        name: 'SetTabOrder',
        category: 'Layout',
        summary: 'Cambia el tab order de una columna en un DataWindow visual.',
        signatures: [{ label: 'SetTabOrder(column, taborder)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetTabOrder.html',
    }),
    dataWindowFunction({
        name: 'SetRowFocusIndicator',
        category: 'Navegación',
        summary: 'Configura el indicador visual de la fila actual en un DataWindow visual.',
        signatures: [{ label: 'SetRowFocusIndicator(indicator)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SetRowFocusIndicator.html',
    }),
    dataWindowFunction({
        name: 'SelectTextAll',
        category: 'Texto',
        summary: 'Selecciona todo el contenido de un DataWindow con presentación RichText.',
        signatures: [{ label: 'SelectTextAll()' }],
        appliesTo: ['DataWindow control con presentación RichText'],
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectTextAll.html',
    }),
    dataWindowFunction({
        name: 'SelectTextLine',
        category: 'Texto',
        summary: 'Selecciona la línea actual en un DataWindow con presentación RichText.',
        signatures: [{ label: 'SelectTextLine()' }],
        appliesTo: ['DataWindow control con presentación RichText'],
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectTextLine.html',
    }),
    dataWindowFunction({
        name: 'SelectTextWord',
        category: 'Texto',
        summary: 'Selecciona la palabra actual en un DataWindow con presentación RichText.',
        signatures: [{ label: 'SelectTextWord()' }],
        appliesTo: ['DataWindow control con presentación RichText'],
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwmeth_SelectTextWord.html',
    }),
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07A,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07B,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07C,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07D,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07E,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07F,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07G,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07H,
    ...PB_MANUAL_CORE_DATAWINDOW_FUNCTIONS_MF_07I,
];
