import { PbSystemSymbolEntry } from '../types';
import { systemObjectDatatype } from './common';

export const PB_MANUAL_CORE_SYSTEM_OBJECT_DATATYPE_CATEGORIES = [
    'Objetos visuales',
    'Objetos no visuales',
    'Objetos de sistema',
    'Reflexión',
    'OLE',
    'Errores',
] as const;

export const PB_MANUAL_CORE_SYSTEM_OBJECT_DATATYPES: readonly PbSystemSymbolEntry[] = [
    // — Objetos visuales —
    systemObjectDatatype({ name: 'Window', category: 'Objetos visuales', summary: 'Ventana de la interfaz de usuario.' }),
    systemObjectDatatype({ name: 'Application', category: 'Objetos visuales', summary: 'Objeto raíz de la aplicación PowerBuilder.' }),
    systemObjectDatatype({ name: 'DataWindow', category: 'Objetos visuales', summary: 'Control DataWindow visual.', lookupAliases: ['dw'] }),
    systemObjectDatatype({ name: 'Menu', category: 'Objetos visuales', summary: 'Menú de la interfaz de usuario.' }),
    systemObjectDatatype({ name: 'Animation', category: 'Objetos visuales', summary: 'Control visual para animaciones integradas.' }),
    systemObjectDatatype({ name: 'CheckBox', category: 'Objetos visuales', summary: 'Control visual de casilla de verificación.' }),
    systemObjectDatatype({ name: 'CommandButton', category: 'Objetos visuales', summary: 'Botón de comando visual.' }),
    systemObjectDatatype({ name: 'DatePicker', category: 'Objetos visuales', summary: 'Selector visual de fecha.' }),
    systemObjectDatatype({ name: 'DropDownListBox', category: 'Objetos visuales', summary: 'Lista desplegable visual.' }),
    systemObjectDatatype({ name: 'DropDownPictureListBox', category: 'Objetos visuales', summary: 'Lista desplegable visual con imágenes.' }),
    systemObjectDatatype({ name: 'EditMask', category: 'Objetos visuales', summary: 'Control de edición con máscara.' }),
    systemObjectDatatype({ name: 'Graph', category: 'Objetos visuales', summary: 'Control visual para gráficos y charts.' }),
    systemObjectDatatype({ name: 'GroupBox', category: 'Objetos visuales', summary: 'Contenedor visual para agrupar controles.' }),
    systemObjectDatatype({ name: 'HProgressBar', category: 'Objetos visuales', summary: 'Barra de progreso horizontal.' }),
    systemObjectDatatype({ name: 'HScrollBar', category: 'Objetos visuales', summary: 'Barra de desplazamiento horizontal.' }),
    systemObjectDatatype({ name: 'HTrackBar', category: 'Objetos visuales', summary: 'Trackbar horizontal visual.' }),
    systemObjectDatatype({ name: 'InkEdit', category: 'Objetos visuales', summary: 'Control de tinta y escritura manuscrita.' }),
    systemObjectDatatype({ name: 'InkPicture', category: 'Objetos visuales', summary: 'Control visual para imágenes de tinta.' }),
    systemObjectDatatype({ name: 'Line', category: 'Objetos visuales', summary: 'Objeto visual de línea.' }),
    systemObjectDatatype({ name: 'ListBox', category: 'Objetos visuales', summary: 'Lista visual de selección.' }),
    systemObjectDatatype({ name: 'ListView', category: 'Objetos visuales', summary: 'Control visual de lista detallada.' }),
    systemObjectDatatype({ name: 'ListViewItem', category: 'Objetos visuales', summary: 'Ítem de un control ListView.' }),
    systemObjectDatatype({ name: 'MultiLineEdit', category: 'Objetos visuales', summary: 'Control de edición multilínea.' }),
    systemObjectDatatype({ name: 'MonthCalendar', category: 'Objetos visuales', summary: 'Calendario mensual visual.' }),
    systemObjectDatatype({ name: 'Oval', category: 'Objetos visuales', summary: 'Objeto visual ovalado.' }),
    systemObjectDatatype({ name: 'Picture', category: 'Objetos visuales', summary: 'Control visual de imagen.' }),
    systemObjectDatatype({ name: 'PictureButton', category: 'Objetos visuales', summary: 'Botón visual con imagen.' }),
    systemObjectDatatype({ name: 'PictureHyperLink', category: 'Objetos visuales', summary: 'Hipervínculo visual basado en imagen.' }),
    systemObjectDatatype({ name: 'PictureListBox', category: 'Objetos visuales', summary: 'Lista visual con imágenes.' }),
    systemObjectDatatype({ name: 'PowerServerLabel', category: 'Objetos visuales', summary: 'Etiqueta visual especializada para PowerServer.' }),
    systemObjectDatatype({ name: 'RadioButton', category: 'Objetos visuales', summary: 'Control visual de opción única.' }),
    systemObjectDatatype({ name: 'Rectangle', category: 'Objetos visuales', summary: 'Objeto visual rectangular.' }),
    systemObjectDatatype({ name: 'RibbonBar', category: 'Objetos visuales', summary: 'Barra visual tipo ribbon.' }),
    systemObjectDatatype({ name: 'RichTextEdit', category: 'Objetos visuales', summary: 'Editor visual de texto enriquecido.' }),
    systemObjectDatatype({ name: 'RoundRectangle', category: 'Objetos visuales', summary: 'Objeto visual rectangular con esquinas redondeadas.' }),
    systemObjectDatatype({ name: 'SingleLineEdit', category: 'Objetos visuales', summary: 'Control de edición de una sola línea.' }),
    systemObjectDatatype({ name: 'StaticHyperLink', category: 'Objetos visuales', summary: 'Hipervínculo visual estático.' }),
    systemObjectDatatype({ name: 'StaticText', category: 'Objetos visuales', summary: 'Texto visual estático.' }),
    systemObjectDatatype({ name: 'Tab', category: 'Objetos visuales', summary: 'Control visual con pestañas.' }),
    systemObjectDatatype({ name: 'TreeView', category: 'Objetos visuales', summary: 'Control visual jerárquico.' }),
    systemObjectDatatype({ name: 'TreeViewItem', category: 'Objetos visuales', summary: 'Ítem de un control TreeView.' }),
    systemObjectDatatype({ name: 'UserObject', category: 'Objetos visuales', summary: 'Base de user objects visuales.' }),
    systemObjectDatatype({ name: 'VProgressBar', category: 'Objetos visuales', summary: 'Barra de progreso vertical.' }),
    systemObjectDatatype({ name: 'VScrollBar', category: 'Objetos visuales', summary: 'Barra de desplazamiento vertical.' }),
    systemObjectDatatype({ name: 'VTrackBar', category: 'Objetos visuales', summary: 'Trackbar vertical visual.' }),
    systemObjectDatatype({ name: 'WebBrowser', category: 'Objetos visuales', summary: 'Control visual de navegador embebido.' }),

    // — Objetos no visuales —
    systemObjectDatatype({ name: 'ADOResultSet', category: 'Objetos no visuales', summary: 'Result set no visual de ADO.' }),
    systemObjectDatatype({ name: 'NonVisualObject', category: 'Objetos no visuales', summary: 'Base de objetos no visuales personalizados.' }),
    systemObjectDatatype({ name: 'DataStore', category: 'Objetos no visuales', summary: 'DataWindow no visual (sin interfaz gráfica).' }),
    systemObjectDatatype({ name: 'Transaction', category: 'Objetos no visuales', summary: 'Objeto de transacción para conexiones de base de datos.' }),
    systemObjectDatatype({ name: 'CoderObject', category: 'Objetos no visuales', summary: 'Objeto no visual para codificación y transformaciones.' }),
    systemObjectDatatype({ name: 'CompressorObject', category: 'Objetos no visuales', summary: 'Objeto no visual para compresión de datos.' }),
    systemObjectDatatype({ name: 'Connection', category: 'Objetos no visuales', summary: 'Conexión no visual a servicios o fuentes externas.' }),
    systemObjectDatatype({ name: 'ContextInformation', category: 'Objetos no visuales', summary: 'Contexto no visual para metadata de sesión.' }),
    systemObjectDatatype({ name: 'ContextKeyword', category: 'Objetos no visuales', summary: 'Keyword de contexto no visual para metadatos runtime.' }),
    systemObjectDatatype({ name: 'CrypterObject', category: 'Objetos no visuales', summary: 'Objeto no visual para cifrado y descifrado.' }),
    systemObjectDatatype({ name: 'DotNetAssembly', category: 'Objetos no visuales', summary: 'Assembly .NET cargado desde PowerBuilder.' }),
    systemObjectDatatype({ name: 'DotNetObject', category: 'Objetos no visuales', summary: 'Objeto .NET interoperable desde PowerBuilder.' }),
    systemObjectDatatype({ name: 'ErrorLogging', category: 'Objetos no visuales', summary: 'Objeto no visual para logging de errores.' }),
    systemObjectDatatype({ name: 'Exception', category: 'Objetos no visuales', summary: 'Excepción runtime interoperable con try/catch.' }),
    systemObjectDatatype({ name: 'ExtractorObject', category: 'Objetos no visuales', summary: 'Objeto no visual para extracción de datos.' }),
    systemObjectDatatype({ name: 'HTTPClient', category: 'Objetos no visuales', summary: 'Cliente HTTP para requests REST y servicios web.' }),
    systemObjectDatatype({ name: 'INet', category: 'Objetos no visuales', summary: 'Objeto no visual para operaciones de Internet.' }),
    systemObjectDatatype({ name: 'InternetResult', category: 'Objetos no visuales', summary: 'Resultado no visual de operaciones HTTP/Internet.' }),
    systemObjectDatatype({ name: 'MailRecipient', category: 'Objetos no visuales', summary: 'Destinatario de correo no visual.' }),
    systemObjectDatatype({ name: 'MLSync', category: 'Objetos no visuales', summary: 'Objeto no visual para sincronización móvil.' }),
    systemObjectDatatype({ name: 'OAuthClient', category: 'Objetos no visuales', summary: 'Cliente OAuth para autenticación y autorización HTTP.' }),
    systemObjectDatatype({ name: 'OAuthRequest', category: 'Objetos no visuales', summary: 'Request OAuth no visual.' }),
    systemObjectDatatype({ name: 'Pipeline', category: 'Objetos no visuales', summary: 'Pipeline no visual para procesos ETL y data movement.' }),
    systemObjectDatatype({ name: 'ProfileCall', category: 'Objetos no visuales', summary: 'Traza no visual de llamada para profiling.' }),
    systemObjectDatatype({ name: 'ProfileClass', category: 'Objetos no visuales', summary: 'Clase perfilada dentro del subsistema de profiling.' }),
    systemObjectDatatype({ name: 'ProfileLine', category: 'Objetos no visuales', summary: 'Línea perfilada dentro del subsistema de profiling.' }),
    systemObjectDatatype({ name: 'ProfileRoutine', category: 'Objetos no visuales', summary: 'Rutina perfilada dentro del subsistema de profiling.' }),
    systemObjectDatatype({ name: 'Profiling', category: 'Objetos no visuales', summary: 'Objeto no visual para profiling runtime.' }),
    systemObjectDatatype({ name: 'JSONParser', category: 'Objetos no visuales', summary: 'Parser JSON no visual para leer y navegar payloads JSON.' }),
    systemObjectDatatype({ name: 'JSONGenerator', category: 'Objetos no visuales', summary: 'Generador JSON no visual para construir payloads serializados.' }),
    systemObjectDatatype({ name: 'JSONPackage', category: 'Objetos no visuales', summary: 'Contenedor JSON no visual para empaquetar y transportar estructuras JSON.' }),
    systemObjectDatatype({ name: 'OLETxnObject', category: 'Objetos no visuales', summary: 'Objeto transaccional OLE no visual.' }),
    systemObjectDatatype({ name: 'PDFDocument', category: 'Objetos no visuales', summary: 'Documento PDF no visual.' }),
    systemObjectDatatype({ name: 'PDFModel', category: 'Objetos no visuales', summary: 'Modelo no visual para contenido PDF.' }),
    systemObjectDatatype({ name: 'PDFObject', category: 'Objetos no visuales', summary: 'Objeto base no visual del subsistema PDF.' }),
    systemObjectDatatype({ name: 'PDFSecurity', category: 'Objetos no visuales', summary: 'Configuración de seguridad PDF no visual.' }),
    systemObjectDatatype({ name: 'RestClient', category: 'Objetos no visuales', summary: 'Cliente REST no visual.' }),
    systemObjectDatatype({ name: 'Service', category: 'Objetos no visuales', summary: 'Servicio no visual del runtime.' }),
    systemObjectDatatype({ name: 'SSLCallback', category: 'Objetos no visuales', summary: 'Callback SSL no visual.' }),
    systemObjectDatatype({ name: 'SSLServiceProvider', category: 'Objetos no visuales', summary: 'Proveedor SSL no visual.' }),
    systemObjectDatatype({ name: 'Timing', category: 'Objetos no visuales', summary: 'Utilidad no visual para medición temporal.' }),
    systemObjectDatatype({ name: 'TokenRequest', category: 'Objetos no visuales', summary: 'Request no visual de token/autenticación.' }),
    systemObjectDatatype({ name: 'TokenResponse', category: 'Objetos no visuales', summary: 'Response no visual de token/autenticación.' }),
    systemObjectDatatype({ name: 'TraceFile', category: 'Objetos no visuales', summary: 'Traza no visual persistida en archivo.' }),
    systemObjectDatatype({ name: 'TraceTree', category: 'Objetos no visuales', summary: 'Árbol no visual de trazas runtime.' }),
    systemObjectDatatype({ name: 'TransactionServer', category: 'Objetos no visuales', summary: 'Servidor transaccional no visual.' }),
    systemObjectDatatype({ name: 'ULSync', category: 'Objetos no visuales', summary: 'Objeto no visual para sincronización UltraLite.' }),
    systemObjectDatatype({ name: 'WSConnection', category: 'Objetos no visuales', summary: 'Conexión no visual a servicios web.' }),

    // — Objetos de sistema —
    systemObjectDatatype({ name: 'PowerObject', category: 'Objetos de sistema', summary: 'Raíz de la jerarquía de tipos PowerBuilder.' }),
    systemObjectDatatype({ name: 'GraphicObject', category: 'Objetos de sistema', summary: 'Base de objetos gráficos.' }),
    systemObjectDatatype({ name: 'DrawObject', category: 'Objetos de sistema', summary: 'Base de objetos de dibujo (línea, rectángulo, etc.).' }),
    systemObjectDatatype({ name: 'Structure', category: 'Objetos de sistema', summary: 'Tipo estructura (agrupación de campos).' }),
    systemObjectDatatype({ name: 'DataWindowChild', category: 'Objetos de sistema', summary: 'Referencia a un DataWindow hijo (DropDownDataWindow).' }),
    systemObjectDatatype({ name: 'DynamicDescriptionArea', category: 'Objetos de sistema', summary: 'Área de descripción para SQL dinámico.' }),
    systemObjectDatatype({ name: 'DynamicStagingArea', category: 'Objetos de sistema', summary: 'Área de staging para SQL dinámico.' }),
    systemObjectDatatype({ name: 'Environment', category: 'Objetos de sistema', summary: 'Información del entorno de ejecución.' }),
    systemObjectDatatype({ name: 'Message', category: 'Objetos de sistema', summary: 'Objeto global para paso de mensajes entre objetos.' }),
    systemObjectDatatype({ name: 'MailSession', category: 'Objetos de sistema', summary: 'Objeto para envío de correo MAPI.' }),

    // — Reflexión —
    systemObjectDatatype({ name: 'ClassDefinition', category: 'Reflexión', summary: 'Definición de clase para reflexión.' }),
    systemObjectDatatype({ name: 'EnumerationDefinition', category: 'Reflexión', summary: 'Definición de enumeración para reflexión.' }),
    systemObjectDatatype({ name: 'EnumerationItemDefinition', category: 'Reflexión', summary: 'Ítem de enumeración para reflexión.' }),
    systemObjectDatatype({ name: 'Function_Object', category: 'Reflexión', summary: 'Objeto de función para reflexión runtime.' }),
    systemObjectDatatype({ name: 'PBDOM_CharacterData', category: 'Reflexión', summary: 'Nodo DOM de datos de carácter.' }),
    systemObjectDatatype({ name: 'PBDOM_Object', category: 'Reflexión', summary: 'Objeto base del DOM XML en PowerBuilder.' }),
    systemObjectDatatype({ name: 'PBDOM_Text', category: 'Reflexión', summary: 'Nodo de texto del DOM XML en PowerBuilder.' }),
    systemObjectDatatype({ name: 'ScriptDefinition', category: 'Reflexión', summary: 'Definición de script para reflexión.' }),
    systemObjectDatatype({ name: 'VariableDefinition', category: 'Reflexión', summary: 'Definición de variable para reflexión.' }),
    systemObjectDatatype({ name: 'TypeDefinition', category: 'Reflexión', summary: 'Definición de tipo para reflexión.' }),
    systemObjectDatatype({ name: 'TypeObject', category: 'Reflexión', summary: 'Objeto de tipo para reflexión.' }),

    // — OLE —
    systemObjectDatatype({ name: 'OLEObject', category: 'OLE', summary: 'Objeto OLE Automation genérico.' }),
    systemObjectDatatype({ name: 'OLEControl', category: 'OLE', summary: 'Control OLE visual insertable.' }),
    systemObjectDatatype({ name: 'OLECustomControl', category: 'OLE', summary: 'Control OLE ActiveX personalizado.' }),
    systemObjectDatatype({ name: 'OLEStorage', category: 'OLE', summary: 'Almacenamiento OLE Structured Storage.' }),
    systemObjectDatatype({ name: 'OLEStream', category: 'OLE', summary: 'Flujo dentro de un OLE Storage.' }),

    // — Errores —
    systemObjectDatatype({ name: 'Throwable', category: 'Errores', summary: 'Base de excepciones (try/catch/throw).' }),
    systemObjectDatatype({ name: 'Error', category: 'Errores', summary: 'Objeto global de error del sistema.' }),
    systemObjectDatatype({ name: 'RuntimeError', category: 'Errores', summary: 'Error en tiempo de ejecución.' }),
];
