import { PbSystemSymbolEntry } from '../../types';
import { globalFunction } from '../common';

export const PB_MANUAL_CORE_GLOBAL_FUNCTION_CATEGORIES = [
    'UI',
    'Events',
    'Validation',
    'Strings',
    'Conversion',
    'Date and time',
    'Math',
    'Objects',
    'Errors',
    'Files',
    'Dialogs',
    'Configuration',
    'Project / IDE',
    'Web / HTTP',
    'System',
] as const;

export const PB_MANUAL_CORE_GLOBAL_FUNCTIONS: readonly PbSystemSymbolEntry[] = [
    globalFunction({
        name: 'MessageBox',
        category: 'UI',
        summary: 'Displays a message box and returns the button clicked.',
        signatures: [{
            label: 'MessageBox(title, text, icon, button, default)',
            parameters: [
                { label: 'title', documentation: 'Title of the message window.' },
                { label: 'text', documentation: 'Main text displayed to the user.' },
                { label: 'icon', documentation: 'Optional icon for the message box.' },
                { label: 'button', documentation: 'Optional set of buttons.' },
                { label: 'default', documentation: 'Optional default button.' },
            ],
        }],
        appliesTo: ['any PowerScript script'],
    }),
    globalFunction({
        name: 'Clipboard',
        category: 'UI',
        summary: 'Gets or sets the clipboard text.',
        signatures: [
            {
                label: 'Clipboard()',
                documentation: 'Returns the current textual content of the clipboard.',
            },
            {
                label: 'Clipboard(text)',
                documentation: 'Replaces the textual content of the clipboard.',
                parameters: [
                    { label: 'text', documentation: 'Text to be copied to the clipboard.' },
                ],
            },
        ],
        appliesTo: ['scripts with desktop interaction'],
    }),
    globalFunction({ name: 'Beep', category: 'UI', summary: 'Emits the specified number of beeps.', signatures: [{ label: 'Beep(count)' }] }),
    globalFunction({
        name: 'TriggerEvent',
        category: 'Events',
        summary: 'Triggers an event synchronously on an object.',
        signatures: [{
            label: 'TriggerEvent(target, eventName, argumentList?)',
            parameters: [
                { label: 'target', documentation: 'Object on which the event is executed.' },
                { label: 'eventName', documentation: 'Name of the event to trigger.' },
                { label: 'argumentList?', documentation: 'Optional list of event arguments.' },
            ],
        }],
        appliesTo: ['scripts that invoke PowerBuilder object events'],
    }),
    globalFunction({
        name: 'PostEvent',
        category: 'Events',
        summary: 'Enqueues an event to execute asynchronously.',
        signatures: [{
            label: 'PostEvent(target, eventName, argumentList?)',
            parameters: [
                { label: 'target', documentation: 'Object on which the event is enqueued.' },
                { label: 'eventName', documentation: 'Name of the event to post.' },
                { label: 'argumentList?', documentation: 'Optional list of event arguments.' },
            ],
        }],
        appliesTo: ['scripts that decouple event execution'],
    }),
    globalFunction({ name: 'IsNull', category: 'Validation', summary: 'Returns TRUE if the variable is NULL.', signatures: [{ label: 'IsNull(value)', parameters: [{ label: 'value' }] }] }),
    globalFunction({ name: 'IsValid', category: 'Validation', summary: 'Returns TRUE if the object variable references a valid object.', signatures: [{ label: 'IsValid(objectRef)' }] }),
    globalFunction({
        name: 'IsNumber',
        category: 'Validation',
        summary: 'Returns TRUE if a string represents a valid numeric value.',
        signatures: [{
            label: 'IsNumber(value)',
            parameters: [{ label: 'value', documentation: 'The string you want to test.' }],
        }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isNumber_func.html',
    }),
    globalFunction({ name: 'IsDate', category: 'Validation', summary: 'Returns TRUE if a string represents a valid date.', signatures: [{ label: 'IsDate(datevalue)', parameters: [{ label: 'datevalue', documentation: 'The string you want to test.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isDate_func.html' }),
    globalFunction({ name: 'IsTime', category: 'Validation', summary: 'Returns TRUE if a string represents a valid time.', signatures: [{ label: 'IsTime(timevalue)', parameters: [{ label: 'timevalue', documentation: 'The string you want to test.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isTime_func.html' }),
    globalFunction({ name: 'SetNull', category: 'Validation', summary: 'Assigns NULL to a variable.', signatures: [{ label: 'SetNull(anyvariable)', parameters: [{ label: 'anyvariable' }] }] }),
    globalFunction({ name: 'Trim', category: 'Strings', summary: 'Removes leading and trailing spaces.', signatures: [{ label: 'Trim(value)', parameters: [{ label: 'value', documentation: 'The string you want to trim.' }] }] }),
    globalFunction({
        name: 'TrimW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Trim.',
        signatures: [{ label: 'TrimW(value)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Trim',
    }),
    globalFunction({ name: 'LeftTrim', category: 'Strings', summary: 'Removes spaces from the beginning of a string.', signatures: [{ label: 'LeftTrim(string, removeallspaces?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/leftTrim_func.html' }),
    globalFunction({ name: 'RightTrim', category: 'Strings', summary: 'Removes spaces from the end of a string.', signatures: [{ label: 'RightTrim(string, removeallspaces?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightTrim_func.html' }),
    globalFunction({ name: 'Left', category: 'Strings', summary: 'Returns the leftmost characters.', signatures: [{ label: 'Left(value, count)' }] }),
    globalFunction({ name: 'Right', category: 'Strings', summary: 'Returns the rightmost characters.', signatures: [{ label: 'Right(value, count)' }] }),
    globalFunction({ name: 'Mid', category: 'Strings', summary: 'Returns characters from an intermediate position.', signatures: [{ label: 'Mid(value, start, length?)' }] }),
    globalFunction({ name: 'Len', category: 'Strings', summary: 'Returns the length of a string.', signatures: [{ label: 'Len(value)', parameters: [{ label: 'value' }] }] }),
    globalFunction({ name: 'Pos', category: 'Strings', summary: 'Returns the position of a fragment within a string.', signatures: [{ label: 'Pos(value, target, start?)' }] }),
    globalFunction({ name: 'LastPos', category: 'Strings', summary: 'Returns the last occurrence of a substring within another string.', signatures: [{ label: 'LastPos(string1, string2)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/lastPos_func.html' }),
    globalFunction({ name: 'Match', category: 'Strings', summary: 'Checks if a string matches a text pattern.', signatures: [{ label: 'Match(string, textpattern)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/match_func.html' }),
    globalFunction({ name: 'Upper', category: 'Strings', summary: 'Converts text to uppercase.', signatures: [{ label: 'Upper(value)', parameters: [{ label: 'value' }] }] }),
    globalFunction({ name: 'Lower', category: 'Strings', summary: 'Converts text to lowercase.', signatures: [{ label: 'Lower(value)', parameters: [{ label: 'value' }] }] }),
    globalFunction({ name: 'WordCap', category: 'Strings', summary: 'Capitalizes the first letter of each word and the rest to lowercase.', signatures: [{ label: 'WordCap(text)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/wordcap_func.html' }),
    globalFunction({ name: 'Replace', category: 'Strings', summary: 'Replaces characters starting from a given position.', signatures: [{ label: 'Replace(value, start, length, replacement)' }] }),
    globalFunction({ name: 'Space', category: 'Strings', summary: 'Returns a string composed of spaces.', signatures: [{ label: 'Space(count)' }] }),
    globalFunction({ name: 'Fill', category: 'Strings', summary: 'Builds a string of the specified length by repeating the given characters.', signatures: [{ label: 'Fill(chars, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fill_func.html' }),
    globalFunction({ name: 'Asc', category: 'Strings', summary: 'Returns the numeric value of the first character.', signatures: [{ label: 'Asc(value)' }] }),
    globalFunction({ name: 'Char', category: 'Strings', summary: 'Builds a character from its numeric code.', signatures: [{ label: 'Char(asciiCode)' }] }),
    globalFunction({ name: 'Length', category: 'Strings', summary: 'Returns the logical length of the specified value.', signatures: [{ label: 'Length(value)' }] }),
    globalFunction({ name: 'Reverse', category: 'Strings', summary: 'Reverses the order of characters in a string.', signatures: [{ label: 'Reverse(value)' }] }),
    globalFunction({
        name: 'String',
        category: 'Conversion',
        summary: 'Converts a value to its string representation.',
        signatures: [
            { label: 'String(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] },
            { label: 'String(value, format)', parameters: [
                { label: 'value', documentation: 'The value you want to convert.' },
                { label: 'format', documentation: 'The format mask (optional).' },
            ] },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/string_func.html',
    }),
    globalFunction({ name: 'Integer', category: 'Conversion', summary: 'Converts a value to integer.', signatures: [{ label: 'Integer(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/integer_func.html' }),
    globalFunction({ name: 'Long', category: 'Conversion', summary: 'Converts a value to long.', signatures: [{ label: 'Long(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/long_func.html' }),
    globalFunction({ name: 'Double', category: 'Conversion', summary: 'Converts a value to double.', signatures: [{ label: 'Double(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/double_func.html' }),
    globalFunction({ name: 'Dec', category: 'Conversion', summary: 'Converts a value to decimal.', signatures: [{ label: 'Dec(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dec_func.html' }),
    globalFunction({ name: 'Real', category: 'Conversion', summary: 'Converts a value to real.', signatures: [{ label: 'Real(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/real_func.html' }),
    globalFunction({ name: 'Date', category: 'Conversion', summary: 'Converts a value to date.', signatures: [{ label: 'Date(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/date_func.html' }),
    globalFunction({ name: 'Time', category: 'Conversion', summary: 'Converts a value to time.', signatures: [{ label: 'Time(value)', parameters: [{ label: 'value', documentation: 'The value you want to convert.' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/time_func.html' }),
    globalFunction({ name: 'Blob', category: 'Conversion', summary: 'Converts a value to blob.', signatures: [{ label: 'Blob(value)' }] }),
    globalFunction({ name: 'BlobMid', category: 'Conversion', summary: 'Extracts a portion of a blob starting from a given position.', signatures: [{ label: 'BlobMid(value, start, length?)' }] }),
    globalFunction({ name: 'IntHigh', category: 'Conversion', summary: 'Extracts the high half of a compound integer value.', signatures: [{ label: 'IntHigh(value)' }] }),
    globalFunction({ name: 'IntLow', category: 'Conversion', summary: 'Extracts the low half of a compound integer value.', signatures: [{ label: 'IntLow(value)' }] }),
    globalFunction({ name: 'ToAnsi', category: 'Conversion', summary: 'Converts a textual value to an ANSI representation.', signatures: [{ label: 'ToAnsi(value)' }] }),
    globalFunction({ name: 'ToUnicode', category: 'Conversion', summary: 'Converts a textual value to a Unicode representation.', signatures: [{ label: 'ToUnicode(value)' }] }),
    globalFunction({ name: 'Today', category: 'Date and time', summary: 'Returns the current system date.', signatures: [{ label: 'Today()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/today_func.html' }),
    globalFunction({ name: 'Now', category: 'Date and time', summary: 'Returns the current system date and time.', signatures: [{ label: 'Now()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/now_func.html' }),
    globalFunction({ name: 'Year', category: 'Date and time', summary: 'Returns the year of a date.', signatures: [{ label: 'Year(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/year_func.html' }),
    globalFunction({ name: 'Month', category: 'Date and time', summary: 'Returns the month of a date.', signatures: [{ label: 'Month(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/month_func.html' }),
    globalFunction({ name: 'Day', category: 'Date and time', summary: 'Returns the day of a date.', signatures: [{ label: 'Day(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/day_func.html' }),
    globalFunction({ name: 'DayName', category: 'Date and time', summary: 'Returns the name of the day of the week for a date.', signatures: [{ label: 'DayName(date)', parameters: [{ label: 'date' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dayName_func.html' }),
    globalFunction({ name: 'DayNumber', category: 'Date and time', summary: 'Returns the number of the day of the week for a date.', signatures: [{ label: 'DayNumber(date)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dayNumber_func.html' }),
    globalFunction({ name: 'DaysAfter', category: 'Date and time', summary: 'Returns the number of days between two dates.', signatures: [{ label: 'DaysAfter(startDate, endDate)' }] }),
    globalFunction({ name: 'Hour', category: 'Date and time', summary: 'Returns the hour of a time value.', signatures: [{ label: 'Hour(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/hour_func.html' }),
    globalFunction({ name: 'Minute', category: 'Date and time', summary: 'Returns the minutes of a time value.', signatures: [{ label: 'Minute(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/minute_func.html' }),
    globalFunction({ name: 'Second', category: 'Date and time', summary: 'Returns the seconds of a time value.', signatures: [{ label: 'Second(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/second_func.html' }),
    globalFunction({ name: 'SecondsAfter', category: 'Date and time', summary: 'Returns the difference in seconds between two time values.', signatures: [{ label: 'SecondsAfter(startTime, endTime)' }] }),
    globalFunction({
        name: 'DateTime',
        category: 'Date and time',
        summary: 'Combines a Date and a Time into a DateTime value.',
        signatures: [{
            label: 'DateTime(date, time)',
            parameters: [
                { label: 'date', documentation: 'The date part of the new DateTime.' },
                { label: 'time', documentation: 'The time part of the new DateTime.' },
            ],
        }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/datetime_func.html',
    }),
    globalFunction({ name: 'Abs', category: 'Math', summary: 'Returns the absolute value.', signatures: [{ label: 'Abs ( n )', parameters: [{ label: 'n', documentation: 'The number for which you want the absolute value' }] }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/abs_func.html' }),
    globalFunction({ name: 'ACos', category: 'Math', summary: 'Returns the arccosine of the specified value.', signatures: [{ label: 'ACos(number)' }] }),
    globalFunction({ name: 'ASin', category: 'Math', summary: 'Returns the arcsine of the specified value.', signatures: [{ label: 'ASin(number)' }] }),
    globalFunction({ name: 'ATan', category: 'Math', summary: 'Returns the arctangent of the specified value.', signatures: [{ label: 'ATan(number)' }] }),
    globalFunction({ name: 'Ceiling', category: 'Math', summary: 'Rounds a number to the next higher integer.', signatures: [{ label: 'Ceiling(number)' }] }),
    globalFunction({ name: 'Round', category: 'Math', summary: 'Rounds a number to the specified number of decimal places.', signatures: [{ label: 'Round(number, decimals)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/round_func.html' }),
    globalFunction({ name: 'Mod', category: 'Math', summary: 'Returns the remainder of a division.', signatures: [{ label: 'Mod(dividend, divisor)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/mod_func.html' }),
    globalFunction({ name: 'Sqrt', category: 'Math', summary: 'Returns the square root.', signatures: [{ label: 'Sqrt(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/sqrt_func.html' }),
    globalFunction({ name: 'Max', category: 'Math', summary: 'Returns the larger of two numbers.', signatures: [{ label: 'Max(left, right)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/max_func.html' }),
    globalFunction({ name: 'Min', category: 'Math', summary: 'Returns the smaller of two numbers.', signatures: [{ label: 'Min(left, right)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/min_func.html' }),
    globalFunction({ name: 'Log', category: 'Math', summary: 'Returns the natural logarithm of the specified value.', signatures: [{ label: 'Log(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/log_func.html' }),
    globalFunction({ name: 'LogTen', category: 'Math', summary: 'Returns the base 10 logarithm of the specified value.', signatures: [{ label: 'LogTen(number)' }] }),
    globalFunction({ name: 'Exp', category: 'Math', summary: 'Returns the exponential of the specified value.', signatures: [{ label: 'Exp(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/exp_func.html' }),
    globalFunction({ name: 'Fact', category: 'Math', summary: 'Returns the factorial of the specified number.', signatures: [{ label: 'Fact(number)' }] }),
    globalFunction({ name: 'Sin', category: 'Math', summary: 'Returns the sine of the specified angle.', signatures: [{ label: 'Sin(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/sin_func.html' }),
    globalFunction({ name: 'Cos', category: 'Math', summary: 'Returns the cosine of the specified angle.', signatures: [{ label: 'Cos(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/cos_func.html' }),
    globalFunction({ name: 'Tan', category: 'Math', summary: 'Returns the tangent of the specified angle.', signatures: [{ label: 'Tan(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/tan_func.html' }),
    globalFunction({ name: 'Sign', category: 'Math', summary: 'Returns the sign of the specified number.', signatures: [{ label: 'Sign(number)' }] }),
    globalFunction({ name: 'Truncate', category: 'Math', summary: 'Truncates a number without rounding it.', signatures: [{ label: 'Truncate(number, decimals?)' }] }),
    globalFunction({ name: 'Rand', category: 'Math', summary: 'Returns a pseudorandom integer.', signatures: [{ label: 'Rand(limit)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rand_func.html' }),
    globalFunction({ name: 'Randomize', category: 'Math', summary: 'Initializes the pseudorandom generator seed.', signatures: [{ label: 'Randomize(seed?)' }] }),
    globalFunction({
        name: 'UpperBound',
        category: 'Math',
        summary: 'Returns the upper bound of a dimension of an array.',
        signatures: [{
            label: 'UpperBound(array, dimension?)',
            parameters: [
                { label: 'array', documentation: 'The array for which you want the upper bound.' },
                { label: 'dimension?', documentation: 'The dimension of the array (default is 1).' },
            ],
        }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/upperbound_func.html',
    }),
    globalFunction({
        name: 'LowerBound',
        category: 'Math',
        summary: 'Returns the lower bound of a dimension of an array.',
        signatures: [{
            label: 'LowerBound(array, dimension?)',
            parameters: [
                { label: 'array', documentation: 'The array for which you want the lower bound.' },
                { label: 'dimension?', documentation: 'The dimension of the array (default is 1).' },
            ],
        }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/lowerbound_func.html',
    }),
    globalFunction({ name: 'TypeOf', category: 'Objects', summary: 'Returns the type of a PowerBuilder object.', signatures: [{ label: 'TypeOf(objectRef)' }] }),
    globalFunction({ name: 'ClassName', category: 'Objects', summary: 'Returns the class name of the object.', signatures: [{ label: 'ClassName(objectRef)' }] }),
    globalFunction({ name: 'Handle', category: 'Objects', summary: 'Returns the native handle associated with the visual object.', signatures: [{ label: 'Handle(objectRef)' }] }),
    globalFunction({ name: 'GetApplication', category: 'Objects', summary: 'Returns a reference to the Application object.', signatures: [{ label: 'GetApplication()' }] }),
    globalFunction({ name: 'GetFocus', category: 'Objects', summary: 'Returns the object that currently has the focus.', signatures: [{ label: 'GetFocus()' }] }),
    globalFunction({ name: 'PopulateError', category: 'Errors', summary: 'Populates the properties of the Error object.', signatures: [{ label: 'PopulateError(code, message)' }] }),
    globalFunction({ name: 'SignalError', category: 'Errors', summary: 'Triggers the SystemError event.', signatures: [{ label: 'SignalError(code?, message?)' }] }),
    globalFunction({ name: 'FileOpen', category: 'Files', summary: 'Opens a file and returns a descriptor.', signatures: [{ label: 'FileOpen(filename, mode?, access?, lock?, write?, encoding?)' }] }),
    globalFunction({ name: 'FileClose', category: 'Files', summary: 'Closes an open file.', signatures: [{ label: 'FileClose(fileNumber)' }] }),
    globalFunction({ name: 'FileRead', category: 'Files', summary: 'Reads data from a file.', signatures: [{ label: 'FileRead(fileNumber, variable)' }] }),
    globalFunction({ name: 'FileWrite', category: 'Files', summary: 'Writes data to a file.', signatures: [{ label: 'FileWrite(fileNumber, variable)' }] }),
    globalFunction({ name: 'FileExists', category: 'Files', summary: 'Returns TRUE if the file exists.', signatures: [{ label: 'FileExists(filename)' }] }),
    globalFunction({ name: 'FileCopy', category: 'Files', summary: 'Copies a file to a new location.', signatures: [{ label: 'FileCopy(source, target, replace?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileCopy_func.html' }),
    globalFunction({ name: 'FileDelete', category: 'Files', summary: 'Deletes a file.', signatures: [{ label: 'FileDelete(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileDelete_func.html' }),
    globalFunction({ name: 'FileMove', category: 'Files', summary: 'Moves or renames a file.', signatures: [{ label: 'FileMove(source, target, replace?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileMove_func.html' }),
    globalFunction({ name: 'FileLength', category: 'Files', summary: 'Returns the size of a file in bytes.', signatures: [{ label: 'FileLength(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileLength_func.html' }),
    globalFunction({ name: 'GetCurrentDirectory', category: 'Files', summary: 'Returns the current working directory.', signatures: [{ label: 'GetCurrentDirectory()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getCurrentDirectory_func.html' }),
    globalFunction({ name: 'ChangeDirectory', category: 'Files', summary: 'Changes the current working directory.', signatures: [{ label: 'ChangeDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/changeDirectory_func.html' }),
    globalFunction({ name: 'DirectoryExists', category: 'Files', summary: 'Returns TRUE if the directory exists.', signatures: [{ label: 'DirectoryExists(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/directoryExists_func.html' }),
    globalFunction({ name: 'CreateDirectory', category: 'Files', summary: 'Creates a directory.', signatures: [{ label: 'CreateDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/createDirectory_func.html' }),
    globalFunction({ name: 'RemoveDirectory', category: 'Files', summary: 'Removes an empty directory.', signatures: [{ label: 'RemoveDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/removeDirectory_func.html' }),
    globalFunction({
        name: 'GetFileOpenName',
        category: 'Dialogs',
        summary: 'Displays the standard dialog box for selecting the file to be opened.',
        signatures: [{ label: 'GetFileOpenName(title, fileName, initialDir?, defaultExtension?, filter?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFileOpenName_func.html',
    }),
    globalFunction({
        name: 'GetFileSaveName',
        category: 'Dialogs',
        summary: 'Displays the standard dialog box for selecting the file to be saved.',
        signatures: [{ label: 'GetFileSaveName(title, fileName, initialDir?, defaultExtension?, filter?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFileSaveName_func.html',
    }),
    globalFunction({
        name: 'GetFolder',
        category: 'Dialogs',
        summary: 'Displays the standard dialog box for selecting a folder.',
        signatures: [{ label: 'GetFolder(title, folderName)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFolder_func.html',
    }),
    globalFunction({
        name: 'ProfileInt',
        category: 'Configuration',
        summary: 'Reads an integer value from an INI file or the Windows registry.',
        signatures: [{ label: 'ProfileInt(filename, section, key, default)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/profileInt_func.html',
    }),
    globalFunction({ name: 'ProfileString', category: 'Configuration', summary: 'Reads a value from an INI file.', signatures: [{ label: 'ProfileString(filename, section, key, default?)' }] }),
    globalFunction({ name: 'SetProfileString', category: 'Configuration', summary: 'Writes a value to an INI file.', signatures: [{ label: 'SetProfileString(filename, section, key, value)' }] }),
    globalFunction({ name: 'RGB', category: 'System', summary: 'Returns a long representing a color.', signatures: [{ label: 'RGB(red, green, blue)' }] }),
    globalFunction({ name: 'KeyDown', category: 'System', summary: 'Returns TRUE if the specified key is pressed.', signatures: [{ label: 'KeyDown(keyCode)' }] }),
    globalFunction({ name: 'Idle', category: 'System', summary: 'Sets the time before the Idle event is triggered.', signatures: [{ label: 'Idle(seconds)' }] }),
    globalFunction({ name: 'Yield', category: 'System', summary: 'Allows the system to process pending messages.', signatures: [{ label: 'Yield()' }] }),
    globalFunction({ name: 'Run', category: 'System', summary: 'Executes an external program.', signatures: [{ label: 'Run(commandLine, windowState?)' }] }),
    globalFunction({ name: 'OpenWithParm', category: 'System', summary: 'Opens a window passing an initial parameter.', signatures: [{ label: 'OpenWithParm(windowVariable, parameter)' }] }),
    globalFunction({ name: 'CloseWithReturn', category: 'System', summary: 'Closes a window returning a value to the caller.', signatures: [{ label: 'CloseWithReturn(windowVariable, returnValue)' }] }),
    globalFunction({ name: 'Restart', category: 'System', summary: 'Restarts the PowerBuilder application.', signatures: [{ label: 'Restart()' }] }),
    globalFunction({ name: 'Cpu', category: 'System', summary: 'Returns the CPU time used by the application in milliseconds.', signatures: [{ label: 'Cpu()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/cpu_func.html' }),
    globalFunction({ name: 'DBHandle', category: 'System', summary: 'Returns the native handle associated with a database connection.', signatures: [{ label: 'DBHandle(transactionObject)' }] }),
    globalFunction({ name: 'DebugBreak', category: 'System', summary: 'Forces a break for debugging when a debugger is available.', signatures: [{ label: 'DebugBreak()' }] }),
    globalFunction({ name: 'GarbageCollect', category: 'System', summary: 'Requests the release of memory from unreferenced objects.', signatures: [{ label: 'GarbageCollect()' }] }),
    globalFunction({ name: 'GarbageCollectGetTimeLimit', category: 'System', summary: 'Returns the current time limit used by the garbage collector.', signatures: [{ label: 'GarbageCollectGetTimeLimit()' }] }),
    globalFunction({ name: 'GarbageCollectSetTimeLimit', category: 'System', summary: 'Configures the time limit used by the garbage collector.', signatures: [{ label: 'GarbageCollectSetTimeLimit(limit)' }] }),
    globalFunction({ name: 'Sleep', category: 'System', summary: 'Suspends execution for the specified interval.', signatures: [{ label: 'Sleep(duration)' }] }),
    globalFunction({ name: 'Timer', category: 'System', summary: 'Returns the current value of the system timer.', signatures: [{ label: 'Timer()' }] }),
    globalFunction({ name: 'CommandParm', category: 'System', summary: 'Returns the command line parameters passed to the application.', signatures: [{ label: 'CommandParm()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/commandParm.html' }),
    globalFunction({ name: 'GetEnvironment', category: 'System', summary: 'Loads information about the operating system, processor, and screen into an Environment object.', signatures: [{ label: 'GetEnvironment(environmentinfo)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getEnvironment_func.html' }),
    globalFunction({ name: 'GetInstalledRuntimes', category: 'Project / IDE', summary: 'Returns the PowerBuilder Runtime versions installed on the current computer.', signatures: [{ label: 'GetInstalledRuntimes()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/GetInstalledRuntimes_func.html' }),
    globalFunction({ name: 'IsRunningAsSolution', category: 'Project / IDE', summary: 'Indicates if the current application is running as a solution and not as a workspace.', signatures: [{ label: 'IsRunningAsSolution()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/IsRunningAsSolution_func.html' }),
    globalFunction({ name: 'AddToLibraryList', category: 'Project / IDE', summary: 'Adds a PBL or PBD library to the application\'s active library list.', signatures: [{ label: 'AddToLibraryList(libraryName)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/addtolibrarylist_func.html' }),
    globalFunction({ name: 'GetLibraryList', category: 'Project / IDE', summary: 'Returns the application\'s active library list as a comma-separated string.', signatures: [{ label: 'GetLibraryList()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getLibraryList_func.html' }),
    globalFunction({ name: 'SetLibraryList', category: 'Project / IDE', summary: 'Replaces the application\'s active library list.', signatures: [{ label: 'SetLibraryList(libraryList)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/setLibraryList_func.html' }),
    globalFunction({ name: 'RegistryDelete', category: 'Configuration', summary: 'Deletes a key or value from the specified branch of the Windows registry.', signatures: [{ label: 'RegistryDelete(key, valueName)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryDelete_func.html' }),
    globalFunction({ name: 'RegistryGet', category: 'Configuration', summary: 'Reads a value from the Windows registry into a compatible PowerBuilder variable.', signatures: [{ label: 'RegistryGet(key, valueName, valueVariable)' }, { label: 'RegistryGet(key, valueName, valueType, valueVariable)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryGet_func.html' }),
    globalFunction({ name: 'RegistryKeys', category: 'Configuration', summary: 'Obtains the list of immediate subkeys under a Windows registry key.', signatures: [{ label: 'RegistryKeys(key, subkeys)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryKeys_func.html' }),
    globalFunction({ name: 'RegistrySet', category: 'Configuration', summary: 'Writes or updates a value in the Windows registry.', signatures: [{ label: 'RegistrySet(key, valueName, valueType, value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registrySet_func.html' }),
    globalFunction({ name: 'RegistryValues', category: 'Configuration', summary: 'Obtains the list of value names defined for a Windows registry key.', signatures: [{ label: 'RegistryValues(key, valueNames)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryValues_func.html' }),
    globalFunction({ name: 'RelativeDate', category: 'Date and time', summary: 'Returns a date shifted by a number of days relative to another date.', signatures: [{ label: 'RelativeDate(date, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/relativeDate_func.html' }),
    globalFunction({ name: 'RelativeTime', category: 'Date and time', summary: 'Returns a time shifted by a number of seconds relative to another time.', signatures: [{ label: 'RelativeTime(time, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/relativeTime_func.html' }),
    globalFunction({ name: 'Pi', category: 'Math', summary: 'Returns the value of the constant pi.', signatures: [{ label: 'Pi()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pi_func.html' }),
    globalFunction({
        name: 'FileReadEx',
        category: 'Files',
        summary: 'Reads data from an open file and returns the number of bytes read.',
        signatures: [
            { label: 'FileReadEx(fileNumber, blob, length?)' },
            { label: 'FileReadEx(fileNumber, string)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileReadEx_func.html',
    }),
    globalFunction({
        name: 'FileWriteEx',
        category: 'Files',
        summary: 'Writes data to an open file and returns the number of bytes written.',
        signatures: [
            { label: 'FileWriteEx(fileNumber, blob)' },
            { label: 'FileWriteEx(fileNumber, string)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileWriteEx_func.html',
    }),
    globalFunction({
        name: 'FileSeek',
        category: 'Files',
        summary: 'Repositions the read or write pointer of a file.',
        signatures: [{ label: 'FileSeek(fileNumber, location, origin?)' }],
        manualOverlay: {
            mode: 'override',
            reason: 'Maintains the stable curated signature used by signatureHelp and completion, avoiding official rail verbosity/generated arity drift.',
            evidence: [
                'generated:global-functions:callable:powerscript:global:fileseek:all',
                'manual-core:global-functions:callable:powerscript:global:fileseek:all',
            ],
            reviewedBy: 'B327',
            targetKey: {
                domain: 'global-functions',
                kind: 'callable',
                namespace: 'powerscript',
                invocation: 'global',
                name: 'FileSeek',
            },
        },
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileSeek_func.html',
    }),
    globalFunction({
        name: 'FileSeek64',
        category: 'Files',
        summary: 'Repositions the read or write pointer for large files.',
        signatures: [{ label: 'FileSeek64(fileNumber, location, origin?)' }],
        manualOverlay: {
            mode: 'override',
            reason: 'Maintains the stable curated signature used by signatureHelp and completion, avoiding official rail verbosity/generated arity drift.',
            evidence: [
                'generated:global-functions:callable:powerscript:global:fileseek64:all',
                'manual-core:global-functions:callable:powerscript:global:fileseek64:all',
            ],
            reviewedBy: 'B327',
            targetKey: {
                domain: 'global-functions',
                kind: 'callable',
                namespace: 'powerscript',
                invocation: 'global',
                name: 'FileSeek64',
            },
        },
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileSeek64_func.html',
    }),
    globalFunction({ name: 'FileLength64', category: 'Files', summary: 'Returns the size of a file as longlong.', signatures: [{ label: 'FileLength64(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileLength64_func.html' }),
    globalFunction({ name: 'FileEncoding', category: 'Files', summary: 'Detects the text encoding of a file.', signatures: [{ label: 'FileEncoding(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileEncoding_func.html' }),
    globalFunction({ name: 'PointerX', category: 'System', summary: 'Returns the current X coordinate of the mouse pointer.', signatures: [{ label: 'PointerX()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pointerX_func.html' }),
    globalFunction({ name: 'PointerY', category: 'System', summary: 'Returns the current Y coordinate of the mouse pointer.', signatures: [{ label: 'PointerY()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pointerY_func.html' }),
    globalFunction({
        name: 'SetPointer',
        category: 'System',
        summary: 'Changes the current shape of the mouse pointer.',
        signatures: [
            { label: 'SetPointer(pointerStyle)' },
            { label: 'SetPointer(cursorFile, hotspotX?, hotspotY?)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/setPointer_func.html',
    }),
    globalFunction({ name: 'WorkSpaceHeight', category: 'System', summary: 'Returns the height of the available work area on the screen.', signatures: [{ label: 'WorkSpaceHeight()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspaceheight_func.html' }),
    globalFunction({ name: 'WorkSpaceWidth', category: 'System', summary: 'Returns the width of the available work area on the screen.', signatures: [{ label: 'WorkSpaceWidth()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacewidth_func.html' }),
    globalFunction({ name: 'WorkSpaceX', category: 'System', summary: 'Returns the starting X coordinate of the available work area on the screen.', signatures: [{ label: 'WorkSpaceX()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacex_func.html' }),
    globalFunction({ name: 'WorkSpaceY', category: 'System', summary: 'Returns the starting Y coordinate of the available work area on the screen.', signatures: [{ label: 'WorkSpaceY()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacey_func.html' }),
    globalFunction({ name: 'PixelsToUnits', category: 'System', summary: 'Converts a measurement in pixels to PowerBuilder units.', signatures: [{ label: 'PixelsToUnits(value, axis?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pixelsToUnits_func.html' }),
    globalFunction({ name: 'UnitsToPixels', category: 'System', summary: 'Converts a measurement in PowerBuilder units to pixels.', signatures: [{ label: 'UnitsToPixels(value, axis?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/unitsToPixels_func.html' }),
    globalFunction({
        name: 'LenW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Len.',
        signatures: [{ label: 'LenW(value)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Len',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/lenW_func.html',
    }),
    globalFunction({
        name: 'LeftTrimW',
        category: 'Strings',
        summary: 'Legacy Unicode version of LeftTrim.',
        signatures: [{ label: 'LeftTrimW(string, removeallspaces?)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'LeftTrim',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/leftTrimW_func.html',
    }),
    globalFunction({
        name: 'RightTrimW',
        category: 'Strings',
        summary: 'Legacy Unicode version of RightTrim.',
        signatures: [{ label: 'RightTrimW(string, removeallspaces?)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'RightTrim',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightTrimW_func.html',
    }),
    globalFunction({
        name: 'LeftW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Left.',
        signatures: [{ label: 'LeftW(value, count)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Left',
    }),
    globalFunction({
        name: 'RightW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Right.',
        signatures: [{ label: 'RightW(value, count)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Right',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightW_func.html',
    }),
    globalFunction({
        name: 'MidW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Mid.',
        signatures: [{ label: 'MidW(value, start, length?)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Mid',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/midW_func.html',
    }),
    globalFunction({
        name: 'PosW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Pos.',
        signatures: [{ label: 'PosW(value, target, start?)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Pos',
    }),
    globalFunction({
        name: 'MatchW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Match.',
        signatures: [{ label: 'MatchW(string, textpattern)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Match',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/matchW_func.html',
    }),
    globalFunction({
        name: 'FillW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Fill.',
        signatures: [{ label: 'FillW(chars, n)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Fill',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fillW_func.html',
    }),
    globalFunction({
        name: 'ReplaceW',
        category: 'Strings',
        summary: 'Legacy Unicode version of Replace.',
        signatures: [{ label: 'ReplaceW(value, start, length, replacement)' }],
        obsolete: true,
        obsoleteMessage: 'The *W family is obsolete in favor of standard Unicode functions.',
        replacement: 'Replace',
    }),
    globalFunction({
        name: 'ChooseColor',
        category: 'Dialogs',
        summary: 'Displays the standard dialog box for selecting a color.',
        signatures: [{ label: 'ChooseColor(color, customColors[])' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/chooseColor_func.html',
    }),
    globalFunction({
        name: 'ShowHelp',
        category: 'Dialogs',
        summary: 'Displays a help topic from the specified file.',
        signatures: [{ label: 'ShowHelp(helpfile, helpcommand, typeid?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/showHelp_func.html',
    }),
    globalFunction({
        name: 'ShowPopupHelp',
        category: 'Dialogs',
        summary: 'Displays context-sensitive popup help at a screen position.',
        signatures: [{ label: 'ShowPopupHelp(helpfile, x, y, contextid)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/showPopupHelp_func.html',
    }),
    globalFunction({
        name: 'OpenURL',
        category: 'Web / HTTP',
        summary: 'Opens a URL using the handler registered in the system.',
        signatures: [{ label: 'OpenURL(url)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/OpenURL_func.html',
    }),
    globalFunction({
        name: 'TraceBegin',
        category: 'System',
        summary: 'Marks the start of an activity within the execution trace.',
        signatures: [{ label: 'TraceBegin(identifier)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceBegin_func.html',
    }),
    globalFunction({
        name: 'TraceClose',
        category: 'System',
        summary: 'Closes the currently open tracing file.',
        signatures: [{ label: 'TraceClose()' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceClose_func.html',
    }),
    globalFunction({
        name: 'TraceDisableActivity',
        category: 'System',
        summary: 'Disables tracing for the specified activity.',
        signatures: [{ label: 'TraceDisableActivity(activity)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceDisableActivity_func.html',
    }),
    globalFunction({
        name: 'TraceEnableActivity',
        category: 'System',
        summary: 'Enables tracing for the specified activity.',
        signatures: [{ label: 'TraceEnableActivity(activity)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceEnableActivity_func.html',
    }),
    globalFunction({
        name: 'TraceEnd',
        category: 'System',
        summary: 'Marks the end of an activity within the execution trace.',
        signatures: [{ label: 'TraceEnd()' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceEnd_func.html',
    }),
    globalFunction({
        name: 'TraceError',
        category: 'System',
        summary: 'Writes an error message to the execution trace.',
        signatures: [{ label: 'TraceError(severity, message)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceError_func.html',
    }),
    globalFunction({
        name: 'TraceOpen',
        category: 'System',
        summary: 'Opens a tracing file and configures the associated timer.',
        signatures: [{ label: 'TraceOpen(filename, timer)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceOpen_func.html',
    }),
    globalFunction({
        name: 'TraceUser',
        category: 'System',
        summary: 'Writes a user message to the execution trace.',
        signatures: [{ label: 'TraceUser(info, message)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceUser_func.html',
    }),
    globalFunction({
        name: 'PBGetMenuString',
        category: 'System',
        summary: 'Retrieves the text of a native menu item.',
        signatures: [{ label: 'PBGetMenuString(hmenu, nPos, caption, nMaxLength)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pBGetMenuString_func.html',
    }),
    globalFunction({
        name: 'Open',
        category: 'System',
        summary: 'Opens a window, with optional support for an owner or parent container.',
        signatures: [{ label: 'Open(windowvar, parent?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/open_func.html',
    }),
    globalFunction({
        name: 'Close',
        category: 'System',
        summary: 'Closes the specified window.',
        signatures: [{ label: 'Close(windowname)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/close_func.html',
    }),
];
