import { PbSystemSymbolEntry } from '../../types';
import { globalFunction } from '../common';

export const PB_MANUAL_CORE_GLOBAL_FUNCTION_CATEGORIES = [
    'UI',
    'Eventos',
    'Validación',
    'Strings',
    'Conversión',
    'Fecha y hora',
    'Matemáticas',
    'Objetos',
    'Errores',
    'Archivos',
    'Diálogos',
    'Configuración',
    'Proyecto / IDE',
    'Web / HTTP',
    'Sistema',
] as const;

export const PB_MANUAL_CORE_GLOBAL_FUNCTIONS: readonly PbSystemSymbolEntry[] = [
    globalFunction({
        name: 'MessageBox',
        category: 'UI',
        summary: 'Muestra un cuadro de mensaje y devuelve el botón pulsado.',
        signatures: [{
            label: 'MessageBox(title, text, icon?, button?, default?)',
            parameters: [
                { label: 'title', documentation: 'Título de la ventana de mensaje.' },
                { label: 'text', documentation: 'Texto principal que se muestra al usuario.' },
                { label: 'icon?', documentation: 'Icono opcional del cuadro de mensaje.' },
                { label: 'button?', documentation: 'Conjunto opcional de botones.' },
                { label: 'default?', documentation: 'Botón por defecto opcional.' },
            ],
        }],
        appliesTo: ['cualquier script PowerScript'],
    }),
    globalFunction({
        name: 'Clipboard',
        category: 'UI',
        summary: 'Obtiene o establece el texto del portapapeles.',
        signatures: [
            {
                label: 'Clipboard()',
                documentation: 'Devuelve el contenido textual actual del portapapeles.',
            },
            {
                label: 'Clipboard(text)',
                documentation: 'Sustituye el contenido textual del portapapeles.',
                parameters: [
                    { label: 'text', documentation: 'Texto que se copiará al portapapeles.' },
                ],
            },
        ],
        appliesTo: ['scripts con interacción de escritorio'],
    }),
    globalFunction({ name: 'Beep', category: 'UI', summary: 'Emite el número de pitidos indicado.', signatures: [{ label: 'Beep(count)' }] }),
    globalFunction({
        name: 'TriggerEvent',
        category: 'Eventos',
        summary: 'Dispara un evento de forma síncrona sobre un objeto.',
        signatures: [{
            label: 'TriggerEvent(target, eventName, argumentList?)',
            parameters: [
                { label: 'target', documentation: 'Objeto sobre el que se ejecuta el evento.' },
                { label: 'eventName', documentation: 'Nombre del evento que se quiere disparar.' },
                { label: 'argumentList?', documentation: 'Lista opcional de argumentos del evento.' },
            ],
        }],
        appliesTo: ['scripts que invocan eventos de objetos PowerBuilder'],
    }),
    globalFunction({
        name: 'PostEvent',
        category: 'Eventos',
        summary: 'Encola un evento para ejecutarlo de forma asíncrona.',
        signatures: [{
            label: 'PostEvent(target, eventName, argumentList?)',
            parameters: [
                { label: 'target', documentation: 'Objeto sobre el que se encola el evento.' },
                { label: 'eventName', documentation: 'Nombre del evento que se quiere postear.' },
                { label: 'argumentList?', documentation: 'Lista opcional de argumentos del evento.' },
            ],
        }],
        appliesTo: ['scripts que desacoplan la ejecución de eventos'],
    }),
    globalFunction({ name: 'IsNull', category: 'Validación', summary: 'Devuelve TRUE si la variable es NULL.', signatures: [{ label: 'IsNull(value)' }] }),
    globalFunction({ name: 'IsValid', category: 'Validación', summary: 'Devuelve TRUE si la variable de objeto referencia un objeto válido.', signatures: [{ label: 'IsValid(objectRef)' }] }),
    globalFunction({
        name: 'IsNumber',
        category: 'Validación',
        summary: 'Devuelve TRUE si una cadena representa un valor numérico válido.',
        signatures: [{ label: 'IsNumber(value)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isNumber_func.html',
    }),
    globalFunction({ name: 'IsDate', category: 'Validación', summary: 'Devuelve TRUE si una cadena representa una fecha válida.', signatures: [{ label: 'IsDate(datevalue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isDate_func.html' }),
    globalFunction({ name: 'IsTime', category: 'Validación', summary: 'Devuelve TRUE si una cadena representa una hora válida.', signatures: [{ label: 'IsTime(timevalue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/isTime_func.html' }),
    globalFunction({ name: 'SetNull', category: 'Validación', summary: 'Asigna NULL a una variable.', signatures: [{ label: 'SetNull(variable)' }] }),
    globalFunction({ name: 'Trim', category: 'Strings', summary: 'Elimina los espacios iniciales y finales.', signatures: [{ label: 'Trim(value)' }] }),
    globalFunction({
        name: 'TrimW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Trim.',
        signatures: [{ label: 'TrimW(value)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Trim',
    }),
    globalFunction({ name: 'LeftTrim', category: 'Strings', summary: 'Elimina los espacios al inicio de una cadena.', signatures: [{ label: 'LeftTrim(string, removeallspaces?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/leftTrim_func.html' }),
    globalFunction({ name: 'RightTrim', category: 'Strings', summary: 'Elimina los espacios al final de una cadena.', signatures: [{ label: 'RightTrim(string, removeallspaces?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightTrim_func.html' }),
    globalFunction({ name: 'Left', category: 'Strings', summary: 'Devuelve los caracteres más a la izquierda.', signatures: [{ label: 'Left(value, count)' }] }),
    globalFunction({ name: 'Right', category: 'Strings', summary: 'Devuelve los caracteres más a la derecha.', signatures: [{ label: 'Right(value, count)' }] }),
    globalFunction({ name: 'Mid', category: 'Strings', summary: 'Devuelve caracteres desde una posición intermedia.', signatures: [{ label: 'Mid(value, start, length?)' }] }),
    globalFunction({ name: 'Len', category: 'Strings', summary: 'Devuelve la longitud de una cadena.', signatures: [{ label: 'Len(value)' }] }),
    globalFunction({ name: 'Pos', category: 'Strings', summary: 'Devuelve la posición de un fragmento dentro de una cadena.', signatures: [{ label: 'Pos(value, target, start?)' }] }),
    globalFunction({ name: 'LastPos', category: 'Strings', summary: 'Devuelve la última aparición de una subcadena dentro de otra cadena.', signatures: [{ label: 'LastPos(string1, string2)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/lastPos_func.html' }),
    globalFunction({ name: 'Match', category: 'Strings', summary: 'Comprueba si una cadena coincide con un patrón de texto.', signatures: [{ label: 'Match(string, textpattern)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/match_func.html' }),
    globalFunction({ name: 'Upper', category: 'Strings', summary: 'Convierte el texto a mayúsculas.', signatures: [{ label: 'Upper(value)' }] }),
    globalFunction({ name: 'Lower', category: 'Strings', summary: 'Convierte el texto a minúsculas.', signatures: [{ label: 'Lower(value)' }] }),
    globalFunction({ name: 'WordCap', category: 'Strings', summary: 'Convierte la primera letra de cada palabra a mayúscula y el resto a minúsculas.', signatures: [{ label: 'WordCap(text)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/wordcap_func.html' }),
    globalFunction({ name: 'Replace', category: 'Strings', summary: 'Sustituye caracteres a partir de una posición dada.', signatures: [{ label: 'Replace(value, start, length, replacement)' }] }),
    globalFunction({ name: 'Space', category: 'Strings', summary: 'Devuelve una cadena compuesta por espacios.', signatures: [{ label: 'Space(count)' }] }),
    globalFunction({ name: 'Fill', category: 'Strings', summary: 'Construye una cadena de la longitud indicada repitiendo los caracteres dados.', signatures: [{ label: 'Fill(chars, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fill_func.html' }),
    globalFunction({ name: 'Asc', category: 'Strings', summary: 'Devuelve el valor numérico del primer carácter.', signatures: [{ label: 'Asc(value)' }] }),
    globalFunction({ name: 'Char', category: 'Strings', summary: 'Construye un carácter a partir de su código numérico.', signatures: [{ label: 'Char(asciiCode)' }] }),
    globalFunction({ name: 'Length', category: 'Strings', summary: 'Devuelve la longitud lógica del valor indicado.', signatures: [{ label: 'Length(value)' }] }),
    globalFunction({ name: 'Reverse', category: 'Strings', summary: 'Invierte el orden de los caracteres de una cadena.', signatures: [{ label: 'Reverse(value)' }] }),
    globalFunction({
        name: 'String',
        category: 'Conversión',
        summary: 'Convierte un valor a su representación en cadena.',
        signatures: [
            { label: 'String(value)' },
            { label: 'String(value, format)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/string_func.html',
    }),
    globalFunction({ name: 'Integer', category: 'Conversión', summary: 'Convierte un valor a integer.', signatures: [{ label: 'Integer(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/integer_func.html' }),
    globalFunction({ name: 'Long', category: 'Conversión', summary: 'Convierte un valor a long.', signatures: [{ label: 'Long(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/long_func.html' }),
    globalFunction({ name: 'Double', category: 'Conversión', summary: 'Convierte un valor a double.', signatures: [{ label: 'Double(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/double_func.html' }),
    globalFunction({ name: 'Dec', category: 'Conversión', summary: 'Convierte un valor a decimal.', signatures: [{ label: 'Dec(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dec_func.html' }),
    globalFunction({ name: 'Date', category: 'Conversión', summary: 'Convierte un valor a date.', signatures: [{ label: 'Date(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/date_func.html' }),
    globalFunction({ name: 'Time', category: 'Conversión', summary: 'Convierte un valor a time.', signatures: [{ label: 'Time(value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/time_func.html' }),
    globalFunction({ name: 'Blob', category: 'Conversión', summary: 'Convierte un valor a blob.', signatures: [{ label: 'Blob(value)' }] }),
    globalFunction({ name: 'BlobMid', category: 'Conversión', summary: 'Extrae una porción de un blob a partir de una posición dada.', signatures: [{ label: 'BlobMid(value, start, length?)' }] }),
    globalFunction({ name: 'IntHigh', category: 'Conversión', summary: 'Extrae la mitad alta de un valor entero compuesto.', signatures: [{ label: 'IntHigh(value)' }] }),
    globalFunction({ name: 'IntLow', category: 'Conversión', summary: 'Extrae la mitad baja de un valor entero compuesto.', signatures: [{ label: 'IntLow(value)' }] }),
    globalFunction({ name: 'ToAnsi', category: 'Conversión', summary: 'Convierte un valor textual a una representación ANSI.', signatures: [{ label: 'ToAnsi(value)' }] }),
    globalFunction({ name: 'ToUnicode', category: 'Conversión', summary: 'Convierte un valor textual a una representación Unicode.', signatures: [{ label: 'ToUnicode(value)' }] }),
    globalFunction({ name: 'Today', category: 'Fecha y hora', summary: 'Devuelve la fecha actual del sistema.', signatures: [{ label: 'Today()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/today_func.html' }),
    globalFunction({ name: 'Now', category: 'Fecha y hora', summary: 'Devuelve la fecha y hora actual del sistema.', signatures: [{ label: 'Now()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/now_func.html' }),
    globalFunction({ name: 'Year', category: 'Fecha y hora', summary: 'Devuelve el año de una fecha.', signatures: [{ label: 'Year(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/year_func.html' }),
    globalFunction({ name: 'Month', category: 'Fecha y hora', summary: 'Devuelve el mes de una fecha.', signatures: [{ label: 'Month(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/month_func.html' }),
    globalFunction({ name: 'Day', category: 'Fecha y hora', summary: 'Devuelve el día de una fecha.', signatures: [{ label: 'Day(dateValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/day_func.html' }),
    globalFunction({ name: 'DayName', category: 'Fecha y hora', summary: 'Devuelve el nombre del día de la semana de una fecha.', signatures: [{ label: 'DayName(date)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dayName_func.html' }),
    globalFunction({ name: 'DayNumber', category: 'Fecha y hora', summary: 'Devuelve el número del día de la semana de una fecha.', signatures: [{ label: 'DayNumber(date)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/dayNumber_func.html' }),
    globalFunction({ name: 'DaysAfter', category: 'Fecha y hora', summary: 'Devuelve los días transcurridos entre dos fechas.', signatures: [{ label: 'DaysAfter(startDate, endDate)' }] }),
    globalFunction({ name: 'Hour', category: 'Fecha y hora', summary: 'Devuelve la hora de un valor temporal.', signatures: [{ label: 'Hour(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/hour_func.html' }),
    globalFunction({ name: 'Minute', category: 'Fecha y hora', summary: 'Devuelve los minutos de un valor temporal.', signatures: [{ label: 'Minute(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/minute_func.html' }),
    globalFunction({ name: 'Second', category: 'Fecha y hora', summary: 'Devuelve los segundos de un valor temporal.', signatures: [{ label: 'Second(timeValue)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/second_func.html' }),
    globalFunction({ name: 'SecondsAfter', category: 'Fecha y hora', summary: 'Devuelve la diferencia en segundos entre dos valores temporales.', signatures: [{ label: 'SecondsAfter(startTime, endTime)' }] }),
    globalFunction({ name: 'Abs', category: 'Matemáticas', summary: 'Devuelve el valor absoluto.', signatures: [{ label: 'Abs(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/abs_func.html' }),
    globalFunction({ name: 'ACos', category: 'Matemáticas', summary: 'Devuelve el arcocoseno del valor indicado.', signatures: [{ label: 'ACos(number)' }] }),
    globalFunction({ name: 'ASin', category: 'Matemáticas', summary: 'Devuelve el arcoseno del valor indicado.', signatures: [{ label: 'ASin(number)' }] }),
    globalFunction({ name: 'ATan', category: 'Matemáticas', summary: 'Devuelve la arcotangente del valor indicado.', signatures: [{ label: 'ATan(number)' }] }),
    globalFunction({ name: 'Ceiling', category: 'Matemáticas', summary: 'Redondea un número hacia el entero inmediato superior.', signatures: [{ label: 'Ceiling(number)' }] }),
    globalFunction({ name: 'Round', category: 'Matemáticas', summary: 'Redondea un número al número de decimales indicado.', signatures: [{ label: 'Round(number, decimals)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/round_func.html' }),
    globalFunction({ name: 'Mod', category: 'Matemáticas', summary: 'Devuelve el resto de una división.', signatures: [{ label: 'Mod(dividend, divisor)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/mod_func.html' }),
    globalFunction({ name: 'Sqrt', category: 'Matemáticas', summary: 'Devuelve la raíz cuadrada.', signatures: [{ label: 'Sqrt(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/sqrt_func.html' }),
    globalFunction({ name: 'Max', category: 'Matemáticas', summary: 'Devuelve el mayor de dos números.', signatures: [{ label: 'Max(left, right)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/max_func.html' }),
    globalFunction({ name: 'Min', category: 'Matemáticas', summary: 'Devuelve el menor de dos números.', signatures: [{ label: 'Min(left, right)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/min_func.html' }),
    globalFunction({ name: 'Log', category: 'Matemáticas', summary: 'Devuelve el logaritmo natural del valor indicado.', signatures: [{ label: 'Log(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/log_func.html' }),
    globalFunction({ name: 'LogTen', category: 'Matemáticas', summary: 'Devuelve el logaritmo en base 10 del valor indicado.', signatures: [{ label: 'LogTen(number)' }] }),
    globalFunction({ name: 'Exp', category: 'Matemáticas', summary: 'Devuelve la exponencial del valor indicado.', signatures: [{ label: 'Exp(number)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/exp_func.html' }),
    globalFunction({ name: 'Fact', category: 'Matemáticas', summary: 'Devuelve el factorial del número indicado.', signatures: [{ label: 'Fact(number)' }] }),
    globalFunction({ name: 'Sin', category: 'Matemáticas', summary: 'Devuelve el seno del ángulo indicado.', signatures: [{ label: 'Sin(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/sin_func.html' }),
    globalFunction({ name: 'Cos', category: 'Matemáticas', summary: 'Devuelve el coseno del ángulo indicado.', signatures: [{ label: 'Cos(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/cos_func.html' }),
    globalFunction({ name: 'Tan', category: 'Matemáticas', summary: 'Devuelve la tangente del ángulo indicado.', signatures: [{ label: 'Tan(radians)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/tan_func.html' }),
    globalFunction({ name: 'Sign', category: 'Matemáticas', summary: 'Devuelve el signo del número indicado.', signatures: [{ label: 'Sign(number)' }] }),
    globalFunction({ name: 'Truncate', category: 'Matemáticas', summary: 'Trunca un número sin redondearlo.', signatures: [{ label: 'Truncate(number, decimals?)' }] }),
    globalFunction({ name: 'Rand', category: 'Matemáticas', summary: 'Devuelve un entero pseudoaleatorio.', signatures: [{ label: 'Rand(limit)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rand_func.html' }),
    globalFunction({ name: 'Randomize', category: 'Matemáticas', summary: 'Inicializa la semilla del generador pseudoaleatorio.', signatures: [{ label: 'Randomize(seed?)' }] }),
    globalFunction({ name: 'TypeOf', category: 'Objetos', summary: 'Devuelve el tipo de un objeto PowerBuilder.', signatures: [{ label: 'TypeOf(objectRef)' }] }),
    globalFunction({ name: 'ClassName', category: 'Objetos', summary: 'Devuelve el nombre de clase del objeto.', signatures: [{ label: 'ClassName(objectRef)' }] }),
    globalFunction({ name: 'Handle', category: 'Objetos', summary: 'Devuelve el handle nativo asociado al objeto visual.', signatures: [{ label: 'Handle(objectRef)' }] }),
    globalFunction({ name: 'GetApplication', category: 'Objetos', summary: 'Devuelve una referencia al objeto Application.', signatures: [{ label: 'GetApplication()' }] }),
        globalFunction({ name: 'GetFocus', category: 'Objetos', summary: 'Devuelve el objeto que tiene actualmente el foco.', signatures: [{ label: 'GetFocus()' }] }),
    globalFunction({ name: 'PopulateError', category: 'Errores', summary: 'Rellena las propiedades del objeto Error.', signatures: [{ label: 'PopulateError(code, message)' }] }),
    globalFunction({ name: 'SignalError', category: 'Errores', summary: 'Dispara el evento SystemError.', signatures: [{ label: 'SignalError(code?, message?)' }] }),
    globalFunction({ name: 'FileOpen', category: 'Archivos', summary: 'Abre un archivo y devuelve un descriptor.', signatures: [{ label: 'FileOpen(filename, mode?, access?, lock?, write?, encoding?)' }] }),
    globalFunction({ name: 'FileClose', category: 'Archivos', summary: 'Cierra un archivo abierto.', signatures: [{ label: 'FileClose(fileNumber)' }] }),
    globalFunction({ name: 'FileRead', category: 'Archivos', summary: 'Lee datos desde un archivo.', signatures: [{ label: 'FileRead(fileNumber, variable)' }] }),
    globalFunction({ name: 'FileWrite', category: 'Archivos', summary: 'Escribe datos en un archivo.', signatures: [{ label: 'FileWrite(fileNumber, variable)' }] }),
    globalFunction({ name: 'FileExists', category: 'Archivos', summary: 'Devuelve TRUE si el archivo existe.', signatures: [{ label: 'FileExists(filename)' }] }),
    globalFunction({ name: 'FileCopy', category: 'Archivos', summary: 'Copia un archivo a una nueva ubicación.', signatures: [{ label: 'FileCopy(source, target, replace?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileCopy_func.html' }),
    globalFunction({ name: 'FileDelete', category: 'Archivos', summary: 'Elimina un archivo.', signatures: [{ label: 'FileDelete(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileDelete_func.html' }),
    globalFunction({ name: 'FileMove', category: 'Archivos', summary: 'Mueve o renombra un archivo.', signatures: [{ label: 'FileMove(source, target, replace?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileMove_func.html' }),
    globalFunction({ name: 'FileLength', category: 'Archivos', summary: 'Devuelve el tamaño de un archivo en bytes.', signatures: [{ label: 'FileLength(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileLength_func.html' }),
    globalFunction({ name: 'GetCurrentDirectory', category: 'Archivos', summary: 'Devuelve el directorio de trabajo actual.', signatures: [{ label: 'GetCurrentDirectory()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getCurrentDirectory_func.html' }),
    globalFunction({ name: 'ChangeDirectory', category: 'Archivos', summary: 'Cambia el directorio de trabajo actual.', signatures: [{ label: 'ChangeDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/changeDirectory_func.html' }),
    globalFunction({ name: 'DirectoryExists', category: 'Archivos', summary: 'Devuelve TRUE si el directorio existe.', signatures: [{ label: 'DirectoryExists(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/directoryExists_func.html' }),
    globalFunction({ name: 'CreateDirectory', category: 'Archivos', summary: 'Crea un directorio.', signatures: [{ label: 'CreateDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/createDirectory_func.html' }),
    globalFunction({ name: 'RemoveDirectory', category: 'Archivos', summary: 'Elimina un directorio vacío.', signatures: [{ label: 'RemoveDirectory(path)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/removeDirectory_func.html' }),
    globalFunction({
        name: 'GetFileOpenName',
        category: 'Diálogos',
        summary: 'Muestra el cuadro de diálogo estándar para seleccionar el archivo que se va a abrir.',
        signatures: [{ label: 'GetFileOpenName(title, fileName, initialDir?, defaultExtension?, filter?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFileOpenName_func.html',
    }),
    globalFunction({
        name: 'GetFileSaveName',
        category: 'Diálogos',
        summary: 'Muestra el cuadro de diálogo estándar para seleccionar el archivo con el que se va a guardar.',
        signatures: [{ label: 'GetFileSaveName(title, fileName, initialDir?, defaultExtension?, filter?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFileSaveName_func.html',
    }),
    globalFunction({
        name: 'GetFolder',
        category: 'Diálogos',
        summary: 'Muestra el cuadro de diálogo estándar para seleccionar una carpeta.',
        signatures: [{ label: 'GetFolder(title, folderName)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getFolder_func.html',
    }),
    globalFunction({
        name: 'ProfileInt',
        category: 'Configuración',
        summary: 'Lee un valor entero de un archivo INI o del registro de Windows.',
        signatures: [{ label: 'ProfileInt(filename, section, key, default)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/profileInt_func.html',
    }),
    globalFunction({ name: 'ProfileString', category: 'Configuración', summary: 'Lee un valor de un archivo INI.', signatures: [{ label: 'ProfileString(filename, section, key, default?)' }] }),
    globalFunction({ name: 'SetProfileString', category: 'Configuración', summary: 'Escribe un valor en un archivo INI.', signatures: [{ label: 'SetProfileString(filename, section, key, value)' }] }),
    globalFunction({ name: 'RGB', category: 'Sistema', summary: 'Devuelve un long que representa un color.', signatures: [{ label: 'RGB(red, green, blue)' }] }),
    globalFunction({ name: 'KeyDown', category: 'Sistema', summary: 'Devuelve TRUE si la tecla indicada está pulsada.', signatures: [{ label: 'KeyDown(keyCode)' }] }),
    globalFunction({ name: 'Idle', category: 'Sistema', summary: 'Establece el tiempo antes de que se dispare el evento Idle.', signatures: [{ label: 'Idle(seconds)' }] }),
    globalFunction({ name: 'Yield', category: 'Sistema', summary: 'Permite que el sistema procese mensajes pendientes.', signatures: [{ label: 'Yield()' }] }),
    globalFunction({ name: 'Run', category: 'Sistema', summary: 'Ejecuta un programa externo.', signatures: [{ label: 'Run(commandLine, windowState?)' }] }),
    globalFunction({ name: 'OpenWithParm', category: 'Sistema', summary: 'Abre una ventana pasando un parámetro inicial.', signatures: [{ label: 'OpenWithParm(windowVariable, parameter)' }] }),
    globalFunction({ name: 'CloseWithReturn', category: 'Sistema', summary: 'Cierra una ventana devolviendo un valor al llamador.', signatures: [{ label: 'CloseWithReturn(windowVariable, returnValue)' }] }),
    globalFunction({ name: 'Restart', category: 'Sistema', summary: 'Reinicia la aplicación PowerBuilder.', signatures: [{ label: 'Restart()' }] }),
    globalFunction({ name: 'Cpu', category: 'Sistema', summary: 'Devuelve el tiempo de CPU usado por la aplicación en milisegundos.', signatures: [{ label: 'Cpu()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/cpu_func.html' }),
        globalFunction({ name: 'DBHandle', category: 'Sistema', summary: 'Devuelve el handle nativo asociado a una conexión de base de datos.', signatures: [{ label: 'DBHandle(transactionObject)' }] }),
        globalFunction({ name: 'DebugBreak', category: 'Sistema', summary: 'Fuerza una interrupción para depuración cuando hay un depurador disponible.', signatures: [{ label: 'DebugBreak()' }] }),
    globalFunction({ name: 'GarbageCollect', category: 'Sistema', summary: 'Solicita la liberación de memoria de objetos no referenciados.', signatures: [{ label: 'GarbageCollect()' }] }),
        globalFunction({ name: 'GarbageCollectGetTimeLimit', category: 'Sistema', summary: 'Devuelve el límite de tiempo actual usado por el recolector de basura.', signatures: [{ label: 'GarbageCollectGetTimeLimit()' }] }),
        globalFunction({ name: 'GarbageCollectSetTimeLimit', category: 'Sistema', summary: 'Configura el límite de tiempo usado por el recolector de basura.', signatures: [{ label: 'GarbageCollectSetTimeLimit(limit)' }] }),
        globalFunction({ name: 'Sleep', category: 'Sistema', summary: 'Suspende la ejecución durante el intervalo indicado.', signatures: [{ label: 'Sleep(duration)' }] }),
        globalFunction({ name: 'Timer', category: 'Sistema', summary: 'Devuelve el valor actual del temporizador del sistema.', signatures: [{ label: 'Timer()' }] }),
    globalFunction({ name: 'CommandParm', category: 'Sistema', summary: 'Devuelve los parámetros de línea de comandos pasados a la aplicación.', signatures: [{ label: 'CommandParm()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/commandParm.html' }),
    globalFunction({ name: 'GetEnvironment', category: 'Sistema', summary: 'Carga información del sistema operativo, procesador y pantalla en un objeto Environment.', signatures: [{ label: 'GetEnvironment(environmentinfo)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getEnvironment_func.html' }),
        globalFunction({ name: 'GetInstalledRuntimes', category: 'Proyecto / IDE', summary: 'Devuelve las versiones de PowerBuilder Runtime instaladas en el equipo actual.', signatures: [{ label: 'GetInstalledRuntimes()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/GetInstalledRuntimes_func.html' }),
        globalFunction({ name: 'IsRunningAsSolution', category: 'Proyecto / IDE', summary: 'Indica si la aplicación actual se está ejecutando como solución y no como workspace.', signatures: [{ label: 'IsRunningAsSolution()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/IsRunningAsSolution_func.html' }),
        globalFunction({ name: 'AddToLibraryList', category: 'Proyecto / IDE', summary: 'Añade una biblioteca PBL o PBD a la library list activa de la aplicación.', signatures: [{ label: 'AddToLibraryList(libraryName)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/addtolibrarylist_func.html' }),
        globalFunction({ name: 'GetLibraryList', category: 'Proyecto / IDE', summary: 'Devuelve la library list activa de la aplicación como una cadena separada por comas.', signatures: [{ label: 'GetLibraryList()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/getLibraryList_func.html' }),
        globalFunction({ name: 'SetLibraryList', category: 'Proyecto / IDE', summary: 'Sustituye la library list activa de la aplicación.', signatures: [{ label: 'SetLibraryList(libraryList)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/setLibraryList_func.html' }),
        globalFunction({ name: 'RegistryDelete', category: 'Configuración', summary: 'Elimina una clave o un valor de la rama indicada del registro de Windows.', signatures: [{ label: 'RegistryDelete(key, valueName)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryDelete_func.html' }),
        globalFunction({ name: 'RegistryGet', category: 'Configuración', summary: 'Lee un valor del registro de Windows en una variable PowerBuilder compatible.', signatures: [{ label: 'RegistryGet(key, valueName, valueVariable)' }, { label: 'RegistryGet(key, valueName, valueType, valueVariable)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryGet_func.html' }),
        globalFunction({ name: 'RegistryKeys', category: 'Configuración', summary: 'Obtiene la lista de subclaves inmediatas bajo una clave del registro de Windows.', signatures: [{ label: 'RegistryKeys(key, subkeys)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryKeys_func.html' }),
        globalFunction({ name: 'RegistrySet', category: 'Configuración', summary: 'Escribe o actualiza un valor en el registro de Windows.', signatures: [{ label: 'RegistrySet(key, valueName, valueType, value)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registrySet_func.html' }),
        globalFunction({ name: 'RegistryValues', category: 'Configuración', summary: 'Obtiene la lista de nombres de valor definidos para una clave del registro de Windows.', signatures: [{ label: 'RegistryValues(key, valueNames)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/registryValues_func.html' }),
    globalFunction({ name: 'RelativeDate', category: 'Fecha y hora', summary: 'Devuelve una fecha desplazada un número de días respecto a otra fecha.', signatures: [{ label: 'RelativeDate(date, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/relativeDate_func.html' }),
    globalFunction({ name: 'RelativeTime', category: 'Fecha y hora', summary: 'Devuelve una hora desplazada un número de segundos respecto a otra hora.', signatures: [{ label: 'RelativeTime(time, n)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/relativeTime_func.html' }),
    globalFunction({ name: 'Pi', category: 'Matemáticas', summary: 'Devuelve el valor de la constante pi.', signatures: [{ label: 'Pi()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pi_func.html' }),
    globalFunction({
        name: 'FileReadEx',
        category: 'Archivos',
        summary: 'Lee datos desde un archivo abierto y devuelve la cantidad de bytes leídos.',
        signatures: [
            { label: 'FileReadEx(fileNumber, blob, length?)' },
            { label: 'FileReadEx(fileNumber, string)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileReadEx_func.html',
    }),
    globalFunction({
        name: 'FileWriteEx',
        category: 'Archivos',
        summary: 'Escribe datos en un archivo abierto y devuelve la cantidad de bytes escritos.',
        signatures: [
            { label: 'FileWriteEx(fileNumber, blob)' },
            { label: 'FileWriteEx(fileNumber, string)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileWriteEx_func.html',
    }),
    globalFunction({
        name: 'FileSeek',
        category: 'Archivos',
        summary: 'Reposiciona el puntero de lectura o escritura de un archivo.',
        signatures: [{ label: 'FileSeek(fileNumber, location, origin?)' }],
        manualOverlay: {
            mode: 'override',
            reason: 'Mantiene la firma curada estable usada por signatureHelp y completion, evitando la verbosidad/generated arity drift del rail oficial.',
            evidence: [
                'generated:global-functions:callable:powerscript:global:fileseek:all',
                'manual-core:global-functions:callable:powerscript:global:fileseek:all',
            ],
            reviewedBy: 'B327',
            targetKey: {
                domain: 'global-functions',
                kind: 'callable',
                namespace: 'powerscript',
                invocation: 'global',
                name: 'FileSeek',
            },
        },
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileSeek_func.html',
    }),
    globalFunction({
        name: 'FileSeek64',
        category: 'Archivos',
        summary: 'Reposiciona el puntero de lectura o escritura para archivos grandes.',
        signatures: [{ label: 'FileSeek64(fileNumber, location, origin?)' }],
        manualOverlay: {
            mode: 'override',
            reason: 'Mantiene la firma curada estable usada por signatureHelp y completion, evitando la verbosidad/generated arity drift del rail oficial.',
            evidence: [
                'generated:global-functions:callable:powerscript:global:fileseek64:all',
                'manual-core:global-functions:callable:powerscript:global:fileseek64:all',
            ],
            reviewedBy: 'B327',
            targetKey: {
                domain: 'global-functions',
                kind: 'callable',
                namespace: 'powerscript',
                invocation: 'global',
                name: 'FileSeek64',
            },
        },
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileSeek64_func.html',
    }),
    globalFunction({ name: 'FileLength64', category: 'Archivos', summary: 'Devuelve el tamaño de un archivo como longlong.', signatures: [{ label: 'FileLength64(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileLength64_func.html' }),
    globalFunction({ name: 'FileEncoding', category: 'Archivos', summary: 'Detecta la codificación de texto de un archivo.', signatures: [{ label: 'FileEncoding(filename)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fileEncoding_func.html' }),
    globalFunction({ name: 'PointerX', category: 'Sistema', summary: 'Devuelve la coordenada X actual del puntero del mouse.', signatures: [{ label: 'PointerX()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pointerX_func.html' }),
    globalFunction({ name: 'PointerY', category: 'Sistema', summary: 'Devuelve la coordenada Y actual del puntero del mouse.', signatures: [{ label: 'PointerY()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pointerY_func.html' }),
    globalFunction({
        name: 'SetPointer',
        category: 'Sistema',
        summary: 'Cambia la forma actual del puntero del mouse.',
        signatures: [
            { label: 'SetPointer(pointerStyle)' },
            { label: 'SetPointer(cursorFile, hotspotX?, hotspotY?)' },
        ],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/setPointer_func.html',
    }),
    globalFunction({ name: 'WorkSpaceHeight', category: 'Sistema', summary: 'Devuelve la altura del área de trabajo disponible en pantalla.', signatures: [{ label: 'WorkSpaceHeight()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspaceheight_func.html' }),
    globalFunction({ name: 'WorkSpaceWidth', category: 'Sistema', summary: 'Devuelve el ancho del área de trabajo disponible en pantalla.', signatures: [{ label: 'WorkSpaceWidth()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacewidth_func.html' }),
    globalFunction({ name: 'WorkSpaceX', category: 'Sistema', summary: 'Devuelve la coordenada X de inicio del área de trabajo disponible en pantalla.', signatures: [{ label: 'WorkSpaceX()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacex_func.html' }),
    globalFunction({ name: 'WorkSpaceY', category: 'Sistema', summary: 'Devuelve la coordenada Y de inicio del área de trabajo disponible en pantalla.', signatures: [{ label: 'WorkSpaceY()' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/workspacey_func.html' }),
    globalFunction({ name: 'PixelsToUnits', category: 'Sistema', summary: 'Convierte una medida en píxeles a unidades PowerBuilder.', signatures: [{ label: 'PixelsToUnits(value, axis?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pixelsToUnits_func.html' }),
    globalFunction({ name: 'UnitsToPixels', category: 'Sistema', summary: 'Convierte una medida en unidades PowerBuilder a píxeles.', signatures: [{ label: 'UnitsToPixels(value, axis?)' }], sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/unitsToPixels_func.html' }),
    globalFunction({
        name: 'LenW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Len.',
        signatures: [{ label: 'LenW(value)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Len',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/lenW_func.html',
    }),
    globalFunction({
        name: 'LeftTrimW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de LeftTrim.',
        signatures: [{ label: 'LeftTrimW(string, removeallspaces?)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'LeftTrim',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/leftTrimW_func.html',
    }),
    globalFunction({
        name: 'RightTrimW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de RightTrim.',
        signatures: [{ label: 'RightTrimW(string, removeallspaces?)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'RightTrim',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightTrimW_func.html',
    }),
    globalFunction({
        name: 'LeftW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Left.',
        signatures: [{ label: 'LeftW(value, count)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Left',
    }),
    globalFunction({
        name: 'RightW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Right.',
        signatures: [{ label: 'RightW(value, count)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Right',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/rightW_func.html',
    }),
    globalFunction({
        name: 'MidW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Mid.',
        signatures: [{ label: 'MidW(value, start, length?)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Mid',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/midW_func.html',
    }),
    globalFunction({
        name: 'PosW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Pos.',
        signatures: [{ label: 'PosW(value, target, start?)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Pos',
    }),
    globalFunction({
        name: 'MatchW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Match.',
        signatures: [{ label: 'MatchW(string, textpattern)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Match',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/matchW_func.html',
    }),
    globalFunction({
        name: 'FillW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Fill.',
        signatures: [{ label: 'FillW(chars, n)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Fill',
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/fillW_func.html',
    }),
    globalFunction({
        name: 'ReplaceW',
        category: 'Strings',
        summary: 'Versión heredada Unicode de Replace.',
        signatures: [{ label: 'ReplaceW(value, start, length, replacement)' }],
        obsolete: true,
        obsoleteMessage: 'La familia *W quedó obsoleta en favor de las funciones Unicode estándar.',
        replacement: 'Replace',
    }),
    globalFunction({
        name: 'ChooseColor',
        category: 'Diálogos',
        summary: 'Muestra el cuadro de diálogo estándar para seleccionar un color.',
        signatures: [{ label: 'ChooseColor(color, customColors[])' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/chooseColor_func.html',
    }),
    globalFunction({
        name: 'ShowHelp',
        category: 'Diálogos',
        summary: 'Muestra un tema de ayuda desde el archivo indicado.',
        signatures: [{ label: 'ShowHelp(helpfile, helpcommand, typeid?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/showHelp_func.html',
    }),
    globalFunction({
        name: 'ShowPopupHelp',
        category: 'Diálogos',
        summary: 'Muestra ayuda contextual emergente en una posición de pantalla.',
        signatures: [{ label: 'ShowPopupHelp(helpfile, x, y, contextid)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/showPopupHelp_func.html',
    }),
    globalFunction({
        name: 'OpenURL',
        category: 'Web / HTTP',
        summary: 'Abre una URL usando el manejador registrado en el sistema.',
        signatures: [{ label: 'OpenURL(url)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/OpenURL_func.html',
    }),
    globalFunction({
        name: 'TraceBegin',
        category: 'Sistema',
        summary: 'Marca el inicio de una actividad dentro del rastro de ejecución.',
        signatures: [{ label: 'TraceBegin(identifier)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceBegin_func.html',
    }),
    globalFunction({
        name: 'TraceClose',
        category: 'Sistema',
        summary: 'Cierra el archivo de tracing actualmente abierto.',
        signatures: [{ label: 'TraceClose()' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceClose_func.html',
    }),
    globalFunction({
        name: 'TraceDisableActivity',
        category: 'Sistema',
        summary: 'Deshabilita el tracing para la actividad indicada.',
        signatures: [{ label: 'TraceDisableActivity(activity)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceDisableActivity_func.html',
    }),
    globalFunction({
        name: 'TraceEnableActivity',
        category: 'Sistema',
        summary: 'Habilita el tracing para la actividad indicada.',
        signatures: [{ label: 'TraceEnableActivity(activity)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceEnableActivity_func.html',
    }),
    globalFunction({
        name: 'TraceEnd',
        category: 'Sistema',
        summary: 'Marca el final de una actividad dentro del rastro de ejecución.',
        signatures: [{ label: 'TraceEnd()' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceEnd_func.html',
    }),
    globalFunction({
        name: 'TraceError',
        category: 'Sistema',
        summary: 'Escribe un mensaje de error en el rastro de ejecución.',
        signatures: [{ label: 'TraceError(severity, message)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceError_func.html',
    }),
    globalFunction({
        name: 'TraceOpen',
        category: 'Sistema',
        summary: 'Abre un archivo de tracing y configura el temporizador asociado.',
        signatures: [{ label: 'TraceOpen(filename, timer)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceOpen_func.html',
    }),
    globalFunction({
        name: 'TraceUser',
        category: 'Sistema',
        summary: 'Escribe un mensaje de usuario en el rastro de ejecución.',
        signatures: [{ label: 'TraceUser(info, message)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/traceUser_func.html',
    }),
    globalFunction({
        name: 'PBGetMenuString',
        category: 'Sistema',
        summary: 'Recupera el texto de un elemento de menú nativo.',
        signatures: [{ label: 'PBGetMenuString(hmenu, nPos, caption, nMaxLength)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/pBGetMenuString_func.html',
    }),
    globalFunction({
        name: 'Open',
        category: 'Sistema',
        summary: 'Abre una ventana, con soporte opcional para un owner o contenedor padre.',
        signatures: [{ label: 'Open(windowvar, parent?)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/open_func.html',
    }),
    globalFunction({
        name: 'Close',
        category: 'Sistema',
        summary: 'Cierra la ventana indicada.',
        signatures: [{ label: 'Close(windowname)' }],
        sourceUrl: 'https://docs.appeon.com/pb2025/powerscript_reference/close_func.html',
    }),
];
