import { PbSystemSymbolEntry } from '../../types';
import { objectFunction } from '../common';
import {
    EVENT_CAPABLE_OBJECT_TYPES,
    FOCUSABLE_OBJECT_TYPES,
    REDRAWABLE_OBJECT_TYPES,
    TEXT_OBJECT_TYPES,
    VISUAL_OBJECT_TYPES,
} from '../ownerTypes/visualOwnerTypes';

export const PB_MANUAL_CORE_OBJECT_FUNCTION_CATEGORIES = [
    'Interaction',
    'Visual',
    'Layout',
    'Context',
    'Text',
    'Events',
] as const;

const EDITABLE_TEXT_OBJECT_TYPES = [
    'singlelineedit',
    'editmask',
    'multilineedit',
] as const;

const MULTILINE_TEXT_OBJECT_TYPES = [
    'editmask',
    'multilineedit',
] as const;

type ObjectFunctionCategory = (typeof PB_MANUAL_CORE_OBJECT_FUNCTION_CATEGORIES)[number];

type ObjectFunctionDescriptor = {
    name: string;
    category: ObjectFunctionCategory;
    summary: string;
    signature: string;
    appliesTo: readonly string[];
    ownerTypes: readonly string[];
    obsolete?: boolean;
    obsoleteMessage?: string;
    replacement?: string;
    sourceUrl: string;
};

const WINDOW_CONTROL_ONLY_OWNER_TYPES = ['window'] as const;
const WINDOW_CONTROL_ONLY_APPLIES_TO = ['Window control'] as const;
const WINDOW_CONTROL_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html';

const LISTBOX_OWNER_TYPES = ['listbox'] as const;
const LISTBOX_APPLIES_TO = ['ListBox control'] as const;
const LISTBOX_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/ListBox_control.html';

const TAB_OWNER_TYPES = ['tab'] as const;
const TAB_APPLIES_TO = ['Tab control'] as const;
const TAB_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/Tab_control.html';

const LISTVIEW_OWNER_TYPES = ['listview'] as const;
const LISTVIEW_APPLIES_TO = ['ListView control'] as const;
const LISTVIEW_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/ListView_control.html';

const TREEVIEW_OWNER_TYPES = ['treeview'] as const;
const TREEVIEW_APPLIES_TO = ['TreeView control'] as const;
const TREEVIEW_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/TreeView_control.html';

function defineObjectFunctionEntries(
    descriptors: readonly ObjectFunctionDescriptor[],
): readonly PbSystemSymbolEntry[] {
    return descriptors.map(descriptor => objectFunction({
        name: descriptor.name,
        category: descriptor.category,
        summary: descriptor.summary,
        signatures: [{ label: descriptor.signature }],
        appliesTo: descriptor.appliesTo,
        ownerTypes: descriptor.ownerTypes,
        obsolete: descriptor.obsolete,
        obsoleteMessage: descriptor.obsoleteMessage,
        replacement: descriptor.replacement,
        sourceUrl: descriptor.sourceUrl,
    }));
}

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06A = defineObjectFunctionEntries([
    {
        name: 'ArrangeSheets',
        category: 'Visual',
        summary: 'Rearranges the open MDI sheets in the current window.',
        signature: 'ArrangeSheets(style?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'ChangeMenu',
        category: 'Context',
        summary: 'Replaces the active menu associated with the window.',
        signature: 'ChangeMenu(menu)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'CloseUserObject',
        category: 'Visual',
        summary: 'Closes a dynamically opened user object in the window.',
        signature: 'CloseUserObject(control)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetActiveSheet',
        category: 'Context',
        summary: 'Returns the active MDI sheet of the window.',
        signature: 'GetActiveSheet()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetContextService',
        category: 'Context',
        summary: 'Creates a context service instance for the window.',
        signature: 'GetContextService(...)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetFirstSheet',
        category: 'Context',
        summary: 'Returns the first open sheet in the MDI window.',
        signature: 'GetFirstSheet()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetNextSheet',
        category: 'Context',
        summary: 'Returns the next open sheet relative to a given sheet.',
        signature: 'GetNextSheet(sheet)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenSheet',
        category: 'Visual',
        summary: 'Opens a user object as a sheet of the window.',
        signature: 'OpenSheet(uo, parent, position?, arrangeopen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenSheetWithParm',
        category: 'Visual',
        summary: 'Opens a sheet and exposes a parameter in the Message object.',
        signature: 'OpenSheetWithParm(uo, parent, parm, position?, arrangeopen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenUserObject',
        category: 'Visual',
        summary: 'Dynamically opens a user object associated with the window.',
        signature: 'OpenUserObject(class, parent)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06B = defineObjectFunctionEntries([
    {
        name: 'OpenUserObjectWithParm',
        category: 'Visual',
        summary: 'Opens a dynamic user object and passes an initial parameter.',
        signature: 'OpenUserObjectWithParm(class, parent, parm)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetToolbar',
        category: 'Context',
        summary: 'Obtains a reference to a registered toolbar in the window.',
        signature: 'GetToolbar(index)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetToolbarPos',
        category: 'Layout',
        summary: 'Returns the current position of a window toolbar.',
        signature: 'GetToolbarPos(index)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'IsMaximizeAllTabbedSheetsEnabled',
        category: 'Context',
        summary: 'Indicates if the window maximizes all tabbed sheets.',
        signature: 'IsMaximizeAllTabbedSheetsEnabled()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'IsTabbedViewEnabled',
        category: 'Context',
        summary: 'Indicates if the window uses tabbed view for its sheets.',
        signature: 'IsTabbedViewEnabled()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetMicroHelp',
        category: 'Visual',
        summary: 'Updates the microhelp text displayed by the window.',
        signature: 'SetMicroHelp(text)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetSheetID',
        category: 'Context',
        summary: 'Assigns a logical identifier to an open sheet.',
        signature: 'SetSheetID(sheet, id)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetToolbar',
        category: 'Visual',
        summary: 'Shows or hides a registered toolbar in the window.',
        signature: 'SetToolbar(index, visible)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetToolbarPos',
        category: 'Layout',
        summary: 'Relocates a window toolbar to the specified position.',
        signature: 'SetToolbarPos(index, position)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SaveDockingState',
        category: 'Context',
        summary: 'Persists the current docked layout of the window to a file.',
        signature: 'SaveDockingState(file)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06C = defineObjectFunctionEntries([
    {
        name: 'AddItem',
        category: 'Interaction',
        summary: 'Adds an item to the end of the ListBox.',
        signature: 'AddItem(text)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interaction',
        summary: 'Deletes the specified item from the ListBox.',
        signature: 'DeleteItem(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DirList',
        category: 'Interaction',
        summary: 'Loads files matching a pattern into the ListBox.',
        signature: 'DirList(path, filetype)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DirSelect',
        category: 'Interaction',
        summary: 'Retrieves the current selection of the ListBox into a variable.',
        signature: 'DirSelect(pathvar)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Drag',
        category: 'Interaction',
        summary: 'Starts or ends dragging of the ListBox control.',
        signature: 'Drag(begin)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'FindItem',
        category: 'Interaction',
        summary: 'Finds the next item that starts with the specified text.',
        signature: 'FindItem(text, start)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'GetContextService',
        category: 'Context',
        summary: 'Creates a context service instance for the ListBox.',
        signature: 'GetContextService(...)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interaction',
        summary: 'Inserts an item before the specified index.',
        signature: 'InsertItem(index, text)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Prints the visible content of the ListBox.',
        signature: 'Print()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06D = defineObjectFunctionEntries([
    {
        name: 'Reset',
        category: 'Interaction',
        summary: 'Removes all items from the ListBox.',
        signature: 'Reset()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the ListBox control.',
        signature: 'ClassName()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns the parent object of the ListBox.',
        signature: 'GetParent()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal position of the pointer relative to the ListBox.',
        signature: 'PointerX()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical position of the pointer relative to the ListBox.',
        signature: 'PointerY()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectedIndex',
        category: 'Interaction',
        summary: 'Returns the index of the first selected item.',
        signature: 'SelectedIndex()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectedItem',
        category: 'Text',
        summary: 'Returns the text of the first selected item.',
        signature: 'SelectedItem()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectItem',
        category: 'Interaction',
        summary: 'Selects an item by text or index.',
        signature: 'SelectItem(item, select?)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Changes the Z-order of the ListBox within the window.',
        signature: 'SetPosition(position)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06E = defineObjectFunctionEntries([
    {
        name: 'SetRedraw',
        category: 'Visual',
        summary: 'Suspends or reactivates automatic redrawing of the ListBox.',
        signature: 'SetRedraw(redraw)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetState',
        category: 'Interaction',
        summary: 'Changes the selected state of a multi-selection item.',
        signature: 'SetState(index, selected)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetTop',
        category: 'Layout',
        summary: 'Scrolls the ListBox to show the specified item at the top.',
        signature: 'SetTop(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'State',
        category: 'Interaction',
        summary: 'Indicates if a specific item is selected.',
        signature: 'State(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Text',
        category: 'Text',
        summary: 'Returns the text of the item specified by index.',
        signature: 'Text(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Top',
        category: 'Layout',
        summary: 'Returns the index of the item visible at the top.',
        signature: 'Top()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TotalItems',
        category: 'Interaction',
        summary: 'Returns the total number of items in the ListBox.',
        signature: 'TotalItems()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TotalSelected',
        category: 'Interaction',
        summary: 'Returns how many items are selected.',
        signature: 'TotalSelected()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the ListBox.',
        signature: 'TypeOf()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06F = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the Tab control.',
        signature: 'ClassName()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'CloseTab',
        category: 'Visual',
        summary: 'Closes a dynamically opened page within the Tab.',
        signature: 'CloseTab(index)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'Drag',
        category: 'Interaction',
        summary: 'Starts or ends dragging of the Tab control.',
        signature: 'Drag(begin)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'GetContextService',
        category: 'Context',
        summary: 'Creates a context service instance for the Tab.',
        signature: 'GetContextService(...)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns the parent object of the Tab.',
        signature: 'GetParent()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'MoveTab',
        category: 'Layout',
        summary: 'Reorders a tab to a new position.',
        signature: 'MoveTab(from, to)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'OpenTab',
        category: 'Visual',
        summary: 'Opens a user object as a page of the Tab control.',
        signature: 'OpenTab(uo, index?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'OpenTabWithParm',
        category: 'Visual',
        summary: 'Opens a Tab page and passes an initial parameter.',
        signature: 'OpenTabWithParm(uo, parm, index?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06G = defineObjectFunctionEntries([
    {
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal position of the pointer relative to the Tab.',
        signature: 'PointerX()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical position of the pointer relative to the Tab.',
        signature: 'PointerY()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Prints the current content of the Tab control.',
        signature: 'Print()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'SelectTab',
        category: 'Interaction',
        summary: 'Programmatically selects a Tab page.',
        signature: 'SelectTab(index)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Changes the Z-order of the Tab within the window.',
        signature: 'SetPosition(position)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TabPostEvent',
        category: 'Events',
        summary: 'Posts an event to the queues of all Tab pages.',
        signature: 'TabPostEvent(eventname, wordparm?, longparm?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TabTriggerEvent',
        category: 'Events',
        summary: 'Triggers an event on all Tab pages.',
        signature: 'TabTriggerEvent(eventname, wordparm?, longparm?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the Tab control.',
        signature: 'TypeOf()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06H = defineObjectFunctionEntries([
    {
        name: 'AddColumn',
        category: 'Layout',
        summary: 'Adds a column to the report view of the ListView.',
        signature: 'AddColumn(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddItem',
        category: 'Interaction',
        summary: 'Adds an item to the ListView.',
        signature: 'AddItem(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddLargePicture',
        category: 'Visual',
        summary: 'Adds an image to the large icons list of the ListView.',
        signature: 'AddLargePicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddSmallPicture',
        category: 'Visual',
        summary: 'Adds an image to the small icons list of the ListView.',
        signature: 'AddSmallPicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddStatePicture',
        category: 'Visual',
        summary: 'Adds an image to the state list of the ListView.',
        signature: 'AddStatePicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'Arrange',
        category: 'Layout',
        summary: 'Rearranges items in the ListView icon view.',
        signature: 'Arrange(style?)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the ListView control.',
        signature: 'ClassName()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetContextService',
        category: 'Context',
        summary: 'Creates a context service instance for the ListView.',
        signature: 'GetContextService(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns the parent object of the ListView.',
        signature: 'GetParent()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06I = defineObjectFunctionEntries([
    {
        name: 'DeleteColumn',
        category: 'Layout',
        summary: 'Deletes a column from the ListView.',
        signature: 'DeleteColumn(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteColumns',
        category: 'Layout',
        summary: 'Deletes all columns from the ListView.',
        signature: 'DeleteColumns()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interaction',
        summary: 'Deletes an item from the ListView.',
        signature: 'DeleteItem(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteItems',
        category: 'Interaction',
        summary: 'Deletes all items from the ListView.',
        signature: 'DeleteItems()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'EditLabel',
        category: 'Text',
        summary: 'Starts label editing for an item.',
        signature: 'EditLabel(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'FindItem',
        category: 'Interaction',
        summary: 'Finds an item based on the specified criteria.',
        signature: 'FindItem(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetColumn',
        category: 'Layout',
        summary: 'Retrieves the properties of a column.',
        signature: 'GetColumn(index, column)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetItem',
        category: 'Interaction',
        summary: 'Retrieves the properties of an item.',
        signature: 'GetItem(index, item)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06J = defineObjectFunctionEntries([
    {
        name: 'GetOrigin',
        category: 'Layout',
        summary: 'Obtains the coordinates of the visible origin of the ListView.',
        signature: 'GetOrigin(x, y)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'InsertColumn',
        category: 'Layout',
        summary: 'Inserts a column at the specified position.',
        signature: 'InsertColumn(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interaction',
        summary: 'Inserts an item at the specified position.',
        signature: 'InsertItem(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal position of the pointer relative to the ListView.',
        signature: 'PointerX()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical position of the pointer relative to the ListView.',
        signature: 'PointerY()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetColumn',
        category: 'Layout',
        summary: 'Updates the properties of a ListView column.',
        signature: 'SetColumn(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetItem',
        category: 'Interaction',
        summary: 'Updates the values of a ListView item.',
        signature: 'SetItem(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetOverlayPicture',
        category: 'Visual',
        summary: 'Associates an overlay image with a ListView image index.',
        signature: 'SetOverlayPicture(pictureindex, overlayindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06K = defineObjectFunctionEntries([
    {
        name: 'AddPicture',
        category: 'Visual',
        summary: 'Adds an image to the main list of the TreeView.',
        signature: 'AddPicture(picture)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'AddStatePicture',
        category: 'Visual',
        summary: 'Adds an image to the state list of the TreeView.',
        signature: 'AddStatePicture(picture)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'CollapseItem',
        category: 'Interaction',
        summary: 'Collapses the specified item in the TreeView.',
        signature: 'CollapseItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interaction',
        summary: 'Deletes an item from the TreeView and all its children.',
        signature: 'DeleteItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Drag',
        category: 'Interaction',
        summary: 'Starts or ends dragging of a TreeView item.',
        signature: 'Drag(begin)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'EditLabel',
        category: 'Text',
        summary: 'Starts label editing for a TreeView item.',
        signature: 'EditLabel(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'ExpandAll',
        category: 'Interaction',
        summary: 'Expands an item and all its descendant levels.',
        signature: 'ExpandAll(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'ExpandItem',
        category: 'Interaction',
        summary: 'Expands the specified item in the TreeView.',
        signature: 'ExpandItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06L = defineObjectFunctionEntries([
    {
        name: 'FindItem',
        category: 'Interaction',
        summary: 'Finds a TreeView item based on search criteria.',
        signature: 'FindItem(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetContextService',
        category: 'Context',
        summary: 'Creates a context service instance for the TreeView.',
        signature: 'GetContextService(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetItem',
        category: 'Context',
        summary: 'Retrieves information from a TreeView item.',
        signature: 'GetItem(handle, ...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetItemAtPointer',
        category: 'Interaction',
        summary: 'Gets the item located under the pointer.',
        signature: 'GetItemAtPointer()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns the parent object of the TreeView.',
        signature: 'GetParent()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interaction',
        summary: 'Inserts an item at a specific position and level.',
        signature: 'InsertItem(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItemFirst',
        category: 'Interaction',
        summary: 'Inserts an item as the first child of the specified level.',
        signature: 'InsertItemFirst(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItemLast',
        category: 'Interaction',
        summary: 'Inserts an item as the last child of the specified level.',
        signature: 'InsertItemLast(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06M = defineObjectFunctionEntries([
    {
        name: 'InsertItemSort',
        category: 'Interaction',
        summary: 'Inserts an item respecting the current alphabetical sorting.',
        signature: 'InsertItemSort(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal position of the pointer relative to the TreeView.',
        signature: 'PointerX()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical position of the pointer relative to the TreeView.',
        signature: 'PointerY()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SelectItem',
        category: 'Interaction',
        summary: 'Programmatically selects a TreeView item.',
        signature: 'SelectItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetDropHighlight',
        category: 'Visual',
        summary: 'Marks an item as the visual target of a DragDrop operation.',
        signature: 'SetDropHighlight(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetFirstVisible',
        category: 'Layout',
        summary: 'Makes an item the first visible item in the TreeView.',
        signature: 'SetFirstVisible(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetItem',
        category: 'Interaction',
        summary: 'Updates information associated with a TreeView item.',
        signature: 'SetItem(handle, ...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetLevelPictures',
        category: 'Visual',
        summary: 'Associates common images with all items of a level.',
        signature: 'SetLevelPictures(level, pictureindex, selectedindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09A = defineObjectFunctionEntries([
    {
        name: 'DeleteLargePicture',
        category: 'Visual',
        summary: 'Deletes a specific image from the ListView large icons list.',
        signature: 'DeleteLargePicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteLargePictures',
        category: 'Visual',
        summary: 'Deletes all images from the ListView large icons list.',
        signature: 'DeleteLargePictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteSmallPicture',
        category: 'Visual',
        summary: 'Deletes a specific image from the ListView small icons list.',
        signature: 'DeleteSmallPicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteSmallPictures',
        category: 'Visual',
        summary: 'Deletes all images from the ListView small icons list.',
        signature: 'DeleteSmallPictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteStatePicture',
        category: 'Visual',
        summary: 'Deletes a specific image from the ListView state list.',
        signature: 'DeleteStatePicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteStatePictures',
        category: 'Visual',
        summary: 'Deletes all images from the ListView state list.',
        signature: 'DeleteStatePictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'Sort',
        category: 'Layout',
        summary: 'Sorts ListView items based on the configured sorting mode.',
        signature: 'Sort()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalColumns',
        category: 'Context',
        summary: 'Returns the number of columns defined in the ListView report view.',
        signature: 'TotalColumns()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09B = defineObjectFunctionEntries([
    {
        name: 'Drag',
        category: 'Interaction',
        summary: 'Starts or ends programmatic dragging of a ListView item.',
        signature: 'Drag(begin)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SelectedIndex',
        category: 'Interaction',
        summary: 'Returns the index of the currently selected item in the ListView.',
        signature: 'SelectedIndex()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalItems',
        category: 'Interaction',
        summary: 'Returns the total number of items loaded in the ListView.',
        signature: 'TotalItems()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalSelected',
        category: 'Interaction',
        summary: 'Returns how many items are selected in the ListView.',
        signature: 'TotalSelected()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09C = defineObjectFunctionEntries([
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Includes the visible part of the ListView in the active print job.',
        signature: 'Print()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Changes the Z-position of the ListView within the container window.',
        signature: 'SetPosition(position)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the ListView control.',
        signature: 'TypeOf()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09D = defineObjectFunctionEntries([
    {
        name: 'DeletePicture',
        category: 'Visual',
        summary: 'Deletes a specific image from the TreeView main list.',
        signature: 'DeletePicture(pictureindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeletePictures',
        category: 'Visual',
        summary: 'Deletes all images from the TreeView main list.',
        signature: 'DeletePictures()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteStatePicture',
        category: 'Visual',
        summary: 'Deletes a specific image from the TreeView state list.',
        signature: 'DeleteStatePicture(pictureindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteStatePictures',
        category: 'Visual',
        summary: 'Deletes all images from the TreeView state list.',
        signature: 'DeleteStatePictures()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09E = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the TreeView control.',
        signature: 'ClassName()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Includes the visible part of the TreeView in the active print job.',
        signature: 'Print()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Changes the Z-position of the TreeView within the container window.',
        signature: 'SetPosition(position)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the TreeView control.',
        signature: 'TypeOf()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09F = defineObjectFunctionEntries([
    {
        name: 'SetOverlayPicture',
        category: 'Visual',
        summary: 'Associates an overlay image with a TreeView image index.',
        signature: 'SetOverlayPicture(pictureindex, overlayindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Sort',
        category: 'Layout',
        summary: 'Sorts the direct children of the specified item according to SortType or alphabetically.',
        signature: 'Sort(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SortAll',
        category: 'Layout',
        summary: 'Sorts the specified item and all its descendant levels according to SortType or alphabetically.',
        signature: 'SortAll(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09G = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the window at runtime.',
        signature: 'ClassName()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Changes the Z-position of the window within the application visual order.',
        signature: 'SetPosition(position)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09H = defineObjectFunctionEntries([
    {
        name: 'CommitDocking',
        category: 'Visual',
        summary: 'Applies and makes visible the persisted docking layout after opening all necessary sheets.',
        signature: 'CommitDocking()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09I = defineObjectFunctionEntries([
    {
        name: 'LoadDockingState',
        category: 'Context',
        summary: 'Loads the persisted docking state with saved sheet classes and identifiers.',
        signature: 'LoadDockingState(file, typeNames, ids)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09J = defineObjectFunctionEntries([
    {
        name: 'OpenSheetAsDocument',
        category: 'Visual',
        summary: 'Opens a sheet as a tabbed document within the MDI frame with docking.',
        signature: 'OpenSheetAsDocument(uo, parent, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09K = defineObjectFunctionEntries([
    {
        name: 'OpenSheetDocked',
        category: 'Visual',
        summary: 'Opens a docked sheet in a specific position of the MDI frame.',
        signature: 'OpenSheetDocked(uo, parent, position, size?, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09L = defineObjectFunctionEntries([
    {
        name: 'OpenSheetFromDockingState',
        category: 'Visual',
        summary: 'Opens persisted sheets from a previously stored docking state.',
        signature: 'OpenSheetFromDockingState(file, parent)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09M = defineObjectFunctionEntries([
    {
        name: 'OpenSheetInTabGroup',
        category: 'Visual',
        summary: 'Opens a sheet in a tab group of the MDI frame with docking.',
        signature: 'OpenSheetInTabGroup(uo, parent, tabgroup, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09N = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmAsDocument',
        category: 'Visual',
        summary: 'Opens a sheet as a tabbed document and exposes an initial parameter in Message.',
        signature: 'OpenSheetWithParmAsDocument(uo, parent, parm, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09O = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmDocked',
        category: 'Visual',
        summary: 'Opens a docked sheet in a specific position and exposes an initial parameter in Message.',
        signature: 'OpenSheetWithParmDocked(uo, parent, parm, position, size?, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09P = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmFromDockingState',
        category: 'Visual',
        summary: 'Opens persisted sheets from a docking state and exposes an initial parameter in Message.',
        signature: 'OpenSheetWithParmFromDockingState(file, parent, parm)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09Q = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmInTabGroup',
        category: 'Visual',
        summary: 'Opens a sheet in a tab group of the MDI frame and exposes an initial parameter in Message.',
        signature: 'OpenSheetWithParmInTabGroup(uo, parent, parm, tabgroup, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Dockable windows are obsolete since PowerBuilder 2019 R2 and no longer receive technical support.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09R = defineObjectFunctionEntries([
    {
        name: 'CloseChannel',
        category: 'Context',
        summary: 'Closes a DDE channel previously opened by the window.',
        signature: 'CloseChannel(channel)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'ExecRemote',
        category: 'Context',
        summary: 'Requests a DDE server application to execute a remote command.',
        signature: 'ExecRemote(channel, command)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetCommandDDE',
        category: 'Context',
        summary: 'Obtains the command received by the window when acting as a DDE server.',
        signature: 'GetCommandDDE(command)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetCommandDDEOrigin',
        category: 'Context',
        summary: 'Obtains the origin of the command received when the window acts as a DDE server.',
        signature: 'GetCommandDDEOrigin(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetDataDDE',
        category: 'Text',
        summary: 'Obtains data sent by another DDE application and copies it to a destination variable.',
        signature: 'GetDataDDE(data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetDataDDEOrigin',
        category: 'Context',
        summary: 'Retrieves DDE identifiers associated with the origin of the received data.',
        signature: 'GetDataDDEOrigin(application, topic, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetRemote',
        category: 'Text',
        summary: 'Requests data from a DDE server application and stores it in a local variable.',
        signature: 'GetRemote(channel, item, data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenChannel',
        category: 'Context',
        summary: 'Opens a channel to a DDE server application for an application-topic pair.',
        signature: 'OpenChannel(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'RespondRemote',
        category: 'Context',
        summary: 'Indicates if the command or data received from a remote DDE application were accepted.',
        signature: 'RespondRemote(accepted)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetDataDDE',
        category: 'Text',
        summary: 'Sends data to a DDE client application when the window acts as a server.',
        signature: 'SetDataDDE(data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetRemote',
        category: 'Text',
        summary: 'Requests a DDE server application to accept and save data in a remote location.',
        signature: 'SetRemote(channel, item, data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StartHotLink',
        category: 'Context',
        summary: 'Establishes a DDE hot link to receive immediate changes from a remote item.',
        signature: 'StartHotLink(channel, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StartServerDDE',
        category: 'Context',
        summary: 'Registers the current application as a DDE server for the specified combination.',
        signature: 'StartServerDDE(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StopHotLink',
        category: 'Context',
        summary: 'Terminates a previously established DDE hot link with a remote item.',
        signature: 'StopHotLink(channel, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StopServerDDE',
        category: 'Context',
        summary: 'Stops the application from acting as a DDE server.',
        signature: 'StopServerDDE()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'DDE function is obsolete in PowerBuilder; maintained only for legacy compatibility.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

export const PB_MANUAL_CORE_OBJECT_FUNCTIONS: readonly PbSystemSymbolEntry[] = [
    objectFunction({
        name: 'SetFocus',
        category: 'Interaction',
        summary: 'Transfers input focus to the visual object.',
        signatures: [{ label: 'SetFocus()' }],
        appliesTo: ['compatible visual controls'],
        ownerTypes: FOCUSABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Show',
        category: 'Visual',
        summary: 'Shows a hidden visual object.',
        signatures: [{ label: 'Show()' }],
        appliesTo: ['visual objects'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Hide',
        category: 'Visual',
        summary: 'Hides a visual object without destroying it.',
        signatures: [{ label: 'Hide()' }],
        appliesTo: ['visual objects'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Move',
        category: 'Layout',
        summary: 'Relocates the visual object to client coordinates.',
        signatures: [{ label: 'Move(x, y)' }],
        appliesTo: ['visual objects'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Resize',
        category: 'Layout',
        summary: 'Changes the size of the visual object.',
        signatures: [{ label: 'Resize(width, height)' }],
        appliesTo: ['visual objects'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'SetRedraw',
        category: 'Visual',
        summary: 'Temporarily suspends or reactivates redrawing of the visual object.',
        signatures: [{ label: 'SetRedraw(redraw)' }],
        appliesTo: ['windows and controls with explicit redrawing'],
        ownerTypes: REDRAWABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'GetText',
        category: 'Text',
        summary: 'Returns the current text of the control.',
        signatures: [{ label: 'GetText()' }],
        appliesTo: ['edit and text controls'],
        ownerTypes: TEXT_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'SetText',
        category: 'Text',
        summary: 'Replaces the text displayed by the control.',
        signatures: [{ label: 'SetText(text)' }],
        appliesTo: ['edit and text controls'],
        ownerTypes: TEXT_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'CanUndo',
        category: 'Text',
        summary: 'Indicates if the control can undo the last edit made.',
        signatures: [{ label: 'CanUndo()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Clear',
        category: 'Text',
        summary: 'Clears the selected text without copying it to the clipboard.',
        signatures: [{ label: 'Clear()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Copy',
        category: 'Text',
        summary: 'Copies the selected text to the clipboard without deleting it.',
        signatures: [{ label: 'Copy()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Cut',
        category: 'Text',
        summary: 'Cuts the selected text and sends it to the clipboard.',
        signatures: [{ label: 'Cut()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Paste',
        category: 'Text',
        summary: 'Inserts the clipboard content at the current control position.',
        signatures: [{ label: 'Paste()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'ReplaceText',
        category: 'Text',
        summary: 'Replaces the selected text or inserts the specified string at the current position.',
        signatures: [{
            label: 'ReplaceText(text)',
            parameters: [
                { label: 'text', documentation: 'Text to be inserted or replaced over the current selection.' },
            ],
        }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectText',
        category: 'Text',
        summary: 'Selects a portion of text based on a starting position and length.',
        signatures: [{
            label: 'SelectText(start, length)',
            parameters: [
                { label: 'start', documentation: 'Starting position of the text to be selected.' },
                { label: 'length', documentation: 'Number of characters to be selected.' },
            ],
        }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Undo',
        category: 'Text',
        summary: 'Undoes the last edit operation performed on the control.',
        signatures: [{ label: 'Undo()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'ClassName',
        category: 'Context',
        summary: 'Returns the name assigned to the control at runtime.',
        signatures: [{ label: 'ClassName()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns a reference to the parent object containing the control.',
        signatures: [{ label: 'GetParent()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal distance of the pointer from the left edge of the control.',
        signatures: [{ label: 'PointerX()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical distance of the pointer from the top edge of the control.',
        signatures: [{ label: 'PointerY()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Position',
        category: 'Text',
        summary: 'Returns the current position of the insertion point within the control.',
        signatures: [{ label: 'Position()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedLength',
        category: 'Text',
        summary: 'Returns the length of the currently selected text.',
        signatures: [{ label: 'SelectedLength()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedStart',
        category: 'Text',
        summary: 'Returns the starting position of the currently selected text.',
        signatures: [{ label: 'SelectedStart()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedText',
        category: 'Text',
        summary: 'Returns the currently selected text in the control.',
        signatures: [{ label: 'SelectedText()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the current control.',
        signatures: [{ label: 'TypeOf()' }],
        appliesTo: ['editable text controls'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'LineCount',
        category: 'Text',
        summary: 'Returns the total number of lines available in the control.',
        signatures: [{ label: 'LineCount()' }],
        appliesTo: ['editable controls with line support'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'LineLength',
        category: 'Text',
        summary: 'Returns the length of the line where the insertion point is located.',
        signatures: [{ label: 'LineLength()' }],
        appliesTo: ['editable controls with line support'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'Scroll',
        category: 'Text',
        summary: 'Scrolls the control content up or down by the specified number of lines.',
        signatures: [{
            label: 'Scroll(lines)',
            parameters: [
                { label: 'lines', documentation: 'Number of lines to scroll; positive scrolls down, negative scrolls up.' },
            ],
        }],
        appliesTo: ['editable controls with line support'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedLine',
        category: 'Text',
        summary: 'Returns the number of the line where the insertion point is located.',
        signatures: [{ label: 'SelectedLine()' }],
        appliesTo: ['editable controls with line support'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'TextLine',
        category: 'Text',
        summary: 'Returns the full text of the current line in the control.',
        signatures: [{ label: 'TextLine()' }],
        appliesTo: ['editable controls with line support'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'GetParent',
        category: 'Context',
        summary: 'Returns a reference to the parent object containing the window.',
        signatures: [{ label: 'GetParent()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'ParentWindow',
        category: 'Context',
        summary: 'Returns the parent window of the current window if one exists.',
        signatures: [{ label: 'ParentWindow()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PointerX',
        category: 'Interaction',
        summary: 'Returns the horizontal distance of the pointer from the left edge of the screen.',
        signatures: [{ label: 'PointerX()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PointerY',
        category: 'Interaction',
        summary: 'Returns the vertical distance of the pointer from the top edge of the screen.',
        signatures: [{ label: 'PointerY()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'Print',
        category: 'Visual',
        summary: 'Sends the current window to print with the active configuration.',
        signatures: [{ label: 'Print()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'TypeOf',
        category: 'Context',
        summary: 'Returns the runtime type of the current window.',
        signatures: [{ label: 'TypeOf()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceHeight',
        category: 'Layout',
        summary: 'Returns the usable workspace height within the window.',
        signatures: [{ label: 'WorkSpaceHeight()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceWidth',
        category: 'Layout',
        summary: 'Returns the usable workspace width within the window.',
        signatures: [{ label: 'WorkSpaceWidth()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceX',
        category: 'Layout',
        summary: 'Returns the X-coordinate of the left edge of the window workspace.',
        signatures: [{ label: 'WorkSpaceX()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceY',
        category: 'Layout',
        summary: 'Returns the Y-coordinate of the top edge of the window workspace.',
        signatures: [{ label: 'WorkSpaceY()' }],
        appliesTo: ['windows'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PostEvent',
        category: 'Events',
        summary: 'Posts an event to be processed asynchronously on the object.',
        signatures: [{ label: 'PostEvent(eventname, wordparm?, longparm?)' }],
        appliesTo: ['PowerBuilder objects with scriptable events'],
        ownerTypes: EVENT_CAPABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'TriggerEvent',
        category: 'Events',
        summary: 'Immediately triggers an event on the current or specified object.',
        signatures: [{ label: 'TriggerEvent(eventname, wordparm?, longparm?)' }],
        appliesTo: ['PowerBuilder objects with scriptable events'],
        ownerTypes: EVENT_CAPABLE_OBJECT_TYPES,
    }),
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06A,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06B,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06C,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06D,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06E,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06F,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06G,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06H,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06I,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06J,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06K,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06L,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06M,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09A,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09B,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09C,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09D,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09E,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09F,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09G,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09H,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09I,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09J,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09K,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09L,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09M,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09N,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09O,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09P,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09Q,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09R,
];
