import { PbSystemSymbolEntry } from '../types';
import {
    EVENT_CAPABLE_OBJECT_TYPES,
    FOCUSABLE_OBJECT_TYPES,
    objectFunction,
    REDRAWABLE_OBJECT_TYPES,
    TEXT_OBJECT_TYPES,
    VISUAL_OBJECT_TYPES,
} from './common';

export const PB_MANUAL_CORE_OBJECT_FUNCTION_CATEGORIES = [
    'Interacción',
    'Visual',
    'Layout',
    'Contexto',
    'Texto',
    'Eventos',
] as const;

const EDITABLE_TEXT_OBJECT_TYPES = [
    'singlelineedit',
    'editmask',
    'multilineedit',
] as const;

const MULTILINE_TEXT_OBJECT_TYPES = [
    'editmask',
    'multilineedit',
] as const;

type ObjectFunctionCategory = (typeof PB_MANUAL_CORE_OBJECT_FUNCTION_CATEGORIES)[number];

type ObjectFunctionDescriptor = {
    name: string;
    category: ObjectFunctionCategory;
    summary: string;
    signature: string;
    appliesTo: readonly string[];
    ownerTypes: readonly string[];
    obsolete?: boolean;
    obsoleteMessage?: string;
    replacement?: string;
    sourceUrl: string;
};

const WINDOW_CONTROL_ONLY_OWNER_TYPES = ['window'] as const;
const WINDOW_CONTROL_ONLY_APPLIES_TO = ['Window control'] as const;
const WINDOW_CONTROL_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html';

const LISTBOX_OWNER_TYPES = ['listbox'] as const;
const LISTBOX_APPLIES_TO = ['ListBox control'] as const;
const LISTBOX_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/ListBox_control.html';

const TAB_OWNER_TYPES = ['tab'] as const;
const TAB_APPLIES_TO = ['Tab control'] as const;
const TAB_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/Tab_control.html';

const LISTVIEW_OWNER_TYPES = ['listview'] as const;
const LISTVIEW_APPLIES_TO = ['ListView control'] as const;
const LISTVIEW_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/ListView_control.html';

const TREEVIEW_OWNER_TYPES = ['treeview'] as const;
const TREEVIEW_APPLIES_TO = ['TreeView control'] as const;
const TREEVIEW_URL = 'https://docs.appeon.com/pb2025/objects_and_controls/TreeView_control.html';

function defineObjectFunctionEntries(
    descriptors: readonly ObjectFunctionDescriptor[],
): readonly PbSystemSymbolEntry[] {
    return descriptors.map(descriptor => objectFunction({
        name: descriptor.name,
        category: descriptor.category,
        summary: descriptor.summary,
        signatures: [{ label: descriptor.signature }],
        appliesTo: descriptor.appliesTo,
        ownerTypes: descriptor.ownerTypes,
        obsolete: descriptor.obsolete,
        obsoleteMessage: descriptor.obsoleteMessage,
        replacement: descriptor.replacement,
        sourceUrl: descriptor.sourceUrl,
    }));
}

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06A = defineObjectFunctionEntries([
    {
        name: 'ArrangeSheets',
        category: 'Visual',
        summary: 'Reorganiza las hojas MDI abiertas en la ventana actual.',
        signature: 'ArrangeSheets(style?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'ChangeMenu',
        category: 'Contexto',
        summary: 'Sustituye el menú activo asociado a la ventana.',
        signature: 'ChangeMenu(menu)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'CloseUserObject',
        category: 'Visual',
        summary: 'Cierra un user object abierto dinámicamente en la ventana.',
        signature: 'CloseUserObject(control)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetActiveSheet',
        category: 'Contexto',
        summary: 'Devuelve la hoja MDI activa de la ventana.',
        signature: 'GetActiveSheet()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una instancia de servicio contextual para la ventana.',
        signature: 'GetContextService(...)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetFirstSheet',
        category: 'Contexto',
        summary: 'Devuelve la primera hoja abierta en la ventana MDI.',
        signature: 'GetFirstSheet()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetNextSheet',
        category: 'Contexto',
        summary: 'Devuelve la siguiente hoja abierta a partir de una hoja dada.',
        signature: 'GetNextSheet(sheet)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenSheet',
        category: 'Visual',
        summary: 'Abre un user object como hoja de la ventana.',
        signature: 'OpenSheet(uo, parent, position?, arrangeopen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenSheetWithParm',
        category: 'Visual',
        summary: 'Abre una hoja y expone un parámetro en el objeto Message.',
        signature: 'OpenSheetWithParm(uo, parent, parm, position?, arrangeopen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenUserObject',
        category: 'Visual',
        summary: 'Abre dinámicamente un user object asociado a la ventana.',
        signature: 'OpenUserObject(class, parent)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06B = defineObjectFunctionEntries([
    {
        name: 'OpenUserObjectWithParm',
        category: 'Visual',
        summary: 'Abre un user object dinámico y pasa un parámetro inicial.',
        signature: 'OpenUserObjectWithParm(class, parent, parm)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetToolbar',
        category: 'Contexto',
        summary: 'Obtiene una referencia a una toolbar registrada en la ventana.',
        signature: 'GetToolbar(index)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetToolbarPos',
        category: 'Layout',
        summary: 'Devuelve la posición actual de una toolbar de la ventana.',
        signature: 'GetToolbarPos(index)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'IsMaximizeAllTabbedSheetsEnabled',
        category: 'Contexto',
        summary: 'Indica si la ventana maximiza todas las hojas tabuladas.',
        signature: 'IsMaximizeAllTabbedSheetsEnabled()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'IsTabbedViewEnabled',
        category: 'Contexto',
        summary: 'Indica si la ventana usa vista tabulada para sus hojas.',
        signature: 'IsTabbedViewEnabled()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetMicroHelp',
        category: 'Visual',
        summary: 'Actualiza el texto de microayuda mostrado por la ventana.',
        signature: 'SetMicroHelp(text)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetSheetID',
        category: 'Contexto',
        summary: 'Asigna un identificador lógico a una hoja abierta.',
        signature: 'SetSheetID(sheet, id)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetToolbar',
        category: 'Visual',
        summary: 'Muestra u oculta una toolbar registrada en la ventana.',
        signature: 'SetToolbar(index, visible)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetToolbarPos',
        category: 'Layout',
        summary: 'Reubica una toolbar de la ventana en la posición indicada.',
        signature: 'SetToolbarPos(index, position)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SaveDockingState',
        category: 'Contexto',
        summary: 'Persiste el layout acoplado actual de la ventana en un archivo.',
        signature: 'SaveDockingState(file)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06C = defineObjectFunctionEntries([
    {
        name: 'AddItem',
        category: 'Interacción',
        summary: 'Agrega un elemento al final del ListBox.',
        signature: 'AddItem(text)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interacción',
        summary: 'Elimina el elemento indicado del ListBox.',
        signature: 'DeleteItem(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DirList',
        category: 'Interacción',
        summary: 'Carga en el ListBox los archivos que cumplen un patrón.',
        signature: 'DirList(path, filetype)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'DirSelect',
        category: 'Interacción',
        summary: 'Recupera la selección actual del ListBox en una variable.',
        signature: 'DirSelect(pathvar)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Drag',
        category: 'Interacción',
        summary: 'Inicia o termina el arrastre del control ListBox.',
        signature: 'Drag(begin)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'FindItem',
        category: 'Interacción',
        summary: 'Busca el siguiente elemento que comienza por el texto indicado.',
        signature: 'FindItem(text, start)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una instancia de servicio contextual para el ListBox.',
        signature: 'GetContextService(...)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interacción',
        summary: 'Inserta un elemento antes del índice indicado.',
        signature: 'InsertItem(index, text)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Imprime el contenido visible del ListBox.',
        signature: 'Print()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06D = defineObjectFunctionEntries([
    {
        name: 'Reset',
        category: 'Interacción',
        summary: 'Elimina todos los elementos del ListBox.',
        signature: 'Reset()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control ListBox.',
        signature: 'ClassName()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve el objeto padre del ListBox.',
        signature: 'GetParent()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la posición horizontal del puntero respecto al ListBox.',
        signature: 'PointerX()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la posición vertical del puntero respecto al ListBox.',
        signature: 'PointerY()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectedIndex',
        category: 'Interacción',
        summary: 'Devuelve el índice del primer elemento seleccionado.',
        signature: 'SelectedIndex()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectedItem',
        category: 'Texto',
        summary: 'Devuelve el texto del primer elemento seleccionado.',
        signature: 'SelectedItem()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SelectItem',
        category: 'Interacción',
        summary: 'Selecciona un elemento por texto o por índice.',
        signature: 'SelectItem(item, select?)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Cambia el orden Z del ListBox dentro de la ventana.',
        signature: 'SetPosition(position)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06E = defineObjectFunctionEntries([
    {
        name: 'SetRedraw',
        category: 'Visual',
        summary: 'Suspende o reactiva el repintado automático del ListBox.',
        signature: 'SetRedraw(redraw)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetState',
        category: 'Interacción',
        summary: 'Cambia el estado seleccionado de un elemento multiselección.',
        signature: 'SetState(index, selected)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'SetTop',
        category: 'Layout',
        summary: 'Desplaza el ListBox para mostrar primero el elemento indicado.',
        signature: 'SetTop(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'State',
        category: 'Interacción',
        summary: 'Indica si un elemento concreto está seleccionado.',
        signature: 'State(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Text',
        category: 'Texto',
        summary: 'Devuelve el texto del elemento indicado por índice.',
        signature: 'Text(index)',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'Top',
        category: 'Layout',
        summary: 'Devuelve el índice del elemento visible en la parte superior.',
        signature: 'Top()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TotalItems',
        category: 'Interacción',
        summary: 'Devuelve el número total de elementos del ListBox.',
        signature: 'TotalItems()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TotalSelected',
        category: 'Interacción',
        summary: 'Devuelve cuántos elementos están seleccionados.',
        signature: 'TotalSelected()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
    {
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del ListBox.',
        signature: 'TypeOf()',
        appliesTo: LISTBOX_APPLIES_TO,
        ownerTypes: LISTBOX_OWNER_TYPES,
        sourceUrl: LISTBOX_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06F = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control Tab.',
        signature: 'ClassName()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'CloseTab',
        category: 'Visual',
        summary: 'Cierra una página abierta dinámicamente dentro del Tab.',
        signature: 'CloseTab(index)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'Drag',
        category: 'Interacción',
        summary: 'Inicia o termina el arrastre del control Tab.',
        signature: 'Drag(begin)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una instancia de servicio contextual para el Tab.',
        signature: 'GetContextService(...)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve el objeto padre del Tab.',
        signature: 'GetParent()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'MoveTab',
        category: 'Layout',
        summary: 'Reordena una pestaña a una nueva posición.',
        signature: 'MoveTab(from, to)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'OpenTab',
        category: 'Visual',
        summary: 'Abre un user object como página del control Tab.',
        signature: 'OpenTab(uo, index?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'OpenTabWithParm',
        category: 'Visual',
        summary: 'Abre una página del Tab y pasa un parámetro inicial.',
        signature: 'OpenTabWithParm(uo, parm, index?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06G = defineObjectFunctionEntries([
    {
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la posición horizontal del puntero respecto al Tab.',
        signature: 'PointerX()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la posición vertical del puntero respecto al Tab.',
        signature: 'PointerY()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Imprime el contenido actual del control Tab.',
        signature: 'Print()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'SelectTab',
        category: 'Interacción',
        summary: 'Selecciona programáticamente una página del Tab.',
        signature: 'SelectTab(index)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Cambia el orden Z del Tab dentro de la ventana.',
        signature: 'SetPosition(position)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TabPostEvent',
        category: 'Eventos',
        summary: 'Publica un evento en las colas de todas las páginas del Tab.',
        signature: 'TabPostEvent(eventname, wordparm?, longparm?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TabTriggerEvent',
        category: 'Eventos',
        summary: 'Dispara un evento sobre todas las páginas del Tab.',
        signature: 'TabTriggerEvent(eventname, wordparm?, longparm?)',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
    {
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del control Tab.',
        signature: 'TypeOf()',
        appliesTo: TAB_APPLIES_TO,
        ownerTypes: TAB_OWNER_TYPES,
        sourceUrl: TAB_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06H = defineObjectFunctionEntries([
    {
        name: 'AddColumn',
        category: 'Layout',
        summary: 'Agrega una columna al modo report del ListView.',
        signature: 'AddColumn(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddItem',
        category: 'Interacción',
        summary: 'Agrega un elemento al ListView.',
        signature: 'AddItem(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddLargePicture',
        category: 'Visual',
        summary: 'Agrega una imagen a la lista de iconos grandes del ListView.',
        signature: 'AddLargePicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddSmallPicture',
        category: 'Visual',
        summary: 'Agrega una imagen a la lista de iconos pequeños del ListView.',
        signature: 'AddSmallPicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'AddStatePicture',
        category: 'Visual',
        summary: 'Agrega una imagen a la lista de estados del ListView.',
        signature: 'AddStatePicture(picture)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'Arrange',
        category: 'Layout',
        summary: 'Reorganiza los elementos del ListView en vista de iconos.',
        signature: 'Arrange(style?)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control ListView.',
        signature: 'ClassName()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una instancia de servicio contextual para el ListView.',
        signature: 'GetContextService(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve el objeto padre del ListView.',
        signature: 'GetParent()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06I = defineObjectFunctionEntries([
    {
        name: 'DeleteColumn',
        category: 'Layout',
        summary: 'Elimina una columna del ListView.',
        signature: 'DeleteColumn(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteColumns',
        category: 'Layout',
        summary: 'Elimina todas las columnas del ListView.',
        signature: 'DeleteColumns()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interacción',
        summary: 'Elimina un elemento del ListView.',
        signature: 'DeleteItem(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteItems',
        category: 'Interacción',
        summary: 'Elimina todos los elementos del ListView.',
        signature: 'DeleteItems()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'EditLabel',
        category: 'Texto',
        summary: 'Inicia la edición de la etiqueta de un elemento.',
        signature: 'EditLabel(index)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'FindItem',
        category: 'Interacción',
        summary: 'Busca el siguiente elemento que cumple un criterio.',
        signature: 'FindItem(...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetColumn',
        category: 'Contexto',
        summary: 'Recupera las propiedades de una columna del ListView.',
        signature: 'GetColumn(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'GetItem',
        category: 'Contexto',
        summary: 'Recupera la información de un elemento del ListView.',
        signature: 'GetItem(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06J = defineObjectFunctionEntries([
    {
        name: 'GetOrigin',
        category: 'Layout',
        summary: 'Obtiene las coordenadas del origen visible del ListView.',
        signature: 'GetOrigin(x, y)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'InsertColumn',
        category: 'Layout',
        summary: 'Inserta una columna en la posición indicada.',
        signature: 'InsertColumn(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interacción',
        summary: 'Inserta un elemento en la posición indicada.',
        signature: 'InsertItem(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la posición horizontal del puntero respecto al ListView.',
        signature: 'PointerX()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la posición vertical del puntero respecto al ListView.',
        signature: 'PointerY()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetColumn',
        category: 'Layout',
        summary: 'Actualiza las propiedades de una columna del ListView.',
        signature: 'SetColumn(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetItem',
        category: 'Interacción',
        summary: 'Actualiza los valores de un elemento del ListView.',
        signature: 'SetItem(index, ...)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetOverlayPicture',
        category: 'Visual',
        summary: 'Asocia una imagen overlay a un índice de imagen del ListView.',
        signature: 'SetOverlayPicture(pictureindex, overlayindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06K = defineObjectFunctionEntries([
    {
        name: 'AddPicture',
        category: 'Visual',
        summary: 'Agrega una imagen a la lista principal del TreeView.',
        signature: 'AddPicture(picture)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'AddStatePicture',
        category: 'Visual',
        summary: 'Agrega una imagen a la lista de estado del TreeView.',
        signature: 'AddStatePicture(picture)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'CollapseItem',
        category: 'Interacción',
        summary: 'Contrae el ítem indicado del TreeView.',
        signature: 'CollapseItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteItem',
        category: 'Interacción',
        summary: 'Elimina un ítem del TreeView y todos sus hijos.',
        signature: 'DeleteItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Drag',
        category: 'Interacción',
        summary: 'Inicia o termina el arrastre de un ítem del TreeView.',
        signature: 'Drag(begin)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'EditLabel',
        category: 'Texto',
        summary: 'Inicia la edición de la etiqueta de un ítem del TreeView.',
        signature: 'EditLabel(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'ExpandAll',
        category: 'Interacción',
        summary: 'Expande un ítem y todos sus niveles descendientes.',
        signature: 'ExpandAll(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'ExpandItem',
        category: 'Interacción',
        summary: 'Expande el ítem indicado del TreeView.',
        signature: 'ExpandItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06L = defineObjectFunctionEntries([
    {
        name: 'FindItem',
        category: 'Interacción',
        summary: 'Busca un ítem del TreeView según criterios de búsqueda.',
        signature: 'FindItem(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetContextService',
        category: 'Contexto',
        summary: 'Crea una instancia de servicio contextual para el TreeView.',
        signature: 'GetContextService(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetItem',
        category: 'Contexto',
        summary: 'Recupera la información de un ítem del TreeView.',
        signature: 'GetItem(handle, ...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetItemAtPointer',
        category: 'Interacción',
        summary: 'Obtiene el ítem situado bajo el puntero.',
        signature: 'GetItemAtPointer()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve el objeto padre del TreeView.',
        signature: 'GetParent()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItem',
        category: 'Interacción',
        summary: 'Inserta un ítem en una posición y nivel concretos.',
        signature: 'InsertItem(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItemFirst',
        category: 'Interacción',
        summary: 'Inserta un ítem como primer hijo del nivel indicado.',
        signature: 'InsertItemFirst(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'InsertItemLast',
        category: 'Interacción',
        summary: 'Inserta un ítem como último hijo del nivel indicado.',
        signature: 'InsertItemLast(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06M = defineObjectFunctionEntries([
    {
        name: 'InsertItemSort',
        category: 'Interacción',
        summary: 'Inserta un ítem respetando la ordenación alfabética actual.',
        signature: 'InsertItemSort(...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la posición horizontal del puntero respecto al TreeView.',
        signature: 'PointerX()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la posición vertical del puntero respecto al TreeView.',
        signature: 'PointerY()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SelectItem',
        category: 'Interacción',
        summary: 'Selecciona programáticamente un ítem del TreeView.',
        signature: 'SelectItem(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetDropHighlight',
        category: 'Visual',
        summary: 'Marca un ítem como destino visual de una operación DragDrop.',
        signature: 'SetDropHighlight(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetFirstVisible',
        category: 'Layout',
        summary: 'Convierte un ítem en el primero visible del TreeView.',
        signature: 'SetFirstVisible(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetItem',
        category: 'Interacción',
        summary: 'Actualiza la información asociada a un ítem del TreeView.',
        signature: 'SetItem(handle, ...)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetLevelPictures',
        category: 'Visual',
        summary: 'Asocia imágenes comunes a todos los ítems de un nivel.',
        signature: 'SetLevelPictures(level, pictureindex, selectedindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09A = defineObjectFunctionEntries([
    {
        name: 'DeleteLargePicture',
        category: 'Visual',
        summary: 'Elimina una imagen concreta de la lista de iconos grandes del ListView.',
        signature: 'DeleteLargePicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteLargePictures',
        category: 'Visual',
        summary: 'Elimina todas las imágenes de la lista de iconos grandes del ListView.',
        signature: 'DeleteLargePictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteSmallPicture',
        category: 'Visual',
        summary: 'Elimina una imagen concreta de la lista de iconos pequeños del ListView.',
        signature: 'DeleteSmallPicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteSmallPictures',
        category: 'Visual',
        summary: 'Elimina todas las imágenes de la lista de iconos pequeños del ListView.',
        signature: 'DeleteSmallPictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteStatePicture',
        category: 'Visual',
        summary: 'Elimina una imagen concreta de la lista de estados del ListView.',
        signature: 'DeleteStatePicture(pictureindex)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'DeleteStatePictures',
        category: 'Visual',
        summary: 'Elimina todas las imágenes de la lista de estados del ListView.',
        signature: 'DeleteStatePictures()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'Sort',
        category: 'Layout',
        summary: 'Ordena los elementos del ListView según el modo de ordenación configurado.',
        signature: 'Sort()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalColumns',
        category: 'Contexto',
        summary: 'Devuelve el número de columnas definidas en la vista report del ListView.',
        signature: 'TotalColumns()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09B = defineObjectFunctionEntries([
    {
        name: 'Drag',
        category: 'Interacción',
        summary: 'Inicia o termina el arrastre programático de un elemento del ListView.',
        signature: 'Drag(begin)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SelectedIndex',
        category: 'Interacción',
        summary: 'Devuelve el índice del elemento actualmente seleccionado en el ListView.',
        signature: 'SelectedIndex()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalItems',
        category: 'Interacción',
        summary: 'Devuelve el número total de elementos cargados en el ListView.',
        signature: 'TotalItems()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TotalSelected',
        category: 'Interacción',
        summary: 'Devuelve cuántos elementos están seleccionados en el ListView.',
        signature: 'TotalSelected()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09C = defineObjectFunctionEntries([
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Incluye la parte visible del ListView en el trabajo de impresión activo.',
        signature: 'Print()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Cambia la posición Z del ListView dentro de la ventana contenedora.',
        signature: 'SetPosition(position)',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
    {
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del control ListView.',
        signature: 'TypeOf()',
        appliesTo: LISTVIEW_APPLIES_TO,
        ownerTypes: LISTVIEW_OWNER_TYPES,
        sourceUrl: LISTVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09D = defineObjectFunctionEntries([
    {
        name: 'DeletePicture',
        category: 'Visual',
        summary: 'Elimina una imagen concreta de la lista principal del TreeView.',
        signature: 'DeletePicture(pictureindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeletePictures',
        category: 'Visual',
        summary: 'Elimina todas las imágenes de la lista principal del TreeView.',
        signature: 'DeletePictures()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteStatePicture',
        category: 'Visual',
        summary: 'Elimina una imagen concreta de la lista de estado del TreeView.',
        signature: 'DeleteStatePicture(pictureindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'DeleteStatePictures',
        category: 'Visual',
        summary: 'Elimina todas las imágenes de la lista de estado del TreeView.',
        signature: 'DeleteStatePictures()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09E = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control TreeView.',
        signature: 'ClassName()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Print',
        category: 'Visual',
        summary: 'Incluye la parte visible del TreeView en el trabajo de impresión activo.',
        signature: 'Print()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Cambia la posición Z del TreeView dentro de la ventana contenedora.',
        signature: 'SetPosition(position)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del control TreeView.',
        signature: 'TypeOf()',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09F = defineObjectFunctionEntries([
    {
        name: 'SetOverlayPicture',
        category: 'Visual',
        summary: 'Asocia una imagen overlay a un índice de imagen del TreeView.',
        signature: 'SetOverlayPicture(pictureindex, overlayindex)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'Sort',
        category: 'Layout',
        summary: 'Ordena los hijos directos del ítem indicado según SortType o por orden alfabético.',
        signature: 'Sort(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
    {
        name: 'SortAll',
        category: 'Layout',
        summary: 'Ordena el ítem indicado y todos sus niveles descendientes según SortType o por orden alfabético.',
        signature: 'SortAll(handle)',
        appliesTo: TREEVIEW_APPLIES_TO,
        ownerTypes: TREEVIEW_OWNER_TYPES,
        sourceUrl: TREEVIEW_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09G = defineObjectFunctionEntries([
    {
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado a la ventana en tiempo de ejecución.',
        signature: 'ClassName()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetPosition',
        category: 'Layout',
        summary: 'Cambia la posición Z de la ventana dentro del orden visual de la aplicación.',
        signature: 'SetPosition(position)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09H = defineObjectFunctionEntries([
    {
        name: 'CommitDocking',
        category: 'Visual',
        summary: 'Aplica y hace visible el layout acoplado persistido tras abrir todas las hojas necesarias.',
        signature: 'CommitDocking()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09I = defineObjectFunctionEntries([
    {
        name: 'LoadDockingState',
        category: 'Contexto',
        summary: 'Carga el estado persistido de docking con las clases e identificadores de hojas guardadas.',
        signature: 'LoadDockingState(file, typeNames, ids)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09J = defineObjectFunctionEntries([
    {
        name: 'OpenSheetAsDocument',
        category: 'Visual',
        summary: 'Abre una hoja como documento tabulado dentro del marco MDI con docking.',
        signature: 'OpenSheetAsDocument(uo, parent, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09K = defineObjectFunctionEntries([
    {
        name: 'OpenSheetDocked',
        category: 'Visual',
        summary: 'Abre una hoja acoplada en una posición concreta del marco MDI.',
        signature: 'OpenSheetDocked(uo, parent, position, size?, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09L = defineObjectFunctionEntries([
    {
        name: 'OpenSheetFromDockingState',
        category: 'Visual',
        summary: 'Abre hojas persistidas a partir de un estado de docking previamente almacenado.',
        signature: 'OpenSheetFromDockingState(file, parent)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09M = defineObjectFunctionEntries([
    {
        name: 'OpenSheetInTabGroup',
        category: 'Visual',
        summary: 'Abre una hoja en un grupo de pestañas del marco MDI con docking.',
        signature: 'OpenSheetInTabGroup(uo, parent, tabgroup, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09N = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmAsDocument',
        category: 'Visual',
        summary: 'Abre una hoja como documento tabulado y expone un parámetro inicial en Message.',
        signature: 'OpenSheetWithParmAsDocument(uo, parent, parm, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09O = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmDocked',
        category: 'Visual',
        summary: 'Abre una hoja acoplada en una posición concreta y expone un parámetro inicial en Message.',
        signature: 'OpenSheetWithParmDocked(uo, parent, parm, position, size?, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09P = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmFromDockingState',
        category: 'Visual',
        summary: 'Abre hojas persistidas desde un estado de docking y expone un parámetro inicial en Message.',
        signature: 'OpenSheetWithParmFromDockingState(file, parent, parm)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09Q = defineObjectFunctionEntries([
    {
        name: 'OpenSheetWithParmInTabGroup',
        category: 'Visual',
        summary: 'Abre una hoja en un grupo de pestañas del marco MDI y expone un parámetro inicial en Message.',
        signature: 'OpenSheetWithParmInTabGroup(uo, parent, parm, tabgroup, arrangerOpen?)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Las dockable windows son obsoletas desde PowerBuilder 2019 R2 y ya no reciben soporte tecnico.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

const PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09R = defineObjectFunctionEntries([
    {
        name: 'CloseChannel',
        category: 'Contexto',
        summary: 'Cierra un canal DDE abierto previamente por la ventana.',
        signature: 'CloseChannel(channel)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'ExecRemote',
        category: 'Contexto',
        summary: 'Solicita a una aplicacion servidor DDE que ejecute un comando remoto.',
        signature: 'ExecRemote(channel, command)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetCommandDDE',
        category: 'Contexto',
        summary: 'Obtiene el comando recibido por la ventana cuando actua como servidor DDE.',
        signature: 'GetCommandDDE(command)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetCommandDDEOrigin',
        category: 'Contexto',
        summary: 'Obtiene el origen del comando recibido cuando la ventana actua como servidor DDE.',
        signature: 'GetCommandDDEOrigin(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetDataDDE',
        category: 'Texto',
        summary: 'Obtiene datos enviados por otra aplicacion DDE y los copia en una variable destino.',
        signature: 'GetDataDDE(data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetDataDDEOrigin',
        category: 'Contexto',
        summary: 'Recupera los identificadores DDE asociados al origen de los datos recibidos.',
        signature: 'GetDataDDEOrigin(application, topic, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'GetRemote',
        category: 'Texto',
        summary: 'Solicita datos a una aplicacion servidor DDE y los almacena en una variable local.',
        signature: 'GetRemote(channel, item, data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'OpenChannel',
        category: 'Contexto',
        summary: 'Abre un canal hacia una aplicacion servidor DDE para una pareja aplicacion-topic.',
        signature: 'OpenChannel(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'RespondRemote',
        category: 'Contexto',
        summary: 'Indica si el comando o los datos recibidos desde una aplicacion DDE remota fueron aceptados.',
        signature: 'RespondRemote(accepted)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetDataDDE',
        category: 'Texto',
        summary: 'Envia datos a una aplicacion cliente DDE cuando la ventana actua como servidor.',
        signature: 'SetDataDDE(data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'SetRemote',
        category: 'Texto',
        summary: 'Solicita a una aplicacion servidor DDE que acepte y guarde datos en una ubicacion remota.',
        signature: 'SetRemote(channel, item, data)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StartHotLink',
        category: 'Contexto',
        summary: 'Establece un hot link DDE para recibir cambios inmediatos de un item remoto.',
        signature: 'StartHotLink(channel, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StartServerDDE',
        category: 'Contexto',
        summary: 'Registra la aplicacion actual como servidor DDE para la combinacion indicada.',
        signature: 'StartServerDDE(application, topic)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StopHotLink',
        category: 'Contexto',
        summary: 'Termina un hot link DDE establecido previamente con un item remoto.',
        signature: 'StopHotLink(channel, item)',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
    {
        name: 'StopServerDDE',
        category: 'Contexto',
        summary: 'Hace que la aplicacion deje de actuar como servidor DDE.',
        signature: 'StopServerDDE()',
        appliesTo: WINDOW_CONTROL_ONLY_APPLIES_TO,
        ownerTypes: WINDOW_CONTROL_ONLY_OWNER_TYPES,
        obsolete: true,
        obsoleteMessage: 'Funcion DDE obsoleta en PowerBuilder; se mantiene solo por compatibilidad heredada.',
        sourceUrl: WINDOW_CONTROL_URL,
    },
]);

export const PB_MANUAL_CORE_OBJECT_FUNCTIONS: readonly PbSystemSymbolEntry[] = [
    objectFunction({
        name: 'SetFocus',
        category: 'Interacción',
        summary: 'Transfiere el foco de entrada al objeto visual.',
        signatures: [{ label: 'SetFocus()' }],
        appliesTo: ['controles visuales compatibles'],
        ownerTypes: FOCUSABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Show',
        category: 'Visual',
        summary: 'Muestra un objeto visual oculto.',
        signatures: [{ label: 'Show()' }],
        appliesTo: ['objetos visuales'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Hide',
        category: 'Visual',
        summary: 'Oculta un objeto visual sin destruirlo.',
        signatures: [{ label: 'Hide()' }],
        appliesTo: ['objetos visuales'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Move',
        category: 'Layout',
        summary: 'Reubica el objeto visual en coordenadas cliente.',
        signatures: [{ label: 'Move(x, y)' }],
        appliesTo: ['objetos visuales'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'Resize',
        category: 'Layout',
        summary: 'Cambia el tamaño del objeto visual.',
        signatures: [{ label: 'Resize(width, height)' }],
        appliesTo: ['objetos visuales'],
        ownerTypes: VISUAL_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'SetRedraw',
        category: 'Visual',
        summary: 'Suspende o reactiva temporalmente el repintado del objeto visual.',
        signatures: [{ label: 'SetRedraw(redraw)' }],
        appliesTo: ['ventanas y controles con repintado explícito'],
        ownerTypes: REDRAWABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'GetText',
        category: 'Texto',
        summary: 'Devuelve el texto actual del control.',
        signatures: [{ label: 'GetText()' }],
        appliesTo: ['controles de edición y texto'],
        ownerTypes: TEXT_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'SetText',
        category: 'Texto',
        summary: 'Sustituye el texto mostrado por el control.',
        signatures: [{ label: 'SetText(text)' }],
        appliesTo: ['controles de edición y texto'],
        ownerTypes: TEXT_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'CanUndo',
        category: 'Texto',
        summary: 'Indica si el control puede deshacer la última edición realizada.',
        signatures: [{ label: 'CanUndo()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Clear',
        category: 'Texto',
        summary: 'Borra el texto seleccionado sin copiarlo al portapapeles.',
        signatures: [{ label: 'Clear()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Copy',
        category: 'Texto',
        summary: 'Copia el texto seleccionado al portapapeles sin eliminarlo.',
        signatures: [{ label: 'Copy()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Cut',
        category: 'Texto',
        summary: 'Corta el texto seleccionado y lo envía al portapapeles.',
        signatures: [{ label: 'Cut()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Paste',
        category: 'Texto',
        summary: 'Inserta el contenido del portapapeles en la posición actual del control.',
        signatures: [{ label: 'Paste()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'ReplaceText',
        category: 'Texto',
        summary: 'Reemplaza el texto seleccionado o inserta la cadena indicada en la posición actual.',
        signatures: [{
            label: 'ReplaceText(text)',
            parameters: [
                { label: 'text', documentation: 'Texto que se insertará o sustituirá sobre la selección actual.' },
            ],
        }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectText',
        category: 'Texto',
        summary: 'Selecciona un tramo de texto a partir de una posición y una longitud dadas.',
        signatures: [{
            label: 'SelectText(start, length)',
            parameters: [
                { label: 'start', documentation: 'Posición inicial del texto que se quiere seleccionar.' },
                { label: 'length', documentation: 'Número de caracteres que deben quedar seleccionados.' },
            ],
        }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Undo',
        category: 'Texto',
        summary: 'Deshace la última operación de edición realizada en el control.',
        signatures: [{ label: 'Undo()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'ClassName',
        category: 'Contexto',
        summary: 'Devuelve el nombre asignado al control en tiempo de ejecución.',
        signatures: [{ label: 'ClassName()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve una referencia al objeto padre que contiene el control.',
        signatures: [{ label: 'GetParent()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la distancia horizontal del puntero respecto al borde izquierdo del control.',
        signatures: [{ label: 'PointerX()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la distancia vertical del puntero respecto al borde superior del control.',
        signatures: [{ label: 'PointerY()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'Position',
        category: 'Texto',
        summary: 'Devuelve la posición actual del punto de inserción dentro del control.',
        signatures: [{ label: 'Position()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedLength',
        category: 'Texto',
        summary: 'Devuelve la longitud del texto actualmente seleccionado.',
        signatures: [{ label: 'SelectedLength()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedStart',
        category: 'Texto',
        summary: 'Devuelve la posición inicial del texto actualmente seleccionado.',
        signatures: [{ label: 'SelectedStart()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedText',
        category: 'Texto',
        summary: 'Devuelve el texto actualmente seleccionado en el control.',
        signatures: [{ label: 'SelectedText()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime del control actual.',
        signatures: [{ label: 'TypeOf()' }],
        appliesTo: ['controles editables de texto'],
        ownerTypes: EDITABLE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/SingleLineEdit_control.html',
    }),
    objectFunction({
        name: 'LineCount',
        category: 'Texto',
        summary: 'Devuelve el número total de líneas disponibles en el control.',
        signatures: [{ label: 'LineCount()' }],
        appliesTo: ['controles editables con soporte de líneas'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'LineLength',
        category: 'Texto',
        summary: 'Devuelve la longitud de la línea donde está situado el punto de inserción.',
        signatures: [{ label: 'LineLength()' }],
        appliesTo: ['controles editables con soporte de líneas'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'Scroll',
        category: 'Texto',
        summary: 'Desplaza el contenido del control hacia arriba o abajo el número indicado de líneas.',
        signatures: [{
            label: 'Scroll(lines)',
            parameters: [
                { label: 'lines', documentation: 'Número de líneas que se desplaza el contenido; positivo baja y negativo sube.' },
            ],
        }],
        appliesTo: ['controles editables con soporte de líneas'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'SelectedLine',
        category: 'Texto',
        summary: 'Devuelve el número de la línea en la que está situado el punto de inserción.',
        signatures: [{ label: 'SelectedLine()' }],
        appliesTo: ['controles editables con soporte de líneas'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'TextLine',
        category: 'Texto',
        summary: 'Devuelve el texto completo de la línea actual del control.',
        signatures: [{ label: 'TextLine()' }],
        appliesTo: ['controles editables con soporte de líneas'],
        ownerTypes: MULTILINE_TEXT_OBJECT_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/MultiLineEdit_control.html',
    }),
    objectFunction({
        name: 'GetParent',
        category: 'Contexto',
        summary: 'Devuelve una referencia al objeto padre que contiene la ventana.',
        signatures: [{ label: 'GetParent()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'ParentWindow',
        category: 'Contexto',
        summary: 'Devuelve la ventana padre de la ventana actual cuando existe.',
        signatures: [{ label: 'ParentWindow()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PointerX',
        category: 'Interacción',
        summary: 'Devuelve la distancia horizontal del puntero respecto al borde izquierdo de la pantalla.',
        signatures: [{ label: 'PointerX()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PointerY',
        category: 'Interacción',
        summary: 'Devuelve la distancia vertical del puntero respecto al borde superior de la pantalla.',
        signatures: [{ label: 'PointerY()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'Print',
        category: 'Visual',
        summary: 'Envía la ventana actual a impresión con la configuración activa.',
        signatures: [{ label: 'Print()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'TypeOf',
        category: 'Contexto',
        summary: 'Devuelve el tipo runtime de la ventana actual.',
        signatures: [{ label: 'TypeOf()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceHeight',
        category: 'Layout',
        summary: 'Devuelve la altura del workspace utilizable dentro de la ventana.',
        signatures: [{ label: 'WorkSpaceHeight()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceWidth',
        category: 'Layout',
        summary: 'Devuelve la anchura del workspace utilizable dentro de la ventana.',
        signatures: [{ label: 'WorkSpaceWidth()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceX',
        category: 'Layout',
        summary: 'Devuelve la coordenada X del borde izquierdo del workspace de la ventana.',
        signatures: [{ label: 'WorkSpaceX()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'WorkSpaceY',
        category: 'Layout',
        summary: 'Devuelve la coordenada Y del borde superior del workspace de la ventana.',
        signatures: [{ label: 'WorkSpaceY()' }],
        appliesTo: ['ventanas'],
        ownerTypes: ['window'],
        sourceUrl: 'https://docs.appeon.com/pb2025/objects_and_controls/Window_control.html',
    }),
    objectFunction({
        name: 'PostEvent',
        category: 'Eventos',
        summary: 'Publica un evento para que se procese de forma asíncrona sobre el objeto.',
        signatures: [{ label: 'PostEvent(eventname, wordparm?, longparm?)' }],
        appliesTo: ['objetos PowerBuilder con eventos scriptables'],
        ownerTypes: EVENT_CAPABLE_OBJECT_TYPES,
    }),
    objectFunction({
        name: 'TriggerEvent',
        category: 'Eventos',
        summary: 'Dispara inmediatamente un evento sobre el objeto actual o indicado.',
        signatures: [{ label: 'TriggerEvent(eventname, wordparm?, longparm?)' }],
        appliesTo: ['objetos PowerBuilder con eventos scriptables'],
        ownerTypes: EVENT_CAPABLE_OBJECT_TYPES,
    }),
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06A,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06B,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06C,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06D,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06E,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06F,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06G,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06H,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06I,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06J,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06K,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06L,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_06M,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09A,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09B,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09C,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09D,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09E,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09F,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09G,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09H,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09I,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09J,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09K,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09L,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09M,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09N,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09O,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09P,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09Q,
    ...PB_MANUAL_CORE_OBJECT_FUNCTIONS_MF_09R,
];
