import { PbSystemSymbolEntry } from '../../types';
import { systemObjectDatatype } from '../common';

export const PB_MANUAL_CORE_INTEGRATION_PDF_CATEGORIES = [
  'PDF',
] as const;

export const PB_MANUAL_CORE_INTEGRATION_PDF_TYPES: readonly PbSystemSymbolEntry[] = [
  systemObjectDatatype({
    name: 'PDFAction',
    category: 'PDF',
    summary: 'Reusable PDF action within the runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFAction documentation.', evidence: ['manual-core:integration:pdf:pdfaction'] },
  }),
  systemObjectDatatype({
    name: 'PDFActionJavaScript',
    category: 'PDF',
    summary: 'JavaScript-based PDF action.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFActionJavaScript documentation.', evidence: ['manual-core:integration:pdf:pdfactionjavascript'] },
  }),
  systemObjectDatatype({
    name: 'PDFActionNamed',
    category: 'PDF',
    summary: 'Reusable named PDF action.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFActionNamed documentation.', evidence: ['manual-core:integration:pdf:pdfactionnamed'] },
  }),
  systemObjectDatatype({
    name: 'PDFActionResetForm',
    category: 'PDF',
    summary: 'PDF action to reset forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFActionResetForm documentation.', evidence: ['manual-core:integration:pdf:pdfactionresetform'] },
  }),
  systemObjectDatatype({
    name: 'PDFAttachment',
    category: 'PDF',
    summary: 'Embedded attachment within a PDF document.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFAttachment documentation.', evidence: ['manual-core:integration:pdf:pdfattachment'] },
  }),
  systemObjectDatatype({
    name: 'PDFColor',
    category: 'PDF',
    summary: 'Reusable color within the PDF subsystem.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFColor documentation.', evidence: ['manual-core:integration:pdf:pdfcolor'] },
  }),
  systemObjectDatatype({
    name: 'PDFContent',
    category: 'PDF',
    summary: 'Reusable base content within a PDF page.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFContent documentation.', evidence: ['manual-core:integration:pdf:pdfcontent'] },
  }),
  systemObjectDatatype({
    name: 'PDFContext',
    category: 'PDF',
    summary: 'Non-visual context for PDF operations.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFContext documentation.', evidence: ['manual-core:integration:pdf:pdfcontext'] },
  }),
  systemObjectDatatype({
    name: 'PDFDocExtractor',
    category: 'PDF',
    summary: 'PDF content and metadata extractor.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFDocExtractor documentation.', evidence: ['manual-core:integration:pdf:pdfdocextractor'] },
  }),
  systemObjectDatatype({
    name: 'PDFDocument',
    category: 'PDF',
    summary: 'Non-visual PDF document.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFDocument documentation.', evidence: ['manual-core:integration:pdf:pdfdocument'] },
  }),
  systemObjectDatatype({
    name: 'PDFDocumentProperties',
    category: 'PDF',
    summary: 'PDF document properties.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFDocumentProperties documentation.', evidence: ['manual-core:integration:pdf:pdfdocumentproperties'] },
  }),
  systemObjectDatatype({
    name: 'PDFFont',
    category: 'PDF',
    summary: 'Reusable font within the PDF runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFont documentation.', evidence: ['manual-core:integration:pdf:pdffont'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormField',
    category: 'PDF',
    summary: 'Base field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormField documentation.', evidence: ['manual-core:integration:pdf:pdfformfield'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldCheckBox',
    category: 'PDF',
    summary: 'Checkbox field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldCheckBox documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldcheckbox'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldComboBox',
    category: 'PDF',
    summary: 'Combo box field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldComboBox documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldcombobox'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldGroup',
    category: 'PDF',
    summary: 'Field group for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldGroup documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldgroup'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldListBox',
    category: 'PDF',
    summary: 'List box field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldListBox documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldlistbox'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldPushButton',
    category: 'PDF',
    summary: 'Push button field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldPushButton documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldpushbutton'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldRadioButton',
    category: 'PDF',
    summary: 'Radio button field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldRadioButton documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldradiobutton'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldRadioButtonGroup',
    category: 'PDF',
    summary: 'Radio button group for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldRadioButtonGroup documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldradiobuttongroup'] },
  }),
  systemObjectDatatype({
    name: 'PDFFormFieldText',
    category: 'PDF',
    summary: 'Text field for PDF forms.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFFormFieldText documentation.', evidence: ['manual-core:integration:pdf:pdfformfieldtext'] },
  }),
  systemObjectDatatype({
    name: 'PDFImage',
    category: 'PDF',
    summary: 'Reusable image within the PDF runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFImage documentation.', evidence: ['manual-core:integration:pdf:pdfimage'] },
  }),
  systemObjectDatatype({
    name: 'PDFImportContent',
    category: 'PDF',
    summary: 'Content imported from another PDF.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFImportContent documentation.', evidence: ['manual-core:integration:pdf:pdfimportcontent'] },
  }),
  systemObjectDatatype({
    name: 'PDFInvisibleContent',
    category: 'PDF',
    summary: 'PDF content not visible but persisted in the document.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFInvisibleContent documentation.', evidence: ['manual-core:integration:pdf:pdfinvisiblecontent'] },
  }),
  systemObjectDatatype({
    name: 'PDFModel',
    category: 'PDF',
    summary: 'Non-visual model for PDF content.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFModel documentation.', evidence: ['manual-core:integration:pdf:pdfmodel'] },
  }),
  systemObjectDatatype({
    name: 'PDFMultilineText',
    category: 'PDF',
    summary: 'Reusable multiline text within the PDF subsystem.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFMultilineText documentation.', evidence: ['manual-core:integration:pdf:pdfmultilinetext'] },
  }),
  systemObjectDatatype({
    name: 'PDFObject',
    category: 'PDF',
    summary: 'Base non-visual object of the PDF subsystem.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFObject documentation.', evidence: ['manual-core:integration:pdf:pdfobject'] },
  }),
  systemObjectDatatype({
    name: 'PDFPage',
    category: 'PDF',
    summary: 'Non-visual PDF page.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFPage documentation.', evidence: ['manual-core:integration:pdf:pdfpage'] },
  }),
  systemObjectDatatype({
    name: 'PDFRichText',
    category: 'PDF',
    summary: 'Reusable rich text within the PDF subsystem.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFRichText documentation.', evidence: ['manual-core:integration:pdf:pdfrichtext'] },
  }),
  systemObjectDatatype({
    name: 'PDFSecurity',
    category: 'PDF',
    summary: 'Non-visual PDF security settings.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFSecurity documentation.', evidence: ['manual-core:integration:pdf:pdfsecurity'] },
  }),
  systemObjectDatatype({
    name: 'PDFSharedText',
    category: 'PDF',
    summary: 'Reusable shared text between PDF pages.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFSharedText documentation.', evidence: ['manual-core:integration:pdf:pdfsharedtext'] },
  }),
  systemObjectDatatype({
    name: 'PDFTableOfContents',
    category: 'PDF',
    summary: 'Non-visual PDF table of contents.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFTableOfContents documentation.', evidence: ['manual-core:integration:pdf:pdftableofcontents'] },
  }),
  systemObjectDatatype({
    name: 'PDFTableOfContentsItem',
    category: 'PDF',
    summary: 'PDF table of contents item.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFTableOfContentsItem documentation.', evidence: ['manual-core:integration:pdf:pdftableofcontentsitem'] },
  }),
  systemObjectDatatype({
    name: 'PDFText',
    category: 'PDF',
    summary: 'Reusable simple text within the PDF runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFText documentation.', evidence: ['manual-core:integration:pdf:pdftext'] },
  }),
  systemObjectDatatype({
    name: 'PDFTextBlock',
    category: 'PDF',
    summary: 'Reusable PDF text block.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFTextBlock documentation.', evidence: ['manual-core:integration:pdf:pdftextblock'] },
  }),
  systemObjectDatatype({
    name: 'PDFTextLayout',
    category: 'PDF',
    summary: 'Reusable text layout within the PDF runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFTextLayout documentation.', evidence: ['manual-core:integration:pdf:pdftextlayout'] },
  }),
  systemObjectDatatype({
    name: 'PDFVisibleContent',
    category: 'PDF',
    summary: 'Visible PDF content within a page.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFVisibleContent documentation.', evidence: ['manual-core:integration:pdf:pdfvisiblecontent'] },
  }),
  systemObjectDatatype({
    name: 'PDFWatermark',
    category: 'PDF',
    summary: 'Reusable watermark within the PDF runtime.',
    manualOverlay: { mode: 'override', reason: 'Hardening PDFWatermark documentation.', evidence: ['manual-core:integration:pdf:pdfwatermark'] },
  }),
];