export {
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_FUNCTION_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_SCROLL_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_SCROLL_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_VISUAL_APPLIES_TO,
  PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
} from './dataWindowOwnerTypes';
export {
  PB_MANUAL_CORE_OBJECT_FUNCTION_OWNER_TYPES,
  PB_MANUAL_CORE_OBJECT_OWNER_TYPES,
} from './objectOwnerTypes';
export {
  EVENT_CAPABLE_OBJECT_TYPES,
  FOCUSABLE_OBJECT_TYPES,
  INPUT_OBJECT_TYPES,
  REDRAWABLE_OBJECT_TYPES,
  TEXT_OBJECT_TYPES,
  VISUAL_OBJECT_TYPES,
} from './visualOwnerTypes';

import {
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_EVENT_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_SCROLL_OWNER_TYPES,
  PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
} from './dataWindowOwnerTypes';
import {
  PB_MANUAL_CORE_OBJECT_FUNCTION_OWNER_TYPES,
  PB_MANUAL_CORE_OBJECT_OWNER_TYPES,
} from './objectOwnerTypes';

export const PB_MANUAL_CORE_OWNER_TYPE_GROUPS = {
  object: PB_MANUAL_CORE_OBJECT_OWNER_TYPES,
  objectFunction: PB_MANUAL_CORE_OBJECT_FUNCTION_OWNER_TYPES,
  dataWindowFunction: PB_MANUAL_CORE_DATAWINDOW_FUNCTION_OWNER_TYPES,
  dataWindowControl: PB_MANUAL_CORE_DATAWINDOW_CONTROL_OWNER_TYPES,
  dataWindowScroll: PB_MANUAL_CORE_DATAWINDOW_SCROLL_OWNER_TYPES,
  dataWindowVisual: PB_MANUAL_CORE_DATAWINDOW_VISUAL_OWNER_TYPES,
  dataWindowDataEvent: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
  dataWindowEvent: PB_MANUAL_CORE_DATAWINDOW_EVENT_OWNER_TYPES,
  dataWindowControlEvent: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
} as const;