export const FOCUSABLE_OBJECT_TYPES = [
  'mdiframe',
  'mdiclient',
  'commandbutton',
  'singlelineedit',
  'checkbox',
  'radiobutton',
  'dropdownlistbox',
  'dropdownpicturelistbox',
  'editmask',
  'multilineedit',
  'picturebutton',
  'picturelistbox',
  'datepicker',
  'monthcalendar',
  'richtextedit',
  'inkedit',
  'tab',
  'tabbedbar',
  'treeview',
  'listview',
  'listbox',
  'webbrowser',
] as const;

export const VISUAL_OBJECT_TYPES = [
  'window',
  'mdiframe',
  'mdiclient',
  'datawindow',
  'menu',
  'menucascade',
  'animation',
  'commandbutton',
  'singlelineedit',
  'statictext',
  'statichyperlink',
  'checkbox',
  'radiobutton',
  'dropdownlistbox',
  'dropdownpicturelistbox',
  'editmask',
  'multilineedit',
  'richtextedit',
  'datepicker',
  'monthcalendar',
  'picturelistbox',
  'picturehyperlink',
  'multilineedit',
  'picturebutton',
  'picture',
  'groupbox',
  'powerserverlabel',
  'tab',
  'tabbedbar',
  'treeview',
  'treeviewitem',
  'listview',
  'listviewitem',
  'listbox',
  'graph',
  'graxis',
  'grdispattr',
  'line',
  'rectangle',
  'roundrectangle',
  'oval',
  'hprogressbar',
  'vprogressbar',
  'hscrollbar',
  'vscrollbar',
  'htrackbar',
  'vtrackbar',
  'inkedit',
  'inkpicture',
  'ribbonbar',
  'ribbonitem',
  'ribbonapplicationbuttonitem',
  'ribbonapplicationmenu',
  'ribboncategoryitem',
  'ribboncheckboxitem',
  'ribboncomboboxitem',
  'ribbongroupitem',
  'ribbonlargebuttonitem',
  'ribbonmenu',
  'ribbonmenuitem',
  'ribbonpanelitem',
  'ribbonsmallbuttonitem',
  'ribbontabbuttonitem',
  'userobject',
  'webbrowser',
  'olecontrol',
  'olecustomcontrol',
  'windowactivex',
] as const;

export const TEXT_OBJECT_TYPES = [
  'singlelineedit',
  'statictext',
  'statichyperlink',
  'editmask',
  'multilineedit',
  'richtextedit',
] as const;

export const INPUT_OBJECT_TYPES = [
  'singlelineedit',
  'editmask',
  'multilineedit',
  'dropdownlistbox',
  'dropdownpicturelistbox',
  'listbox',
  'picturelistbox',
  'checkbox',
  'radiobutton',
  'datepicker',
  'monthcalendar',
  'richtextedit',
  'treeview',
  'listview',
  'ribboncheckboxitem',
  'ribboncomboboxitem',
] as const;

export const EVENT_CAPABLE_OBJECT_TYPES = [
  'application',
  'nonvisualobject',
  ...VISUAL_OBJECT_TYPES,
] as const;

export const REDRAWABLE_OBJECT_TYPES = [
  'window',
  'mdiframe',
  'mdiclient',
  'datawindow',
  'tab',
  'tabbedbar',
  'treeview',
  'listview',
  'graph',
  'picture',
  'ribbonbar',
  'webbrowser',
  'windowactivex',
] as const;