import { PbSystemSymbolEntry } from '../../types';
import { dataWindowEvent } from '../common';
import {
    PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
    PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
    PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
} from '../ownerTypes/dataWindowOwnerTypes';

export const PB_MANUAL_CORE_DATAWINDOW_EVENT_CATEGORIES = [
    'Interacción',
    'Edición',
    'Navegación',
    'Errores',
    'Datos',
    'Transacciones',
] as const;

export const PB_MANUAL_CORE_DATAWINDOW_EVENTS: readonly PbSystemSymbolEntry[] = [
    dataWindowEvent({
        name: 'Clicked',
        category: 'Interacción',
        summary: 'Se dispara cuando el usuario hace clic en cualquier punto del DataWindow.',
        signatures: [{ label: 'Clicked(xpos, ypos, row, dwo)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_Clicked.html',
    }),
    dataWindowEvent({
        name: 'DoubleClicked',
        category: 'Interacción',
        summary: 'Se dispara cuando el usuario hace doble clic dentro del DataWindow.',
        signatures: [{ label: 'DoubleClicked(xpos, ypos, row, dwo)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_DoubleClicked.html',
    }),
    dataWindowEvent({
        name: 'ButtonClicked',
        category: 'Interacción',
        summary: 'Se dispara después de que el usuario pulse un botón contenido en el DataWindow.',
        signatures: [{ label: 'ButtonClicked(row, actionreturncode, dwo)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_ButtonClicked.html',
    }),
    dataWindowEvent({
        name: 'ItemChanged',
        category: 'Edición',
        summary: 'Se dispara cuando cambia un campo del DataWindow y pierde el foco antes de aceptar el valor.',
        signatures: [{ label: 'ItemChanged(row, dwo, data)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_ItemChanged.html',
    }),
    dataWindowEvent({
        name: 'ItemError',
        category: 'Edición',
        summary: 'Se dispara cuando un valor modificado no supera la validación de la columna.',
        signatures: [{ label: 'ItemError(row, dwo, data)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_ItemError.html',
    }),
    dataWindowEvent({
        name: 'ItemFocusChanged',
        category: 'Edición',
        summary: 'Se dispara cuando cambia el item actual que tiene el foco dentro del DataWindow.',
        signatures: [{ label: 'ItemFocusChanged(row, dwo)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_ItemFocusChanged.html',
    }),
    dataWindowEvent({
        name: 'RowFocusChanged',
        category: 'Navegación',
        summary: 'Se dispara cuando cambia la fila actual del DataWindow.',
        signatures: [{ label: 'RowFocusChanged(currentrow)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_RowFocusChanged.html',
    }),
    dataWindowEvent({
        name: 'RowFocusChanging',
        category: 'Navegación',
        summary: 'Se dispara justo antes de que cambie la fila actual del DataWindow.',
        signatures: [{ label: 'RowFocusChanging(currentrow, newrow)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_CONTROL_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_RowFocusChanging.html',
    }),
    dataWindowEvent({
        name: 'DBError',
        category: 'Errores',
        summary: 'Se dispara cuando una operación de base de datos del DataWindow o DataStore produce error.',
        signatures: [{ label: 'DBError(sqldbcode, sqlerrtext, sqlsyntax, buffer, row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_DBError.html',
    }),
    dataWindowEvent({
        name: 'RetrieveStart',
        category: 'Datos',
        summary: 'Se dispara justo antes de iniciar un Retrieve sobre el DataWindow o DataStore.',
        signatures: [{ label: 'RetrieveStart()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_RetrieveStart.html',
    }),
    dataWindowEvent({
        name: 'RetrieveRow',
        category: 'Datos',
        summary: 'Se dispara después de recuperar cada fila durante un Retrieve.',
        signatures: [{ label: 'RetrieveRow(row)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_RetrieveRow.html',
    }),
    dataWindowEvent({
        name: 'RetrieveEnd',
        category: 'Datos',
        summary: 'Se dispara cuando termina el proceso de Retrieve.',
        signatures: [{ label: 'RetrieveEnd(rowcount)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_RetrieveEnd.html',
    }),
    dataWindowEvent({
        name: 'UpdateStart',
        category: 'Transacciones',
        summary: 'Se dispara justo antes de enviar a la base de datos los cambios del DataWindow o DataStore.',
        signatures: [{ label: 'UpdateStart()' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_UpdateStart.html',
    }),
    dataWindowEvent({
        name: 'UpdateEnd',
        category: 'Transacciones',
        summary: 'Se dispara cuando finaliza el proceso de Update.',
        signatures: [{ label: 'UpdateEnd(rowsinserted, rowsupdated, rowsdeleted)' }],
        appliesTo: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_APPLIES_TO,
        ownerTypes: PB_MANUAL_CORE_DATAWINDOW_DATA_EVENT_OWNER_TYPES,
        sourceUrl: 'https://docs.appeon.com/pb2025/datawindow_reference/dwevt_UpdateEnd.html',
    }),
];
