import type { PbSystemSymbolLocalizationOverlay } from '../../../../types';

/**
 * Spanish localization overlays for manual runtime domain entries.
 */
export const PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_RUNTIME = [
	// — Non-visual objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ADOResultSet' }, text: { summary: 'Result set no visual de ADO.', documentation: 'El objeto ADOResultSet permite utilizar conjuntos de registros de ActiveX Data Object (ADO) para devolver un conjunto de resultados a un cliente y manipularlos en PowerBuilder.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'BatchDataObjects' }, text: { summary: 'Colección no visual para procesar múltiples objetos de datos en batch.', documentation: 'Especifica múltiples controles DataWindow, DataStores y DataWindows hijos para ser usados con la Web API de .NET DataStore. Se usa con el objeto RESTClient para realizar operaciones de recuperación o actualización masiva.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'NonVisualObject' }, text: { summary: 'Base de objetos no visuales personalizados.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ResultSet' }, text: { summary: 'Result set no visual interoperable con DataStore y ADO.', documentation: 'Proporciona la capacidad de usar record sets de ADO para devolver un conjunto de resultados. Se utiliza con las funciones CreateFrom y GenerateResultSet de DataStore.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Connection' }, text: { summary: 'Conexión no visual a servicios o fuentes externas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ContextInformation' }, text: { summary: 'Contexto no visual para metadata de sesión.', documentation: 'Proporciona información sobre el contexto de ejecución de la aplicación, incluyendo información de la versión actual. Permite modificar características de visualización y comportamiento según el entorno.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ContextKeyword' }, text: { summary: 'Keyword de contexto no visual para metadatos runtime.', documentation: 'Proporciona información del entorno para el contexto actual. En el entorno por defecto, devuelve las variables de entorno de la estación de trabajo host.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ErrorLogging' }, text: { summary: 'Objeto no visual para logging de errores.', documentation: 'Permite escribir mensajes en el archivo de registro utilizado por el contenedor del objeto, como el registro de aplicaciones del sistema para Microsoft Transaction Server.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MLSync' }, text: { summary: 'Objeto no visual para sincronización móvil.', documentation: 'Derivado de MLSynchronization. Su función principal es lanzar dbmlsync.exe para sincronizar una base de datos remota SQL Anywhere con una consolidada. Las propiedades controlan las opciones de sincronización.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MLSynchronization' }, text: { summary: 'Objeto no visual para sincronización móvil avanzada.', documentation: 'Clase abstracta de la cual se derivan los objetos MLSync.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Pipeline' }, text: { summary: 'Pipeline no visual para procesos ETL y data movement.', documentation: 'Se utiliza para gestionar un pipeline de datos durante la ejecución. Se define heredando del objeto integrado Pipeline en el pintor de User Object para acceder a sus eventos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PowerServerResult' }, text: { summary: 'Resultado no visual devuelto por operaciones PowerServer.', documentation: 'Almacena el resultado de operaciones combinadas (merged). Solo tiene efecto cuando la aplicación se despliega mediante un proyecto PowerServer.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SyncParm' }, text: { summary: 'Parámetro no visual para sincronización móvil.', documentation: 'Estructura del sistema para obtener propiedades en tiempo de ejecución de una ventana de opciones de sincronización y pasarlas a un objeto MLSync.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Timing' }, text: { summary: 'Utilidad no visual para medición temporal.', documentation: 'Objeto de sistema no visual que puede usarse cuando un evento Timer no puede asociarse a una ventana. Se debe heredar de la clase Timing para crear una instancia.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TransactionServer' }, text: { summary: 'Servidor transaccional no visual.', documentation: 'Proporciona información sobre el contexto de la transacción actual y permite que un componente controle la transacción y su propio ciclo de vida.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ULSync' }, text: { summary: 'Objeto no visual para sincronización UltraLite.', documentation: 'Derivado de MLSynchronization pero no soportado en la versión actual.' } },

	// — System objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Application' }, text: { summary: 'Objeto raíz de la aplicación PowerBuilder.', documentation: 'Una aplicación es una colección de ventanas y objetos que proporcionan funcionalidad para las actividades del usuario. El objeto Application es el punto de entrada; cuando se ejecuta la aplicación, se dispara su evento Open.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PowerObject' }, text: { summary: 'Raíz de la jerarquía de tipos PowerBuilder.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'GraphicObject' }, text: { summary: 'Base de objetos gráficos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DrawObject' }, text: { summary: 'Base de objetos de dibujo (línea, rectángulo, etc.).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Structure' }, text: { summary: 'Tipo estructura (agrupación de campos).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ArrayBounds' }, text: { summary: 'Describe los límites declarados de un array PowerBuilder.', documentation: 'Estructura que especifica los límites superior e inferior de una dimensión de un array. Se utiliza en el objeto VariableCardinalityDefinition.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DataWindowChild' }, text: { summary: 'Referencia a un DataWindow hijo (DropDownDataWindow).', documentation: 'Un objeto DataWindowChild es un reporte anidado o un DropDownDataWindow dentro de un objeto DataWindow. Se utiliza para acceder a estos objetos de forma independiente.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DynamicDescriptionArea' }, text: { summary: 'Área de descripción para SQL dinámico.', documentation: 'Objeto de sistema que almacena información sobre los parámetros de entrada y salida utilizados en el Formato 4 de SQL dinámico. PowerBuilder proporciona la variable global SQLDA.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DynamicStagingArea' }, text: { summary: 'Área de staging para SQL dinámico.', documentation: 'Almacena información para su uso en sentencias de SQL dinámico. Actúa como conexión entre la ejecución de una sentencia y un objeto Transaction. PowerBuilder proporciona la variable global SQLSA.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Environment' }, text: { summary: 'Información del entorno de ejecución.', documentation: 'Estructura del sistema utilizada para contener información sobre la plataforma informática en la que se ejecuta la aplicación. Se rellena mediante la función GetEnvironment.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Message' }, text: { summary: 'Objeto global para paso de mensajes entre objetos.', documentation: 'Se utiliza para procesar eventos no definidos por PowerBuilder y comunicar parámetros entre ventanas al abrirlas o cerrarlas.' } },

	// — System globals —
	{
		locale: 'es', reviewed: true, source: 'manual-curated',
		targetKey: { domain: 'system-globals', kind: 'system-global', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SQLCA' },
		text: { summary: 'Objeto global de transacción por defecto (tipo Transaction). Conecta y gestiona la base de datos.' }
	},
	{
		locale: 'es', reviewed: true, source: 'manual-curated',
		targetKey: { domain: 'system-globals', kind: 'system-global', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SQLSA' },
		text: { summary: 'Objeto global DynamicStagingArea para SQL dinámico formato 3 y 4.' }
	},
	{
		locale: 'es', reviewed: true, source: 'manual-curated',
		targetKey: { domain: 'system-globals', kind: 'system-global', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SQLDA' },
		text: { summary: 'Objeto global DynamicDescriptionArea para SQL dinámico formato 4.' }
	},
	{
		locale: 'es', reviewed: true, source: 'manual-curated',
		targetKey: { domain: 'system-globals', kind: 'system-global', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Error' },
		text: { summary: 'Objeto global de error del sistema. Recibe información cuando ocurre un error no capturado por try/catch.' }
	},
	{
		locale: 'es', reviewed: true, source: 'manual-curated',
		targetKey: { domain: 'system-globals', kind: 'system-global', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Message' },
		text: { summary: 'Objeto global para paso de mensajes entre objetos, usado con OpenWithParm, CloseWithReturn, etc.' }
	},

	// — Reflection objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ClassDefinition' }, text: { summary: 'Definición de clase para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'EnumerationDefinition' }, text: { summary: 'Definición de enumeración para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'EnumerationItemDefinition' }, text: { summary: 'Ítem de enumeración para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Function_Object' }, text: { summary: 'Objeto de función para reflexión runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PBDOM_CharacterData' }, text: { summary: 'Nodo DOM de datos de carácter.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PBDOM_Object' }, text: { summary: 'Objeto base del DOM XML en PowerBuilder.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PBDOM_Text' }, text: { summary: 'Nodo de texto del DOM XML en PowerBuilder.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ScriptDefinition' }, text: { summary: 'Definición de script para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SimpleTypeDefinition' }, text: { summary: 'Definición simple de tipo para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'VariableDefinition' }, text: { summary: 'Definición de variable para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'VariableCardinalityDefinition' }, text: { summary: 'Definición de cardinalidad para variables y arrays.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TypeDefinition' }, text: { summary: 'Definición de tipo para reflexión.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TypeObject' }, text: { summary: 'Objeto de tipo para reflexión.' } },
	// — Profiling objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ProfileLine' }, text: { summary: 'Línea perfilada dentro del subsistema de profiling.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ProfileCall' }, text: { summary: 'Traza de llamada dentro del subsistema de profiling.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ProfileClass' }, text: { summary: 'Clase perfilada dentro del subsistema de profiling.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ProfileRoutine' }, text: { summary: 'Rutina perfilada dentro del subsistema de profiling.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Profiling' }, text: { summary: 'Objeto no visual para profiling runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceActivityNode' }, text: { summary: 'Nodo de actividad dentro de una captura de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceBeginEnd' }, text: { summary: 'Traza de inicio y fin de actividad.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceFile' }, text: { summary: 'Traza persistida en archivo.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceObject' }, text: { summary: 'Traza asociada a un objeto runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceRoutine' }, text: { summary: 'Traza asociada a una rutina.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceUser' }, text: { summary: 'Traza asociada a actividad de usuario.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceESQL' }, text: { summary: 'Traza ESQL dentro de una sesión de profiling.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceGarbageCollect' }, text: { summary: 'Traza de recolección de basura del runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceLine' }, text: { summary: 'Traza de línea ejecutada.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTree' }, text: { summary: 'Árbol no visual de trazas runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeError' }, text: { summary: 'Nodo de error dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeESQL' }, text: { summary: 'Nodo ESQL dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeGarbageCollect' }, text: { summary: 'Nodo de garbage collection dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeLine' }, text: { summary: 'Nodo de línea dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeNode' }, text: { summary: 'Nodo base del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeObject' }, text: { summary: 'Nodo de objeto dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeRoutine' }, text: { summary: 'Nodo de rutina dentro del árbol de trazas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TraceTreeUser' }, text: { summary: 'Nodo de usuario dentro del árbol de trazas.' } },
	// — OLE objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLEObject' }, text: { summary: 'Objeto OLE Automation genérico.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLEStorage' }, text: { summary: 'Almacenamiento OLE Structured Storage.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLEStream' }, text: { summary: 'Flujo dentro de un OLE Storage.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLETxnObject' }, text: { summary: 'Objeto transaccional OLE no visual.' } },

	// — Mail objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MailSession' }, text: { summary: 'Sesión de correo MAPI/SMTP del runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SMTPClient' }, text: { summary: 'Cliente SMTP no visual para envío programático de correo.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MailFileDescription' }, text: { summary: 'Descriptor de archivo adjunto para el subsistema de correo.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MailMessage' }, text: { summary: 'Mensaje de correo manipulable desde el runtime.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MailRecipient' }, text: { summary: 'Destinatario de correo no visual.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MimeMessage' }, text: { summary: 'Mensaje MIME manipulable desde el runtime.' } },

	// — Error objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Exception' }, text: { summary: 'Excepción runtime interoperable con try/catch.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RuntimeError' }, text: { summary: 'Error en tiempo de ejecución.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Throwable' }, text: { summary: 'Base de excepciones (try/catch/throw).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Error' }, text: { summary: 'Objeto global de error del sistema.' } },
] as const satisfies readonly PbSystemSymbolLocalizationOverlay[];






