import type { PbSystemSymbolLocalizationOverlay } from '../../../../types';

/**
 * Spanish localization overlays for manual visual domain entries.
 * These overlays preserve the original Spanish summaries that were
 * previously embedded directly in the manual base files.
 */
export const PB_SYSTEM_SYMBOL_LOCALIZATION_ES_MANUAL_VISUAL = [
	// — List controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DropDownListBox' }, text: { summary: 'Lista desplegable visual.', documentation: 'Un control DropDownListBox combina las características de un ListBox y un SingleLineEdit. En algunos DropDownListBoxes, el usuario puede seleccionar un elemento ingresando su nombre en el cuadro de texto. En otros, el usuario no puede modificar el cuadro de texto y debe hacer clic en el elemento o presionar la primera letra del mismo para seleccionarlo. En el entorno de desarrollo, si la parte de la lista no se muestra porque ShowList está en FALSE, el usuario debe hacer clic en la flecha hacia abajo al final del cuadro de texto para desplegarla.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DropDownPictureListBox' }, text: { summary: 'Lista desplegable visual con imágenes.', documentation: 'Un control DropDownPictureListBox es similar a un DropDownListBox, pero añade imágenes asociadas a los elementos de la lista. Las imágenes pueden ser mapas de bits (.BMP), iconos (.ICO), cursores (.CUR), archivos GIF (no animados) o archivos JPEG. En el entorno de desarrollo, si la lista no se muestra porque ShowList está en FALSE, el usuario debe hacer clic en la flecha hacia abajo para desplegarla.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ListBox' }, text: { summary: 'Lista visual de selección.', documentation: 'Un ListBox muestra opciones o valores disponibles. Si hay más opciones de las que caben en el control o si el texto excede el ancho del mismo, el ListBox muestra una o dos barras de desplazamiento (vertical u horizontal).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ListView' }, text: { summary: 'Control visual de lista detallada.', documentation: 'Un ListView muestra información en forma de lista. Cada elemento del ListView consiste en texto e imágenes, que pueden manipularse durante la ejecución de la aplicación.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'ListViewItem' }, text: { summary: 'Ítem de un control ListView.', documentation: 'Un objeto ListViewItem es una estructura del sistema que puebla un control ListView. Los elementos ListViewItem no tienen eventos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PictureListBox' }, text: { summary: 'Lista visual con imágenes.', documentation: 'Un PictureListBox muestra opciones o valores que pueden incluir imágenes. Si hay más elementos de los que pueden mostrarse o el texto es muy ancho, el control muestra barras de desplazamiento. Soporta formatos como BMP, CUR, ICO, GIF (no animados), JPEG y PNG.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Tab' }, text: { summary: 'Control visual con pestañas.', documentation: 'Un control Tab contiene páginas de pestañas, que son objetos de usuario que contienen controles. Las páginas pueden definirse dentro del control Tab o en el pintor de User Object. Cada página puede tener su propia etiqueta, imagen y color de fondo. Todas comparten la misma configuración de fuente. Las pestañas pueden mostrarse en cualquiera de los cuatro bordes del control.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TabbedBar' }, text: { summary: 'Barra de pestañas visual para navegación entre páginas.', documentation: 'Actualmente, el control TabbedBar solo se usa para implementar la barra de pestañas en ventanas MDI/MDIHelp. Si se habilita TabbedView para una ventana MDI, PowerBuilder añade automáticamente un control mditbb_1 a la ventana.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TreeView' }, text: { summary: 'Control visual jerárquico.', documentation: 'Un control TreeView es una visualización jerárquica de información. Cada elemento consiste en texto e imágenes que pueden manipularse durante la ejecución.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'TreeViewItem' }, text: { summary: 'Ítem de un control TreeView.', documentation: 'Un TreeViewItem es una estructura del sistema que define las propiedades de los elementos individuales en un control TreeView. No tiene eventos.' } },

	// — Drawing controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Graph' }, text: { summary: 'Control visual para gráficos y charts.', documentation: 'Un gráfico es una representación de una serie de puntos de datos (valores). El gráfico puede tener una sola serie de valores o múltiples series.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'grAxis' }, text: { summary: 'Configuración de ejes para un control Graph.', documentation: 'La clase grAxis se utiliza como parte de un control de gráfico. Cada gráfico tiene tres objetos grAxis: Categoría, Serie y Valores. Para referirse a una propiedad de un eje, use la sintaxis: nombrecontrolgrafico.nombreje.propiedad (ej. gr_1.Series.AutoScale). No tiene eventos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'grDispAttr' }, text: { summary: 'Atributos de visualización para elementos de un Graph.', documentation: 'La clase grDispAttr especifica la apariencia de los objetos de texto en un gráfico (títulos, leyendas, etiquetas de ejes, etc.). Para referirse a una propiedad, use la sintaxis: nombrecontrolgrafico.nombreje.nombregrdispattr.propiedad. No tiene eventos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Line' }, text: { summary: 'Objeto visual de línea.', documentation: 'Un objeto de dibujo de línea es una línea recta única, sólida o discontinua.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Oval' }, text: { summary: 'Objeto visual ovalado.', documentation: 'Un óvalo es un objeto de dibujo redondo o elíptico, relleno o delineado, que se utiliza típicamente para efectos de diseño.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Picture' }, text: { summary: 'Control visual de imagen.', documentation: 'Los controles Picture pueden contener imágenes en formatos BMP, RLE, WMF, GIF (animados o no), JPEG y PNG.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PictureHyperLink' }, text: { summary: 'Hipervínculo visual basado en imagen.', documentation: 'El control PictureHyperLink desciende de Picture. Su propiedad URL permite proporcionar un enlace directo a una página web que se abrirá en el navegador del usuario al hacer clic. Soporta formatos BMP, RLE, WMF, GIF, JPEG y PNG.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Rectangle' }, text: { summary: 'Objeto visual rectangular.', documentation: 'Un rectángulo es una forma rectangular rellena o delineada dentro de una ventana, utilizada típicamente para propósitos de diseño u organización visual de controles.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RoundRectangle' }, text: { summary: 'Objeto visual rectangular con esquinas redondeadas.', documentation: 'Un RoundRectangle es un objeto de dibujo rectangular con esquinas redondeadas utilizado para propósitos de diseño.' } },

	// — Data/UI controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Animation' }, text: { summary: 'Control visual para animaciones integradas.', documentation: 'Los controles de animación pueden mostrar clips de Audio-Video Interleaved (AVI) provenientes de un archivo AVI no comprimido o comprimido mediante codificación de longitud de ejecución (BI_RLE8).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'CheckBox' }, text: { summary: 'Control visual de casilla de verificación.', documentation: 'Los controles CheckBox son pequeñas casillas cuadradas utilizadas para establecer opciones independientes. Cuando se seleccionan, muestran una marca (típicamente una X o un check). Pueden tener dos estados (activado/desactivado) o tres (incluyendo un estado grisáceo o desconocido).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'CommandButton' }, text: { summary: 'Botón de comando visual.', documentation: 'Se utiliza un CommandButton para llevar a cabo una acción. Por ejemplo, se puede usar un botón OK para confirmar una eliminación o un botón Cancel para cancelarla.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DatePicker' }, text: { summary: 'Selector visual de fecha.', documentation: 'Un control DatePicker facilita la selección de una fecha por parte del usuario. Tiene dos partes: un cuadro de lista desplegable que muestra la fecha en el formato seleccionado y una cuadrícula que se asemeja al control MonthCalendar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'GroupBox' }, text: { summary: 'Contenedor visual para agrupar controles.', documentation: 'Un GroupBox es un cuadro utilizado para agrupar controles relacionados. Si contiene RadioButtons, el usuario solo puede seleccionar uno a la vez. Ocultar o mostrar el GroupBox no afecta automáticamente la visibilidad de los controles contenidos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'HProgressBar' }, text: { summary: 'Barra de progreso horizontal.', documentation: 'Se utiliza para indicar el progreso de una operación larga. Es un rectángulo horizontal que se llena con el color de resaltado del sistema a medida que la operación avanza.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'HScrollBar' }, text: { summary: 'Barra de desplazamiento horizontal.', documentation: 'Una barra horizontal con flechas en ambos extremos y un cuadro de desplazamiento. Se usa típicamente como control deslizante para especificar valores en una escala continua.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'HTrackBar' }, text: { summary: 'Trackbar horizontal visual.', documentation: 'Similar a una barra de desplazamiento, pero su deslizador se mueve en incrementos discretos. Tiene una serie de marcas (ticks) a lo largo del canal. Se usa cuando se quiere que el usuario seleccione un valor discreto específico.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'InkPicture' }, text: { summary: 'Control visual para imágenes de tinta.', documentation: 'Un control InkPicture recopila entrada de lápiz ("tinta") en una Tablet PC y la superpone sobre una imagen. Se usa para anotaciones o firmas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MonthCalendar' }, text: { summary: 'Calendario mensual visual.', documentation: 'Un control MonthCalendar proporciona una interfaz de usuario similar a un calendario que facilita a los usuarios la entrada o selección de fechas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PictureButton' }, text: { summary: 'Botón visual con imagen.', documentation: 'Un PictureButton muestra una imagen y, al igual que un CommandButton, se utiliza para llevar a cabo una acción. Soporta formatos BMP, RLE, WMF, GIF, JPEG y PNG.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RadioButton' }, text: { summary: 'Control visual de opción única.', documentation: 'Un RadioButton es un pequeño botón redondo que se utiliza para activar o desactivar una opción. Cuando la opción está activada, el botón tiene un centro oscuro. En un GroupBox, el usuario solo puede seleccionar un botón del grupo a la vez.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'VProgressBar' }, text: { summary: 'Barra de progreso vertical.', documentation: 'Se utiliza para indicar el progreso de una operación larga. Es un rectángulo vertical que se llena con el color de resaltado del sistema a medida que la operación progresa.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'VScrollBar' }, text: { summary: 'Barra de desplazamiento vertical.', documentation: 'Una barra vertical con flechas en ambos extremos y un cuadro de desplazamiento. Se usa típicamente como control deslizante para especificar valores en una escala continua.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'VTrackBar' }, text: { summary: 'Trackbar vertical visual.', documentation: 'Similar a una barra de desplazamiento, pero su deslizador se mueve en incrementos discretos. Tiene marcas (ticks) a la derecha del canal. Se usa cuando se quiere que el usuario seleccione un valor discreto específico.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'WebBrowser' }, text: { summary: 'Control visual de navegador embebido.', documentation: 'El control WebBrowser puede utilizarse para crear un navegador web que puede comunicarse entre una página web y el cliente de la aplicación PowerBuilder.' } },

	// — Text controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'EditMask' }, text: { summary: 'Control de edición con máscara.', documentation: 'Un EditMask es un cuadro similar a SingleLineEdit en el que el usuario puede ingresar texto restringido por una máscara. Por ejemplo, se usa para formatear automáticamente números de teléfono o fechas.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'InkEdit' }, text: { summary: 'Control de tinta y escritura manuscrita.', documentation: 'Un control InkEdit recopila entrada de lápiz ("tinta") en una Tablet PC y la convierte en texto. Se utiliza con el motor de reconocimiento de escritura manuscrita que forma parte de la plataforma Tablet PC. Nota: Al usar características de animación, es posible que los controles InkEdit no se dibujen correctamente.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MultiLineEdit' }, text: { summary: 'Control visual de edición multilínea.', documentation: 'Un control MultiLineEdit es un cuadro rectangular en el que el usuario puede ingresar y editar múltiples líneas de texto. Se utiliza típicamente como un campo de entrada.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RichTextEdit' }, text: { summary: 'Editor visual de texto enriquecido.', documentation: 'Un control RichTextEdit contiene un documento que se muestra como texto formateado. Puede incluir campos de entrada vinculados a un control DataWindow. Cuando los datos de un DataWindow se comparten con el control RichTextEdit, existe una instancia del documento que puede visualizarse múltiples veces con diferentes datos de fila. Los campos de entrada cuyos nombres coinciden con las columnas del DataWindow se completan con datos de la fila actual. Editores de texto enriquecido: Puede seleccionar entre los editores soportados por Appeon PowerBuilder. El editor seleccionado será aplicable al control RichTextEdit, al objeto DataWindow RichText y al estilo de edición RichText. Para más información sobre estos editores, consulte la sección "Rich text editors" en las Técnicas de Aplicación; para diferencias de características, consulte la sección "Feature difference between TX Text Control (64-bit) and Microsoft RichEdit Control (64-bit)". Nota: Al usar características de animación, es posible que los controles RichTextEdit no se dibujen correctamente.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'SingleLineEdit' }, text: { summary: 'Control visual de edición de una sola línea.', documentation: 'Un control SingleLineEdit es un cuadro rectangular en el que el usuario puede ingresar y editar una sola línea de texto. Se utiliza típicamente para campos de entrada simples.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'StaticHyperLink' }, text: { summary: 'Etiqueta de hipervínculo visual.', documentation: 'El control StaticHyperLink es un descendiente de StaticText. Su propiedad URL permite proporcionar un enlace directo a una página web. Cuando el usuario hace clic, el navegador predeterminado abre la página especificada. Nota de uso: Si los usuarios tienen navegadores que soportan autocompletado de URL, puede ingresar una dirección parcial (ej. appeon.com); siempre puede ingresar una dirección completa (ej. http://www.appeon.com).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'StaticText' }, text: { summary: 'Etiqueta de texto estático visual.', documentation: 'StaticText es un texto que el usuario puede seleccionar pero no modificar con el teclado. Puede modificarlo explícitamente mediante scripts.' } },

	// — Ribbon controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonBar' }, text: { summary: 'Barra visual tipo ribbon.', documentation: 'Un control RibbonBar permite crear cintas de opciones que organizan los comandos del usuario en grupos lógicos. Una cinta puede reemplazar la barra de menús y herramientas tradicional con páginas con pestañas (Categorías), divididas en paneles que contienen botones, casillas de verificación y cuadros combinados.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonItem' }, text: { summary: 'Base de elementos interactivos usados por RibbonBar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonApplicationButtonItem' }, text: { summary: 'Botón principal de la aplicación en un RibbonBar.', documentation: 'Define el botón de aplicación en el control RibbonBar. Solo se permite un botón de aplicación por barra de cinta.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonApplicationMenu' }, text: { summary: 'Menú principal de aplicación asociado a un RibbonBar.', documentation: 'Define un menú de aplicación que se asocia con el botón de aplicación. Contiene un menú maestro y un menú de elementos recientes.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonCategoryItem' }, text: { summary: 'Categoría de primer nivel dentro de un RibbonBar.', documentation: 'Define una categoría (pestaña) en el control RibbonBar. Es el contenedor padre de los objetos RibbonPanelItem.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonCheckBoxItem' }, text: { summary: 'Ítem check box usado dentro de paneles o grupos del Ribbon.', documentation: 'Define una casilla de verificación dentro de un panel o grupo de la barra Ribbon.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonComboBoxItem' }, text: { summary: 'Ítem combo box usado dentro de paneles o grupos del Ribbon.', documentation: 'Define un cuadro combinado (combo box) dentro de la barra Ribbon.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonGroupItem' }, text: { summary: 'Grupo lógico de controles dentro de un panel del Ribbon.', documentation: 'Define un grupo dentro de un panel de la barra Ribbon para organizar controles relacionados.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonLargeButtonItem' }, text: { summary: 'Botón grande usado dentro de un RibbonBar.', documentation: 'Define un botón de tamaño grande en el control RibbonBar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonMenu' }, text: { summary: 'Menú contextual o asociado a botones del Ribbon.', documentation: 'Define un menú que puede asociarse con botones de pestaña, botones grandes o pequeños en el RibbonBar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonMenuItem' }, text: { summary: 'Ítem de menú usado en menús Ribbon y application menus.', documentation: 'Define un ítem de menú para el menú de aplicación o el menú de cinta. Puede ser de tipo Normal, Separador o Reciente.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonPanelItem' }, text: { summary: 'Panel que agrupa grupos y botones dentro de una categoría Ribbon.', documentation: 'Define un panel dentro de una categoría del RibbonBar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonSmallButtonItem' }, text: { summary: 'Botón pequeño usado dentro de un RibbonBar.', documentation: 'Define un botón de tamaño pequeño en el control RibbonBar.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'RibbonTabButtonItem' }, text: { summary: 'Botón de pestaña integrado en un RibbonBar.', documentation: 'Define un botón de pestaña en el control RibbonBar.' } },

	// — Visual objects —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Window' }, text: { summary: 'Ventana de la interfaz de usuario.', documentation: 'Las ventanas son la interfaz principal entre el usuario y una aplicación PowerBuilder. Pueden mostrar información, solicitarla y responder a acciones del mouse o teclado. Incluyen propiedades (estilo), eventos (scripts) y funciones.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MDIFrame' }, text: { summary: 'Ventana marco MDI que hospeda hojas, toolbars y menús.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MDIClient' }, text: { summary: 'Área cliente MDI que contiene las hojas hijas dentro del marco.', documentation: 'Un objeto MDIClient es el área donde se muestran las hojas (sheets) abiertas en un marco MDI estándar. PowerBuilder ajusta el tamaño del MDIClient para que llene el espacio dentro del marco.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'DataWindow' }, text: { summary: 'Control DataWindow visual.', documentation: 'Los controles DataWindow se colocan en una ventana u objeto de usuario para mostrar y manipular datos. El objeto DataWindow asociado permite visualizar, manipular y actualizar información de la base de datos.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'Menu' }, text: { summary: 'Menú de la interfaz de usuario.', documentation: 'Se utiliza el pintor de Menú para crear menús y barras de herramientas. Los menús son listas de comandos u opciones que el usuario puede seleccionar. Pueden aparecer en una barra de menús, menús desplegables o menús contextuales (pop-up).' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'MenuCascade' }, text: { summary: 'Elemento de menú en cascada que expone un submenú.', documentation: 'Los objetos de menú contenidos dentro de un MenuCascade aparecen como una paleta de botones desplegables.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'UserObject' }, text: { summary: 'Base de user objects visuales.', documentation: 'Los UserObjects son objetos visuales personalizados que se construyen para complementar los objetos estándar de PowerBuilder. Pueden mostrar información, solicitarla y responder a acciones del usuario.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'PowerServerLabel' }, text: { summary: 'Etiqueta visual especializada para PowerServer.', documentation: 'Un objeto de sistema PowerServerLabel se utiliza para agrupar y enviar múltiples solicitudes al servidor en modo merge. Este objeto y sus funciones solo tienen efecto cuando la aplicación se despliega mediante PowerServer.' } },

	// — OLE visual controls —
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLEControl' }, text: { summary: 'Control OLE visual insertable.', documentation: 'Un OLEControl colocado en una ventana puede contener un objeto (ej. hoja de cálculo o documento) creado por una aplicación compatible con OLE. El usuario puede activar el objeto y editarlo en su aplicación de origen.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'OLECustomControl' }, text: { summary: 'Control OLE ActiveX personalizado.' } },
	{ locale: 'es', reviewed: true, source: 'manual-curated', targetKey: { domain: 'system-object-datatypes', kind: 'system-type', namespace: 'powerbuilder-runtime', invocation: 'global', name: 'WindowActiveX' }, text: { summary: 'Control visual ActiveX que hospeda una ventana PowerBuilder embebida.' } },
] as const satisfies readonly PbSystemSymbolLocalizationOverlay[];
