'use strict';

const fs = require('node:fs/promises');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..');
const outputRoot = path.join(repoRoot, 'artifacts', 'catalog');

function formatPercent(value) {
  return `${(value * 100).toFixed(2)}%`;
}

function buildMarkdownReport(report) {
  const lines = [
    '# Catalog Localization Report',
    '',
    'Generated by: npm run report:catalog-localization',
    `Schema version: ${report.schemaVersion ?? 'unknown'}`,
    '',
  ];

  const locales = Object.entries(report.locales ?? {}).sort(([left], [right]) => left.localeCompare(right));
  for (const [locale, summary] of locales) {
    lines.push(`## Locale ${locale}`);
    lines.push('');
    lines.push(`- overlays: ${summary.overlayCount}`);
    lines.push(`- reviewed: ${summary.reviewedCount}`);
    lines.push(`- targetId: ${summary.targetIdCount}`);
    lines.push(`- targetKey: ${summary.targetKeyCount}`);
    lines.push(`- orphans: ${summary.orphanCount}`);
    lines.push('');
    lines.push('| Domain | Localized | Reviewed | Total | Localized % | Reviewed % |');
    lines.push('| --- | ---: | ---: | ---: | ---: | ---: |');

    const domains = Object.values(report.domainCoverage?.[locale] ?? {}).sort((left, right) => left.domain.localeCompare(right.domain));
    for (const domain of domains) {
      lines.push(`| ${domain.domain} | ${domain.localizedTargetCount} | ${domain.reviewedTargetCount} | ${domain.totalTargetCount} | ${formatPercent(domain.localizedRatio)} | ${formatPercent(domain.reviewedRatio)} |`);
    }
    lines.push('');
  }

  lines.push('## Incomplete overlays');
  lines.push('');
  if ((report.incompleteOverlays?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const overlay of report.incompleteOverlays) {
      lines.push(`- ${overlay.locale} :: ${overlay.domain} :: ${overlay.targetName} :: missing ${overlay.missingFields.join(', ')}`);
    }
  }
  lines.push('');

  lines.push('## Missing fields by domain');
  lines.push('');
  if ((report.missingFieldsByDomain?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const summary of report.missingFieldsByDomain) {
      const fields = Object.entries(summary.fieldCounts ?? {})
        .sort(([left], [right]) => left.localeCompare(right))
        .map(([field, count]) => `${field}:${count}`)
        .join(', ');
      lines.push(`- ${summary.locale} :: ${summary.domain} :: ${fields || 'none'}`);
    }
  }
  lines.push('');

  lines.push('## Invalid parameter targets');
  lines.push('');
  if ((report.invalidParameterTargets?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const issue of report.invalidParameterTargets) {
      lines.push(`- ${issue.locale} :: ${issue.domain} :: ${issue.targetName} :: ${issue.signatureLabel} -> ${issue.parameterName}`);
    }
  }
  lines.push('');

  lines.push('## Recovered targetIds');
  lines.push('');
  if ((report.recoveredTargetIds?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const recovery of report.recoveredTargetIds) {
      lines.push(`- ${recovery.locale} :: ${recovery.domain} :: ${recovery.targetName} :: ${recovery.previousTargetId} -> ${recovery.targetEntryId}`);
    }
  }
  lines.push('');

  lines.push('## Orphan overlays');
  lines.push('');
  if ((report.orphanOverlays?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const orphan of report.orphanOverlays) {
      lines.push(`- ${orphan.locale} :: ${orphan.reason} :: ${orphan.targetId ?? '(sin targetId)'}`);
    }
  }
  lines.push('');

  lines.push('## Schema issues');
  lines.push('');
  if ((report.schemaIssues?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const issue of report.schemaIssues) {
      lines.push(`- ${issue.locale} :: ${issue.code} :: ${issue.domain ?? '(sin dominio)'} :: ${issue.targetName ?? issue.targetId ?? '(sin target)'}${issue.details?.length ? ` :: ${issue.details.join(', ')}` : ''}`);
    }
  }
  lines.push('');

  return `${lines.join('\n')}\n`;
}

async function main() {
  const { buildCatalogConsistencyReport } = require(path.join(
    repoRoot,
    'out',
    'server',
    'knowledge',
    'system',
    'consistency',
  ));

  const generatedAt = new Date().toISOString();
  const localization = buildCatalogConsistencyReport().localization;

  await fs.mkdir(outputRoot, { recursive: true });
  await fs.writeFile(
    path.join(outputRoot, 'catalogLocalizationReport.generated.json'),
    `${JSON.stringify(localization, null, 2)}\n`,
    'utf8',
  );
  await fs.writeFile(
    path.join(outputRoot, 'catalogLocalizationReport.generated.md'),
    buildMarkdownReport(localization),
    'utf8',
  );

  console.log('Reporte de localización del catálogo generado.');
  console.log(`  schemaVersion: ${localization.schemaVersion}`);
  console.log(`  locales: ${Object.keys(localization.locales ?? {}).join(', ') || 'ninguna'}`);
  console.log(`  incompleteOverlays: ${localization.incompleteOverlays.length}`);
  console.log(`  missingFieldsByDomain: ${localization.missingFieldsByDomain.length}`);
  console.log(`  invalidParameterTargets: ${localization.invalidParameterTargets.length}`);
  console.log(`  recoveredTargetIds: ${localization.recoveredTargetIds.length}`);
  console.log(`  schemaIssues: ${localization.schemaIssues.length}`);
  console.log(`  orphanOverlays: ${localization.orphanOverlays.length}`);
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});