'use strict';

const fs = require('node:fs/promises');
const path = require('node:path');

const repoRoot = path.resolve(__dirname, '..');
const outputRoot = path.join(repoRoot, 'artifacts', 'catalog');

function formatPercent(value) {
  return `${(value * 100).toFixed(2)}%`;
}

function buildMarkdownReport(report, summary) {
  const compliance = summary.adrCompliance;
  const lines = [
    '# Catalog ADR-0001 Consistency Report',
    '',
    'Generated by: npm run report:catalog-consistency',
    '',
    `- Consistency status: ${summary.consistencyStatus}`,
    `- Total entries: ${summary.totalEntries ?? 0}`,
    `- Duplicates: ${summary.duplicates ?? 0}`,
    `- Missing signatures: ${summary.missingSignatures ?? 0}`,
    `- Invalid enum types: ${summary.invalidEnumTypes ?? 0}`,
    `- Generated/manual conflicts: ${summary.generatedManualConflicts ?? 0}`,
    `- Orphan localization overlays: ${summary.orphanLocalizationOverlays ?? 0}`,
  ];

  if (compliance) {
    lines.push(
      `- ADR-0001 compliance: ${compliance.status}`,
      `- Recommended policy: ${compliance.recommendedPolicy}`,
      `- Completeness mode: ${compliance.completenessMode}`,
      `- Official domains: ${compliance.officialDomainCount}`,
      `- Manual-primary domains: ${compliance.manualPrimaryDomains.join(', ') || 'none'}`,
      `- Official domains with gaps: ${compliance.officialDomainsWithGaps.join(', ') || 'none'}`,
      `- Coverage drift domains: ${compliance.officialCoverageDriftDomains.join(', ') || 'none'}`,
      `- Overlay counts: gap=${compliance.overlayCounts.gap}, enrichment=${compliance.overlayCounts.enrichment}, override=${compliance.overlayCounts.override}, candidate=${compliance.overlayCounts.candidate}`,
      `- Candidate hot path violations: ${compliance.candidateHotPathViolations}`,
      `- Scraper errors: ${compliance.scraperErrorCount}`,
      `- Localization policy drift: incomplete=${compliance.localizationIncompleteOverlays}, invalidParameters=${compliance.localizationInvalidParameterTargets}, recoveredTargetIds=${compliance.localizationRecoveredTargetIds}`,
      `- Issue count: ${compliance.issueCount}`,
    );
  }

  lines.push('', '## Dataset Counts', '', '| Dataset | Count |', '| --- | ---: |');
  for (const [dataset, count] of Object.entries(report.datasetCounts ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`| ${dataset} | ${count} |`);
  }

  lines.push('', '## Domain Counts', '', '| Domain | Count |', '| --- | ---: |');
  for (const [domain, count] of Object.entries(report.domainCounts ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`| ${domain} | ${count} |`);
  }

  lines.push('', '## Overlay Counts', '', '| Mode | Count |', '| --- | ---: |');
  for (const mode of ['gap', 'enrichment', 'override', 'candidate']) {
    lines.push(`| ${mode} | ${report.manualOverlayModes?.[mode] ?? 0} |`);
  }

  lines.push('', '## Provenance', '', '| Group | Count |', '| --- | ---: |');
  for (const [kind, count] of Object.entries(report.provenance.byKind ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`| kind:${kind} | ${count} |`);
  }
  for (const [authority, count] of Object.entries(report.provenance.byAuthority ?? {}).sort(([left], [right]) => left.localeCompare(right))) {
    lines.push(`| authority:${authority} | ${count} |`);
  }

  lines.push('', '## Adoption by Domain', '', '| Domain | Policy | Official | Generated | Manual | Gaps | Enrichments | Overrides | Candidates | Missing | Scraper errors |', '| --- | --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const domainReport of Object.values(report.adoption.domains ?? {}).filter(Boolean).sort((left, right) => left.domain.localeCompare(right.domain))) {
    lines.push(`| ${domainReport.domain} | ${domainReport.recommendedPolicy} | ${domainReport.officialCount} | ${domainReport.generatedCount} | ${domainReport.manualCount} | ${domainReport.gapCount} | ${domainReport.enrichmentCount} | ${domainReport.overrideCount} | ${domainReport.candidateCount} | ${domainReport.officialCoverage?.missingCount ?? 0} | ${domainReport.scraperErrorCount} |`);
  }

  lines.push('', '## Quality Summary', '', '| Dataset | Signature | Applies To | Owner Types | Event IDs | Return Types | Hover | Signature Help |', '| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const [label, metrics] of [['generated', report.adoption.summary.generated], ['manual', report.adoption.summary.manual]]) {
    lines.push(`| ${label} | ${formatPercent(metrics.signatureQuality.ratio)} | ${formatPercent(metrics.appliesToQuality.ratio)} | ${formatPercent(metrics.ownerTypesQuality.ratio)} | ${formatPercent(metrics.eventIdCoverage.ratio)} | ${formatPercent(metrics.returnTypeCoverage.ratio)} | ${formatPercent(metrics.hoverUsefulness.ratio)} | ${formatPercent(metrics.signatureHelpUsefulness.ratio)} |`);
  }

  lines.push('', '## Rationale', '');
  if ((report.adoption.summary.rationale?.length ?? 0) === 0) {
    lines.push('- none');
  } else {
    for (const reason of report.adoption.summary.rationale) {
      lines.push(`- ${reason}`);
    }
  }

  lines.push('', '## No-action Decisions', '', `- Manual-primary domains remain allowed while no official rail exists: ${compliance?.manualPrimaryDomains.join(', ') || 'none'}.`, `- Candidates stay outside the hot path; current violations: ${compliance?.candidateHotPathViolations ?? 0}.`);

  return `${lines.join('\n')}\n`;
}

async function main() {
  const { buildCatalogConsistencyReport } = require(path.join(
    repoRoot,
    'out',
    'server',
    'knowledge',
    'system',
    'consistency',
  ));
  const { buildWorkspaceCheckCatalogSummary } = require(path.join(
    repoRoot,
    'out',
    'server',
    'features',
    'workspaceCheckCatalogSummary',
  ));

  const payload = {
    schemaVersion: '1.0.0',
    generatedAt: new Date().toISOString(),
    summary: buildWorkspaceCheckCatalogSummary(),
    report: buildCatalogConsistencyReport(),
  };

  await fs.mkdir(outputRoot, { recursive: true });
  await fs.writeFile(
    path.join(outputRoot, 'catalogConsistencyReport.generated.json'),
    `${JSON.stringify(payload, null, 2)}\n`,
    'utf8',
  );
  await fs.writeFile(
    path.join(outputRoot, 'catalogConsistencyReport.generated.md'),
    buildMarkdownReport(payload.report, payload.summary),
    'utf8',
  );

  console.log('Reporte de consistencia ADR-0001 del catalogo generado.');
  console.log(`  consistency: ${payload.summary.consistencyStatus}`);
  console.log(`  adrCompliance: ${payload.summary.adrCompliance?.status ?? 'unknown'}`);
  console.log(`  policy: ${payload.summary.adrCompliance?.recommendedPolicy ?? 'unknown'}`);
  console.log(`  issueCount: ${payload.summary.adrCompliance?.issueCount ?? 0}`);
}

main().catch(error => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});