export {
  PB_MANUAL_CORE_SYSTEM_GLOBALS,
  PB_MANUAL_CORE_SYSTEM_GLOBAL_CATEGORIES,
} from './systemGlobals';
export * from './systemTypes';
export * from './errors';
export * from './reflection';
export * from './ole';
export * from './mail';
export * from './profiling';

import { PbSystemSymbolEntry } from '../../types';
import {
  PB_MANUAL_CORE_RUNTIME_ERROR_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_ERRORS,
} from './errors';
import {
  PB_MANUAL_CORE_RUNTIME_MAIL_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_MAIL_TYPES,
} from './mail';
import {
  PB_MANUAL_CORE_RUNTIME_OLE_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_OLE_TYPES,
} from './ole';
import {
  PB_MANUAL_CORE_RUNTIME_PROFILING_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_PROFILING_TYPES,
} from './profiling';
import {
  PB_MANUAL_CORE_RUNTIME_REFLECTION_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_REFLECTION_TYPES,
} from './reflection';
import {
  PB_MANUAL_CORE_RUNTIME_BASE_SYSTEM_OBJECT_DATATYPE_CATEGORIES,
  PB_MANUAL_CORE_RUNTIME_BASE_SYSTEM_OBJECT_DATATYPES,
} from './systemTypes';

export const PB_MANUAL_CORE_RUNTIME_SYSTEM_OBJECT_DATATYPE_CATEGORIES: readonly string[] = [
  ...PB_MANUAL_CORE_RUNTIME_BASE_SYSTEM_OBJECT_DATATYPE_CATEGORIES,
  ...PB_MANUAL_CORE_RUNTIME_ERROR_CATEGORIES,
  ...PB_MANUAL_CORE_RUNTIME_REFLECTION_CATEGORIES,
  ...PB_MANUAL_CORE_RUNTIME_OLE_CATEGORIES,
  ...PB_MANUAL_CORE_RUNTIME_MAIL_CATEGORIES,
  ...PB_MANUAL_CORE_RUNTIME_PROFILING_CATEGORIES,
];

export const PB_MANUAL_CORE_RUNTIME_SYSTEM_OBJECT_DATATYPES: readonly PbSystemSymbolEntry[] = [
  ...PB_MANUAL_CORE_RUNTIME_BASE_SYSTEM_OBJECT_DATATYPES,
  ...PB_MANUAL_CORE_RUNTIME_ERRORS,
  ...PB_MANUAL_CORE_RUNTIME_REFLECTION_TYPES,
  ...PB_MANUAL_CORE_RUNTIME_OLE_TYPES,
  ...PB_MANUAL_CORE_RUNTIME_MAIL_TYPES,
  ...PB_MANUAL_CORE_RUNTIME_PROFILING_TYPES,
];